### ISSUE TITLE
Support for the R programming language

### ISSUE THREAD

**Issue by romain-intel** [Netflix/metaflow#1]
Metaflow is currently a Python library. Provide R bindings that would allow a Flow to be written entirely in R and use the Python library as a backend.

**Comment by ttymck** [comment]
Very excited for this feature, both to use in my projects and to learn how Netflix combines R and python! 

I am under the impression that this initial work requires porting the internal metaflow codebase to this open source project, but I wanted to ask if I there's any way I can provide assistance toward this feature. 🍻

**Comment by savingoyal** [comment]
There is a virtual workshop scheduled for Aug 7th 4PM-7PM UTC for this feature. More details [here](https://www.eventbrite.com/e/metaflow-tutorial-user-2020-registration-114326317092).

**Comment by savingoyal** [comment]
The R bindings are GA now. Documentation is available here - https://docs.metaflow.org/v/r/

**Comment by garymm** [comment]
This is still listed as future work on this page:
https://docs.metaflow.org/introduction/roadmap
