### ISSUE TITLE
Store a function as a variable and reuse across steps

### ISSUE THREAD

**Issue by mblackgeo** [Netflix/metaflow#1004]
It doesn't seem like it is possible to conditionally store a function in a member variable based on some logic. Consider the following example:

```python
from metaflow import FlowSpec, Parameter, step


class ExampleFlow(FlowSpec):
    operator = Parameter(
        "operator",
        help="Choose `add` or `subtract`.",
        default="add",
    )

    @staticmethod
    def add(a, b):
        return a + b

    @staticmethod
    def sub(a, b):
        return a - b

    @step
    def start(self):
        # Assign the function to a variable in the standard way
        self.operator_func = self.add if self.operator == "add" else self.sub

        # Storing the function in a list appears to work
        # self.operator_func = [self.add] if self.operator == "add" else [self.sub]
        self.next(self.calc)

    @step
    def calc(self):
        # This will throw an error:
        # AttributeError: Flow ExampleFlow has no attribute 'operator_func'
        print("Result:", self.operator_func(10, 5))

        # This works by storing the function in a list
        # print("Result:", self.operator_func[0](10, 5))

        self.next(self.end)

    @step
    def end(self):
        print("Finished")


if __name__ == "__main__":
    ExampleFlow()
```

Here in `start`, the `self.operator_func` is conditionally set to point to either `add` or `sub` function. Doing this in the typical way, with conditional assignment throws an `AttributeError` in the proceeding `calc` step. However, one workaround is to store the function in a list instead and that does then seem to be available in the `calc` step (see the commented out parts in the example above). Is this the expected behaviour?

Metaflow version 2.5.4

**Comment by romain-intel** [comment]
This is "expected" insofar as the logic explicitly excludes methods and functions (see here: https://github.com/Netflix/metaflow/blob/master/metaflow/datastore/task_datastore.py#L696). The reasoning behind that was to store only user level stuff (and not the functions inside the flow itself). When you wrap it in something else (a list, tuple), the check doesn't consider it to be a function so it works. I do agree that it is a bit wonky so we could maybe move to improve this.
