### ISSUE TITLE
Get the value of reserved_params inside flow step

### ISSUE THREAD

**Issue by TonyIvchenko** [Netflix/metaflow#1017]
Is that possible to get the value or `reserved_params` inside `FlowSpec` step? As for instance, how I can get the value of `max-workers` param if it is set or default value if not?

**Comment by savingoyal** [comment]
Not in a straightforward manner. There is an open ticket #571 to add them to the `current` object. One immediate workaround would be to launch your workflow as `METAFLOW_MAX_WORKERS=100 python flow.py run` and sniff the value of `METAFLOW_MAX_WORKERS` in `os.environ` but this approach wouldn't work when running on AWS Batch where the local environment variables are not passed all the way to AWS Batch.

**Comment by TonyIvchenko** [comment]
Thank you, unfortunately we need it in AWS Batch, do you have an ETA for #571

**Comment by savingoyal** [comment]
I can get a PR out next week? Would that work?

**Comment by TonyIvchenko** [comment]
Absolutely, thank you!
