### ISSUE TITLE
What is the difference between Metaflow and MLflow (the flow part)

### ISSUE THREAD

**Issue by michael135** [Netflix/metaflow#1028]
What is the difference between Metaflow and MLflow (the flow part) ?
Or what is the advantage of Metaflow ?

**Comment by savingoyal** [comment]
@michael135 Great question - there are a few overlaps between the two - particularly around logging artifacts & model registry - Metaflow versions and stores all artifacts (data, code, logs, models, etc.) by default. Outside of that, Metaflow is intended towards providing an end-to-end experience for training models. Here is a simple decision rubric if you should consider Metaflow - https://docs.metaflow.org/introduction/what-is-metaflow#should-i-use-metaflow
