### ISSUE TITLE
Flowspec instance attributes set upstream of a branch are not available after the join

### ISSUE THREAD

**Issue by matt-land** [Netflix/metaflow#103]
This is a usability issue since it breaks previously working DAGs if users add steps that follow branches.

An attribute set in the start step (self.start_time) is not accessible in the end step, because the flow has a join.

Removing the branch & join makes this work correctly.

I think this is a bug, since nothing was said in the Metaflow Basics documentation when introducing branches, to the effect that instance attributes totally stop working.

```
from datetime import datetime
import time
from metaflow import step, FlowSpec

class Debug(FlowSpec):
    @step
    def start(self):
        self.start_time = datetime.utcnow()
        self.next(self.sleep_a, self.sleep_b)

    @step
    def sleep_a(self):
        time.sleep(3)
        self.next(self.join)

    @step
    def sleep_b(self):
        time.sleep(3)
        self.next(self.join)

    @step
    def join(self, inputs):
        self.next(self.end)

    @step
    def end(self):
        print('took {}'.format(datetime.utcnow() - self.start_time))
        pass


if __name__ == '__main__':
    Debug()
```

Expected output: "took 0:00:04.832977"

Actual output: AttributeError: Flow Debug has no attribute 'start_time'

My workaround is to rehydrate the instance explicitly. This won't work for users that need to join the output of the branch steps.

```
    @step
    def join(self, inputs):
        join_hydrate(self, inputs)
        self.next(self.end)

def join_hydrate(flowspec: FlowSpec, inputs: dict) -> None:
    bag = set()
    for step in inputs:
        for item in step._datastore:
            if item.startswith('_'):
                continue
            if item == 'name':
                continue
            if item not in bag:
                bag.add(item)
                setattr(flowspec, item, step._datastore[item])

**Comment by jaychia** [comment]
You're missing a `self.merge_artifacts(inputs)` in your join method:
https://docs.metaflow.org/metaflow/basics#data-flow-through-the-graph

This method will check the incoming branches' attributes and perform a merge if possible (if the objects are the same), otherwise, it will throw an error. There's a bunch of other patterns you can use for the join as well, covered in that link above.

**Comment by savingoyal** [comment]
@matt-land Please re-open and comment on the issue if `self.merge_artifacts(...)` doesn't address your concerns.

**Comment by crypdick** [comment]
I just ran into this gotcha. I think there should be a warning if someone neglects to merge_artifacts in a join step.
