### ISSUE TITLE
Conda alternative

### ISSUE THREAD

**Issue by michellemay** [Netflix/metaflow#1035]
Hi, 

I see that the only two options for the dependency management are local or conda.  But from what I understand of the TOS of anaconda/miniconda, using their conda repository is possibly not free if someone is part of a for profit organization with 200+ individuals.

So, is there are any plans on using something else?  Or maybe the preferred way is to implement homemade decorators to call pip  manually?

Maybe I misunderstood the situation.  If this is the case, simply dismiss this question with my apologies.

**Comment by romain-intel** [comment]
Giving another option (around the pip ecosystem) is something that is definitely being looked at but we haven't yet been able to dedicate resources/time to it. I can say with a fair amount of certainty that it will happen but can't really give you a precise timeline right now.

In the meantime though, you can use the conda-forge channnel which IS free for everyone. It doesn't always have all the packages but it has quite a few. Basically, anything except the anaconda channel is fair game.

**Comment by michellemay** [comment]
Thanks for the clarification

**Comment by asmaier** [comment]
See also https://github.com/Netflix/metaflow/issues/24. Especially have a look at this temporary solution: https://github.com/Netflix/metaflow/issues/24#issuecomment-571976372

**Comment by savingoyal** [comment]
https://docs.metaflow.org/scaling/dependencies/libraries#pypi-in-action
