### ISSUE TITLE
Any reason to disallow the "root" username?

### ISSUE THREAD

**Issue by ZiminPark** [Netflix/metaflow#1042]
In this line, I found that metaflow skips the username "root".
https://github.com/Netflix/metaflow/blob/d977cd44839e82e70de3c019a9c6e6f89a3e9a04/metaflow/util.py#L163-L174

Is there any reason to disallow "root" user name? Just ask out of curiosity.
Since I often use metaflow on docker image which starts as a root user, I used to give a value to "USERNAME" environment variable.

**Comment by jackie-ob** [comment]
Thanks for the question.  This is usually considered preferred practice when it comes to security of the host system.  I.e. we want to minimize the amount of permissions a program has to what it needs to perform its function.  Some example [writeups](https://askubuntu.com/questions/16178/why-is-it-bad-to-log-in-as-root) out there.

In your case with docker, some of the security concerns _may_ be reduced - though it would still depend on the reliability of docker's isolation implementation as well as the exact way you started the container.

There are ways to create a non-root experience with docker containers.  E.g. see [this](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user).

If you prefer you may consider joining the Metaflow community slack [here](https://join.slack.com/t/outerbounds-community/shared_invite/zt-191z4huk1-hzREQivUBJw6wixPydbIqA).  Questions there will get more eyes and folks may be able share their solutions for your use case.

**Comment by ZiminPark** [comment]
Thanks for the detailed explanation. I got it.
