### ISSUE TITLE
Reading out artifacts as bytes

### ISSUE THREAD

**Issue by foggy1** [Netflix/metaflow#105]
When I access artifacts from previous flows after the fact directly via `DataArtifact` or with the shorthand (`run.data.x`), if the object is a dataframe, it reads in a dataframe for me. That's dope, but if I'd like to do something with the raw bytes of this artifact -- say, send them to some file store myself outside of the scope of any given flow -- I have to (as far as I can tell) re-dump the dataframe.

Am I missing a trick here or is this a byproduct of the way in which artifacts are stored as diffable in the local datastore by metaflow?

**Comment by romain-intel** [comment]
Are you saying you would like to dump the pickled artifact somewhere else? There is no direct API that will give you the bytes but you could use the pathspec information to basically do a file copy. Is this what you are looking for?

**Comment by romain-intel** [comment]
@foggy1, does the pathspec solution work for you. If not, could you elaborate a bit more?

**Comment by foggy1** [comment]
Apologies for the delay!

What is it that I can file copy from the pathspec in this case? Is this the pathspec off of the `DataArtifact`? That doesn't seem to point me to a file but just a task-specific identifier for that artifact. If I can do something like a file copy that sounds reasonable (although I don't know how to do this with Metaflow's api): I'm mostly wondering how, if there is binary stuff that's on disk, to avoid putting it back into memory just to move it around in its binary form. Doing so may very well _not_ involve Metaflow, but I'm not sure how to reliably grab information about where an artifact's data actually is in a manner beyond the value-fetching shortcut of `.data`.

**Comment by romain-intel** [comment]
Oops, now it's my turn to apologize for the (insane) delay; don't know how this fell off my radar. Anyways, I mistyped, I meant to say that you can do something like ```run.end_task.artifacts.<your artifact name>._object['location']```. Yes, this is hidden (we can expose it if it useful) but this should give you the location of your artifact (the file). You should then be able to do whatever you want with it (this is in the binary form, pickled and all). You can look at the other attributes in _object which will tell you how it was pickled for example.
