### ISSUE TITLE
[Bug Report] Arguments splitted when creating Argo Workflow manifest

### ISSUE THREAD

**Issue by ZiminPark** [Netflix/metaflow#1050]
When deploying to Argo Workflow with the below command, I expect every step will use the '**s3-secret**' secret.
`python parameter_flow.py --with kubernetes:secrets=s3-secret argo-workflows create`
(parameter_flow is exactly same with [the one in docs](https://docs.metaflow.org/going-to-production-with-metaflow/scheduling-metaflow-flows/scheduling-with-argo-workflows#pushing-a-flow-to-production))
But looking into the generated manifest of argo workflow, I found that '**s3-secret**' secret is split like below.

> envFrom:
>           - secretRef:
>               name: s
>           - secretRef:
>               name: '3'
>           - secretRef:
>               name: '-'
>           - secretRef:
>               name: s
>           - secretRef:
>               name: e
>           - secretRef:
>               name: c
>           - secretRef:
>               name: r
>           - secretRef:
>               name: e
>           - secretRef:
>               name: t

I'm using metaflow 2.6.1.
Could you check it?

**Comment by savingoyal** [comment]
can you try with #1048 ?
