### ISSUE TITLE
Drop `ext_info` from `METAFLOW_VERSION` env var in `@batch` and `@kubernetes`

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#1087]
https://outerboundsco.slack.com/archives/C02116BBNTU/p1658246993734459 through chat.metaflow.org

**Comment by heysujal** [comment]
@savingoyal Not able to see it even  after signing up on the workspace.

**Comment by saikonen** [comment]
additional context from the thread
- affects flows deployed with `step-functions` or `argo-workflows`, as these are the only ones setting the env var.
- `ext_info` only filled in when using metaflow extensions

**Comment by saikonen** [comment]
After testing this out, the issue should be fixed by #1329
