### ISSUE TITLE
AWS Batch Job stuck in "RUNNABLE" state

### ISSUE THREAD

**Issue by Viveckh** [Netflix/metaflow#110]
Hi there, 
So I configured everything as outlined for S3 Datastore and Batch Environment and Job Queue.
I skipped the Metadata Service / RDS Setup for the meantime.

I tried running the HelloFlow for test after the setup,
but my job seems to be stuck in the "RUNNABLE" state forever.
Metaflow logs briefly showed a "1 tasks are running" message as shown in the screenshot below, but then again went back to RUNNABLE.

I have also attached my Compute Environment Setup on AWS for reference.
![Screen Shot 2020-02-05 at 9 33 44 AM](https://user-images.githubusercontent.com/9113166/73851091-ec4bad00-47fa-11ea-93d9-086a52d7b906.png)

![Screen Shot 2020-02-04 at 4 27 08 PM](https://user-images.githubusercontent.com/9113166/73850767-54e65a00-47fa-11ea-92cf-3c676a551361.png)

**Comment by savingoyal** [comment]
@Viveckh Looks like an issue with your AWS Batch config. Since you are using spot instances, container instance acquisition time would depend on your pricing constraints. Here is more information - https://aws.amazon.com/premiumsupport/knowledge-center/batch-job-stuck-runnable-status/

**Comment by Viveckh** [comment]
I am actually using on-demand instances... I would understand the delay if I was using spot instances.

**Comment by savingoyal** [comment]
It could also depend on the kind of resources you are requesting. The job would be stuck in RUNNABLE is AWS Batch cannot fulfill the resource constraints using the instance types you have specified in your compute environment.

**Comment by Viveckh** [comment]
I eventually figured it out. Turned out it was the outbound rule in the security group that was attached to the Batch Compute Environment. After allowing a 0.0.0.0/0 egress, it worked.

Thanks for your inputs @savingoyal!
