### ISSUE TITLE
Make `log-group` and `log-stream` configurable for AWS Batch

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#1101]
https://outerbounds-community.slack.com/archives/C02116BBNTU/p1659523083731559 via chat.metaflow.org

**Comment by Limess** [comment]
This is important for us, as it's very difficult to attribute cost when someone runs a metaflow flow and logs too much data - all the logs go to `/aws/batch/job`

We've seen single jobs costing $1000+ per job in logs due to too much logging granularity and had difficulty tracking it down.

**Comment by madhur-ob** [comment]
done in https://github.com/Netflix/metaflow/pull/1767
