### ISSUE TITLE
Run shows as running forever after process is killed

### ISSUE THREAD

**Issue by sofiane-budbee** [Netflix/metaflow#1112]
Hi,
When trying to debug a flow, I had to kill it and restart it few times. Some of the runs kept showing as "Running" in the UI days after the process was killed.

When looking at the run details I found "Not tasks found".

The oldest run is now running since 121h4m

I couldn't find any way to remove it.

**Comment by savingoyal** [comment]
@sofiane-budbee There is an edge case in the UI that can cause this behavior. You can also tweak [some environment variables](https://github.com/Netflix/metaflow-service/blob/master/services/ui_backend_service/docs/environment.md#heartbeat-intervals) in the UI deployment to alter the behavior and mark old zombie runs as failed.
