### ISSUE TITLE
Does metaflow support SPOT GPU instance?

### ISSUE THREAD

**Issue by menon92** [Netflix/metaflow#1137]
Spot GPU is low cost gpu provide by cloud provider https://aws.amazon.com/ec2/spot/pricing/

**Comment by savingoyal** [comment]
@menon92 It does! You can configure spot instances either in [AWS Batch](https://aws.amazon.com/getting-started/hands-on/run-batch-jobs-at-scale-with-ec2-spot/) or in [Kubernetes](https://aws.amazon.com/getting-started/hands-on/amazon-eks-with-spot-instances/).
