### ISSUE TITLE
Environment dependency install version locking

### ISSUE THREAD

**Issue by avicennax** [Netflix/metaflow#114]
Hi guys,

Wanted to discuss dependency version locking for python dependencies installed in during environment bootstrap ([here](https://github.com/Netflix/metaflow/blob/master/metaflow/environment.py#L82)). Consider the case where a user is using a custom image for a step executed using AWS Batch - the Python dependencies installed in the container could be compatible with those Batch command `pip install` deps at testing/deployment time. However, at some later point in time, while in production, the latest PYPI releases for those deps introduces a conflict causing the Batch job to fail in production.

My suspicion is that the maintainers are using the current mechanism to force Metaflow to stay up to date with AWS SDK/CLI deps. Curious to hear thoughts here.

Cheers,
Simon

**Comment by savingoyal** [comment]
Hi @avicennax, we install `awscli`, `click`, `requests` and `boto3` only if they don't already exist on the container. Our recommendation is to use the [`@conda`](https://docs.metaflow.org/metaflow/dependencies) feature of metaflow to specify and isolate your runtime environment. Metaflow, by itself, depends on the stable API introduced by these dependencies.

**Comment by avicennax** [comment]
Interesting - in my case `boto3` was installed on the image already but still re-installed in the Batch command. If thats case - my container environment is probably violating some Metaflow assumptions. I'll dig a little deeper.

My case aside -  that makes sense to me. Just lock in those dependencies with specified versions using the `@conda` decorator.

Thanks!
