### ISSUE TITLE
Documentation for classes

### ISSUE THREAD

**Issue by ghost** [Netflix/metaflow#115]
Hello, thank you for the excellent package. I have gone through the documentation available on the [site](https://docs.metaflow.org/), however, I couldn't find class-specific docs like its public properties and methods. For example, I was looking at IncludeFile and only found an [example](https://docs.metaflow.org/metaflow/data#data-in-local-files) of how to use it. I know there are mentions in the [tutorials](https://github.com/Netflix/metaflow/blob/master/metaflow/tutorials/02-statistics/stats.py) and I can always peek into the [source code](https://github.com/Netflix/metaflow/blob/master/metaflow/includefile.py) but I was wondering if you guys have this information available somewhere centrally. 

Again, thanks for building and open-sourcing metaflow!

**Comment by savingoyal** [comment]
Thanks for the feedback @syedsadiqalinaqvi. We will add class docs to the main doc site by our next release.

**Comment by savingoyal** [comment]
All public APIs are now documented at https://docs.metaflow.org/api
