### ISSUE TITLE
Running a flow without a CLI

### ISSUE THREAD

**Issue by syedsadiqalinaqvi** [Netflix/metaflow#116]
Hi. So far I've only seen examples where flows are run from the command line like

```
python my_flow.py run
```

Is there a way to use them as part of another function? Let's say from a flask server?

```
from my_flow import MyFlow
from flask import Flask

app = Flask(__name__)
@app.route('/')
def hello_world():
    # does some work, then
    MyFlow()
    return 'Hello, World!'

if __name__ == "__main__":
    app.run(host='0.0.0.0')
```

**Comment by savingoyal** [comment]
@syedsadiqalinaqvi We don't have an API for launching flows programmatically, but you should be able to use `subprocess.run` to execute the flow from within another python script.

**Comment by romain-intel** [comment]
Closing as this is a subset of #117 .

**Comment by chanansh** [comment]
@savingoyal, the problem with the subprocess approach is that you cannot pass the output of the flow into a different flow. If there is a way to do that, please let me know.
