### ISSUE TITLE
DAG Visualization

### ISSUE THREAD

**Issue by AbdAlRahman-Odeh-99** [Netflix/metaflow#1170]
Greeting,

I am using Metaflow with local storage. I need to visualize the DAG of my workflow. Any idea how could this be done ?

Thank you for your help

**Comment by shrinandj** [comment]
Hey @AbdAlRahman-Odeh-99 this might help you visualize the DAG of your workflow: https://docs.metaflow.org/metaflow/visualizing-results

**Comment by AshirBorah** [comment]
`python _name_of_script.py_ output-dot | dot -Tpng -o _output_file_name.png_` 
You will need to install Graphviz but this should work
