### ISSUE TITLE
Argo workflows security context causing metaflow init script to fail

### ISSUE THREAD

**Issue by dbragdon1** [Netflix/metaflow#1176]
I've followed Argo Workflows' security context guidelines [here](https://argoproj.github.io/argo-workflows/workflow-pod-security-context/) to restrict the permissions of my workflow pods. 

My argo workflows controller is configured with the following settings:

```yaml
workflowDefaults:
   securityContext:
      runAsNonRoot: true
      runAsUser: 1000
```
My metaflow python script looks like this:

```python
from metaflow import FlowSpec, step


class MetaFlowTest(FlowSpec):
    @step
    def start(self):
        print("This is a start")

        self.next(self.end)

    @step
    def end(self):
        print("This is the end")


if __name__ == "__main__":
    MetaFlowTest()
```
Creating the workflow template locally:

```bash
 METAFLOW_KUBERNETES_NAMESPACE=argo-production METAFLOW_DATASTORE_SYSROOT_S3=s3://my-bucket/metaflow/ python metaflow_test.py --datastore=s3 argo-workflows create
```

Triggering the workflow locally:
```bash
 METAFLOW_KUBERNETES_NAMESPACE=argo-production python metaflow_test.py argo-workflows trigger
```

Logs from workflow pod:

```
mkdir: cannot create directory ‘//.logs’: Permission denied
/bin/bash: line 1: [: -le: unary operator expected
/bin/bash: line 1: [: -gt: unary operator expected
tar: job.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
/usr/local/bin/python: Error while finding module specification for 'metaflow.mflog.save_logs' (ModuleNotFoundError: No module named 'metaflow')
time="2022-10-26T18:09:35.920Z" level=info msg="sub-process exited" argo=true error="<nil>"
time="2022-10-26T18:09:35.920Z" level=info msg="no need to save parameter - on overlapping volume: /mnt/out/task_id" argo=true
Error: exit status 2
```

These errors tell me that my workflow pod security context is working as expected, but I'm not sure how to use a nonroot security context with metaflow, as the user seems to need escalated privileges to run the init script. 

Some questions:

1. Is there a prebuilt metaflow image that contains all of the necessary requirements (awscli, metaflow, etc), so that these dependencies will be preinstalled, rather than requiring the permissions to install them in the default python image at runtime?
2. Is there an environment variable that I can set that will determine the working directory where the `.logs` folder will be created, rather than attempting to create it in the base directory of the container? Is this what `METAFLOW_ARTIFACT_LOCALROOT` is for?
4. Is there a better way to reconcile my pod security context configuration with how metaflow creates workflows that I'm just not seeing?

**Comment by dbragdon1** [comment]
Thanks for your reply. I think a custom docker image seems like the best approach in this setting. Are you setting the working dir to `/tmp` inside of your metaflow script, or by some other means (metaflow environment variables, Dockerfile, etc.). I'll also join the slack and take a look around. Thanks again for your help.

**Comment by savingoyal** [comment]
Conversation resolved at [this thread](https://outerbounds-community.slack.com/archives/C02116BBNTU/p1666899877897229) (accessible via chat.metaflow.org)
