### ISSUE TITLE
provide an alternative env variable $METAFLOW_USERNAME which overrides $USERNAME if set

### ISSUE THREAD

**Issue by dasturge** [Netflix/metaflow#1178]
Our organization has our Linux usernames set to our email addresses.  However, the @ character is illegal in Argo, so it causes a failure with the default Unix username.  I'd rather not have to change the system USERNAME in case it causes unexpected behavior in other programs expecting it to align with my Linux username.  It would be nicer if I could set one explicitly for use in metaflow.

**Comment by romain-intel** [comment]
You should be able to set `METAFLOW_USER`. Metaflow gets the username by looking, in order, at: `METAFLOW_USER`, `SUDO_USER`, `USERNAME` and `USER`.

Let me know if that solves it for you.

**Comment by dasturge** [comment]
https://github.com/Netflix/metaflow-docs/pull/79

I added your comment in the docs where it discusses project workflows, that's where I was trying to find documentation on it.
