### ISSUE TITLE
Please add custom Docker support to Documentation

### ISSUE THREAD

**Issue by jvnte** [Netflix/metaflow#1196]
My team just stumbled across the following blogpost (https://outerbounds.com/docs/build-custom-image/) on how to enable execution of Metaflow steps using custom docker images. 

This basically enables much more flexibilty in terms of environment management - such as having to rely on conda environments only. 

Could you please add this to the overall Metaflow documentation?

**Comment by madhur-ob** [comment]
@savingoyal the section about containers already has a link to the above resource here: https://docs.metaflow.org/scaling/dependencies/containers#building-a-custom-image

Do we want to copy the contents over? Otherwise, we can kinda close this issue...
Let me know what you prefer...
