### ISSUE TITLE
Where can I find the METAFLOW_SERVICE_URL on AWS Console?

### ISSUE THREAD

**Issue by Viveckh** [Netflix/metaflow#121]
Following the instructions in the website to [Create Metaflow Service](https://docs.metaflow.org/metaflow-on-aws/deploy-to-aws#create-metaflow-service) on AWS.

Where can I find the METAFLOW_SERVICE_URL? I created the RDS and the necessary ECS cluster along with the task definition and service, but I cannot see anything that looks like a URL.

Looking at the [cloud formation template provided in the repo](https://github.com/Netflix/metaflow-tools/blob/master/aws/cloudformation/metaflow-cfn-template.yml), it looks like there is something that needs to be set up in API Gateway, but that isn't shown in the instructions.

<img width="675" alt="Screen Shot 2020-02-11 at 2 54 59 PM" src="https://user-images.githubusercontent.com/9113166/74273671-d64c5980-4cde-11ea-9a68-f3925e204aed.png">
<img width="449" alt="Screen Shot 2020-02-11 at 2 55 28 PM" src="https://user-images.githubusercontent.com/9113166/74273676-d9474a00-4cde-11ea-8291-01d262f053b1.png">

**Comment by savingoyal** [comment]
@Viveckh You can get the public IP from the `Task` page accessible within the `Service` page for your service in the Amazon ECS console. The service should be accessible on port 8080.

@ferras Can we update the docs?

**Comment by Viveckh** [comment]
Thanks Savin. So I can see the Public IP but I noticed something strange.
There are dozens of tasks in the STOPPED state (Even though I have not kicked off any real tasks yet)
And I can see a new task being attempting to provision and stopping every minute, and ending up with new Public IPs every minute. What can be the cause for this?

![Screen Shot 2020-02-11 at 4 38 06 PM](https://user-images.githubusercontent.com/9113166/74281922-45c94580-4ced-11ea-9ccf-8a3df72f18d1.png)

**Comment by ferras** [comment]
@Viveckh can you verify your RDS instance is up and accessible. Depending on your exact setup they may need to be on the same vpc or you maybe missing some security group

**Comment by Viveckh** [comment]
Hmm I verified the RDS is up, and also tried pointing the service to the same security group as the RDS. Does the container need to use the `netflixoss/metaflow_metadata_service` docker image by any chance? The documentation on the site doesn't mention it, but I can see it in the [git repo](https://github.com/Netflix/metaflow-service).

**Comment by Viveckh** [comment]
I was able to resolve the errors using the Postgres Database for RDS. I was earlier under the impression any DB system in AmazonRDS is fair game since it wasn't specifically mentioned anywhere that the current support is only for Postgres.

I would recommend updating the documentation at the ECS Task Definition step so it mentions that `netflixoss/metaflow_metadata_service` should be plugged in for the image. Currently, one has to either dig into the cloud formation template or metaflow_service's git repo to find that information.

Thanks for the help guys.
