### ISSUE TITLE
Add support for custom tags at run time

### ISSUE THREAD

**Issue by dhpollack** [Netflix/metaflow#1222]
It would be nice one could add custom tags via a flow/step decorator or environmental variables.  Currently the tagging system seems optimized for post-run tagging, but often times one wants to tag a specific run in order to find that run later.  I would propose either a decorator on the flow or environmental variables.

```
# within flow decorator or on a step
@project(name="my_project", tags=("tag1", "tag2:tag2value" , "tag3"))
class MyFlow(FlowSpec):
  @tags(("start_tag1", "start_tag2:start_tag2_value"))
  def start(self):
    ...

# with an env var
export METAFLOW_USER_TAGS="tag1|tag2:tag2value|tag3"
export METAFLOW_USER_TAGS_DELIMITER="|"
```

**Comment by savingoyal** [comment]
you can already do this - `METAFLOW_RUN_TAGS='mytag another_tag' python helloflow.py run` to attach `mytag` and `another_tag` to the execution. This is semantically equivalent to `python helloflow.py run --tag mytag --tag another_tag`. Would this help?

**Comment by dhpollack** [comment]
The `METAFLOW_RUN_TAGS` is exactly what I was looking for.  This seems like an undocumented feature.  My only complaint now is that it should be in the docs.  :smile:   Thanks for pointing this out!

**Comment by dhpollack** [comment]
I'll close this for now.
