### ISSUE TITLE
Metaflow python client doesn't list scheduled runs from argo-workflows 

### ISSUE THREAD

**Issue by shrinandj** [Netflix/metaflow#1223]
Steps to reproduce:

- Create a flow with `@schedule` decorator
- Create an argo workflow using
- Verify that the flow runs periodically as per the schedule
- List the runs using the Metaflow python client. Something like:

```
from metaflow import Metaflow, Flow
for flow in Metaflow().flows:
    for run in flow:
        print(run.id)
```

In the last step above, the argo-workflow runs from the scheduled flows DO NOT get listed. The runs do show up on the Metaflow UI.
![Screenshot 2023-01-05 at 10 33 16 AM](https://user-images.githubusercontent.com/3084759/210854911-1bcdd3a1-9d13-41f0-b4c0-26302b51152d.png)

**Comment by savingoyal** [comment]
You would need to set `namespace(None)` to switch the client to the global namespace. By default, the client uses the user's local namespace and the scheduled workflows on Argo run in a different namespace.

**Comment by shrinandj** [comment]
Cool.. thanks!

Updated code here for posterity:

```
#!/usr/bin/env python3

import metaflow
from metaflow import Metaflow, Flow

metaflow.namespace(None)
for flow in Metaflow().flows:
    for run in flow:
        print(run.id)
```
