### ISSUE TITLE
Error in Tutorial 4 (04-playlist-plus) caused by incompatibility with latest pandas version.

### ISSUE THREAD

**Issue by eracle** [Netflix/metaflow#1241]
Error message:
`AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from ...`
 

I was following the tutorial for the metaflow project and encountered an error in Tutorial 4. The issue is caused by a compatibility issue between the pinned version of pandas used in Tutorial 4 and the latest pandas.

Specifically, the code in Tutorial 4 attempts to pickle the output from Tutorial 3 but raises an error due to incompatibility. This is preventing me from progressing in the tutorial and I cannot continue.

A solution is to update the pinned version of pandas to the latest version:
```

@conda_base(libraries={'pandas': "1.5.3"})
class PlayListFlow(FlowSpec):

```

**Comment by savingoyal** [comment]
#1299 addresses this issue.
