### ISSUE TITLE
Deploying on AWS : Documentation Update Suggestions

### ISSUE THREAD

**Issue by Viveckh** [Netflix/metaflow#125]
I noticed the [Deploying to AWS](https://docs.metaflow.org/metaflow-on-aws/deploy-to-aws) Documentation doesn't mention this, but the following need to be in the metaflowconfig as well, otherwise, the local datastore and metastore are used by default.

 `METADATA_DEFAULT_METADATA: service`
 `METADATA_DEFAULT_DATASTORE: s3`

**Comment by savingoyal** [comment]
When you type `metaflow configure aws`, it automatically sets `METADATA_DEFAULT_METADATA : service` and `METADATA_DEFAULT_DATASTORE : s3` in the metaflowconfig.

**Comment by Viveckh** [comment]
Totally my bad, I noticed it after I put in the issue.
