### ISSUE TITLE
Allow image pull policy to be set with kubernetes.

### ISSUE THREAD

**Issue by dhpollack** [Netflix/metaflow#1265]
We using custom images in kubernetes and during development these get rebuilt on every commit.  Unfortunately, the default imagePullPolicy with metaflow is "ifNotPresent".  During development, it would be nice to be able to change this to "Always".  

It can be pretty easily doing be adding `image_pull_policy=kwargs.get("image_pull_policy", None)` to line 147 in the `kubernetes_job.py` file and then adding it to the decorator.  I have been editing my local metaflow install manually with this hack, but it would be nice if it were adjustable in metaflow.

**Comment by shrinandj** [comment]
We should fix this the correct way making it configurable and allowing the user to specify the policy. Meanwhile, during development, can you set the image tag to `latest` and run the flow? For images tagged `latest`, Kubernetes would ignore the imagePullPolicy and use `Always` [1].

[1] https://www.containiq.com/post/kubernetes-image-pull-policy

**Comment by colebaileygit** [comment]
We tend to use git branches as tags, so switching to `latest` would introduce other issues for us. Another workaround is to use explicitly tagged images but sometimes branch images used for development are quite convenient

**Comment by shrinandj** [comment]
Makes sense. Feel free to send out a PR. We can review it test it and get it in and do a release. There might also be some changes required in `metaflow/plugins/argo/argo_workflows.py` to support the pull policy in Argo.

**Comment by rparundekar** [comment]
@shrinandj,  Is it safe to assume that even if this was set as default, docker still caches the layers, so there wouldn't be overhead for most layers (except the extra network call it makes to check the latest hash of the layer).

**Comment by shrinandj** [comment]
The [documentation](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy) for imagePullPolicy shows that kubelet does some heavy lifting if the policy is set to `Always`. kubelet will try to fetch the digest from the registry, compare it with what it has and issue a docker pull if it doesn't match.

If the `docker pull` is issued, docker will use the cached layers. So, it will only pull the latest layers that have changed. This will require writing the Dockerfile a bit carefully though.

**Comment by dhpollack** [comment]
feature merged to master
