### ISSUE TITLE
Print UI URL for `step-functions trigger` and `argo-workflows trigger`

### ISSUE THREAD

**Issue by jackie-ob** [Netflix/metaflow#1292]
Can we file an issue for a follow up PR that prints the UI URL for `step-functions trigger` and `argo-workflows trigger`?

_Originally posted by @savingoyal in https://github.com/Netflix/metaflow/issues/1290#issuecomment-1456677430_

**Comment by Blueclaus13** [comment]
I would like to contribute on this issue, is it available?

**Comment by jackie-ob** [comment]
That would be great.  I would recommend waiting for the parent PR to close first (#1290)

**Comment by Blueclaus13** [comment]
Thank you, also I'm new to resolving issues. I have set up the repository, if I have questions to make should I post them here?

**Comment by bsridatta** [comment]
guess this is closed?
