### ISSUE TITLE
Install in Google Colab?

### ISSUE THREAD

**Issue by leocaldeira** [Netflix/metaflow#13]
I got some errors... What i miss?
![image](https://user-images.githubusercontent.com/39734786/70137954-f53ec780-166d-11ea-984c-f8fb607178c8.png)

**Comment by casey-barr** [comment]
@leocaldeira 

Use a ! before your pip command.

i.e. - !pip install metaflow

**Comment by leocaldeira** [comment]
@casey-barr , the error persists.
![image](https://user-images.githubusercontent.com/39734786/70158561-377bff00-1696-11ea-817f-626300995a47.png)

![image](https://user-images.githubusercontent.com/39734786/70158610-4b276580-1696-11ea-914f-a285abc25c22.png)

**Comment by seeravikiran** [comment]
`metaflow` is a binary auto generated by setup tools. You can either do: `os.system` or `subprocess` module and launch `which metaflow`. You can run the remaining commands in a similar fashion.
And let us know if the issue persists.

**Comment by leocaldeira** [comment]
I tested it in other ways and got the same feedback...
@seeravikiran or @casey-barr can u send me a example?

![image](https://user-images.githubusercontent.com/39734786/70229699-76ad5d00-1735-11ea-9a93-2789f46164ea.png)

**Comment by leocaldeira** [comment]
![image](https://user-images.githubusercontent.com/39734786/70230561-5d0d1500-1737-11ea-8adc-c6c6a60fa544.png)

**Comment by romain-intel** [comment]
Hello @leocaldeira, I tried it on colab.research.google.com and it works if you do the following:
```
import os
os.environ['USERNAME'] = 'leo'
!pip install metaflow
!metaflow tutorials pull
!python metaflow-tutorials/00-helloworld/helloworld.py run
```

You can then use the client directly like so:
```
from metaflow import Flow
f = Flow('HelloFlow').latest_successful_run
...
```

Let me know if this helps.

**Comment by leocaldeira** [comment]
Using ! in front of metaflow worked perfectly.
tyvm :)
