### ISSUE TITLE
No way to change S3 endpoint_url

### ISSUE THREAD

**Issue by ifokeev** [Netflix/metaflow#130]
I'm using `minio` as my S3 file storage. There is no way to change default `S3` `endpoint_url` in `metaflow` boto3 client
https://github.com/Netflix/metaflow/blob/c2f70c73782549fdce6c418410ecd9b305199b28/metaflow/metaflow_config.py#L194

I can provide PR if it will be merged fast.

**Comment by tuulos** [comment]
@ifokeev good point. We could expose `endpoint_url` as a config variable.

**Comment by ifokeev** [comment]
@tuulos merge, please

**Comment by Mendes11** [comment]
I'm in need for this feature as well, we use localstack to simulate S3 and to test Metaflow in our calculation services architecture we need this endpoint_url configuration...

**Comment by ifokeev** [comment]
@tuulos merge, please

**Comment by savingoyal** [comment]
@ifokeev @Mendes11 As of `V2.0.3`, this feature is now [available](https://docs.metaflow.org/metaflow-on-aws/deploy-to-aws#metaflow_s-3-_endpoint_url-optional).

**Comment by ifokeev** [comment]
@savingoyal how is this part of `V2.0.3` if the `master` and branch https://github.com/Netflix/metaflow/blob/release-2.0.3/metaflow/metaflow_config.py#L197 doesn't contain any code?

**Comment by savingoyal** [comment]
uh, @romain-intel looks like #132 was never merged even though the release notes mention that they were [part of the release train](https://docs.metaflow.org/introduction/release-notes#ability-to-specify-s3-endpoint).

**Comment by romain-intel** [comment]
I will merge it for the next release. Apologies for having missed it.

**Comment by repocho** [comment]
I have added [this comment to the PR](https://github.com/Netflix/metaflow/pull/132#issuecomment-597755901). I need also the `verify` attribute of boto3, for self-signed certificates.

Let me know how can I add that. If we can do it in the same PR or it is better to create a new PR.

Thank ;-)
