### ISSUE TITLE
introduce `terminate` and `disable` commands for `argo-workflows`

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#1303]

**Comment by savingoyal** [comment]
while at it, maybe do delete as well

**Comment by saikonen** [comment]
the `disable` feature will require some further thought around the UX, as it opens up a lot of questions on the desired behavior. A non-exhaustive list of open questions

- with the upcoming Sensors for workflows, what does it mean to `disable` a workflow?
- should a workflow that is disabled still be able to be triggered manually? can we even prevent this without deleting the workflow?
- should we have a symmetric command to re-enable a workflow? having to rely on `create` can be a bit confusing
- wording of the command in case of offering an enable as well is up for debate. Some ideas include separate `enable/disable` commands, or affecting the status with a flag

**Comment by talebzeghmi** [comment]
It would be great to also have this feature in the Metaflow UI!
However the Metaflow UI is only cognizant of the running Flow once the Argo step has started...

**Comment by saikonen** [comment]
`disable` was superseded by `suspend/unsuspend`. These are now available since https://github.com/Netflix/metaflow/releases/tag/2.9.7
