### ISSUE TITLE
Construct a dag with triangle 

### ISSUE THREAD

**Issue by tanzeyy** [Netflix/metaflow#1305]
![image](https://user-images.githubusercontent.com/25984272/225303092-1c869e1e-bf4c-4ff9-86c3-6d29ae49b036.png)

I would like to know that is it possible to construct dag like the one in the figure? I had tried the following code but got some error:
```python

class BranchFlow(FlowSpec):
    @step
    def start(self):
        self.next(self.a, self.c)

    @step
    def a(self):
        self.x = 1
        print("A")
        self.next(self.b)

    @step
    def c(self):
        print("C")
        self.next(self.b, self.d)

    @step
    def b(self, inputs):
        self.next(self.d)

    @step
    def d(self, inputs):
        self.next(self.end)

    @step
    def end(self):
        print("END")
        pass


if __name__ == '__main__':
    BranchFlow()
```

![image](https://user-images.githubusercontent.com/25984272/225303568-a156d103-ec0b-4c52-8db6-e4864c8943b2.png)

**Comment by LennieGuy** [comment]
I also encountered this problem. It seems that metaflow does not allow a branch to have multiple child nodes @jfernandez

**Comment by savingoyal** [comment]
@tanzeyy @LennieGuy is there a reason to have an edge between `C` and `D`. If there was no edge between them then it would be a valid DAG for Metaflow - `D` would only execute after `C` and you would have access to any intermediate data generated by `C` in `D`.

**Comment by LennieGuy** [comment]
If we need such dependencies, how do we construct the code

**Comment by LennieGuy** [comment]
@savingoyal

**Comment by tanzeyy** [comment]
> @tanzeyy @LennieGuy is there a reason to have an edge between `C` and `D`. If there was no edge between them then it would be a valid DAG for Metaflow - `D` would only execute after `C` and you would have access to any intermediate data generated by `C` in `D`.

Thanks for your reply. The dag shown in the figure is only a demo of our target workflow, actually there are several steps between `C` and `D` and we would like them to be executed immediately after `C` is finished.

**Comment by LennieGuy** [comment]
At the same time, we have more complex dags to construct, but it seems that metaflow is a little inadequate
![20230316-104928](https://user-images.githubusercontent.com/65661801/225497705-38194686-385b-41b8-9b9d-b92a278b3a4d.jpg)

**Comment by savingoyal** [comment]
![IMG_1008](https://user-images.githubusercontent.com/763451/225679303-5fc99980-bab0-4d3b-8bf3-edfc00cbd601.jpg)

You can create such a DAG perfectly fine. Every step has access to all the information from all its ancestors.

**Comment by tanzeyy** [comment]
> ![IMG_1008](https://user-images.githubusercontent.com/763451/225679303-5fc99980-bab0-4d3b-8bf3-edfc00cbd601.jpg)
> 
> You can create such a DAG perfectly fine. Every step has access to all the information from all its ancestors.

But the absence of the edge between `C` and `D` makes the sequential dependency infeasible, and we wouldn't want `D` to execute before `C` is finished.

**Comment by savingoyal** [comment]
![IMG_1013](https://user-images.githubusercontent.com/763451/226694897-24b7218d-0e24-46c1-b382-a5f18ade90de.jpg)

This structure would work then.

**Comment by savingoyal** [comment]
Please reopen the issue if you would like to discuss further or ping me in chat.metaflow.org if that's quicker.
