### ISSUE TITLE
Metaflow cards should ignore unsupported types inside Dataframe

### ISSUE THREAD

**Issue by valayDave** [Netflix/metaflow#1319]
Metaflow cards creation fails with an error when a `pandas.DataFrame` contains types that are not JSON parsable. This can be fixed by identifying supportable types and adding `UnsupportedType : <TYPENAME>` in column values.

**Comment by jimbudarz** [comment]
I ran into the same issue myself recently. I would be willing to try implementing this if the community and maintainers agree that this would be a good solution. 

I believe this would need to change in the `_parse_pandas_dataframe` function in `metaflow/plugins/cards/card_modules/convert_to_native_type.py`, where it loops over all columns to convert them to string datetimes. Leveraging this loop, we could convert non-JSON serializable columns to strings which state that the data type is not viewable.
