### ISSUE TITLE
Drop support for older versions of python

### ISSUE THREAD

**Issue by dhpollack** [Netflix/metaflow#1342]
https://devguide.python.org/versions/

Python 3.5 and 3.6 have been at end of life for a long time (and python 3.7 will soon be end of life).  Particularly python 3.5 has some basic features missing that your test suite doesn't seem to pick up.  The most obvious are f-strings and inline type hints.  You can see examples of f-strings in the code already (`metaflow/vendor.py` for example).

https://github.com/Netflix/metaflow/blob/master/metaflow/vendor.py#L81

I understand you might have a lot of users of python 3.5 but it's time.

**Comment by savingoyal** [comment]
@dhpollack - `vendor.py` is not in the user code execution path; it is only used to ensure that we have correctly vendored packages in Metaflow. 

Our position is that existing functionality should continue working with older versions of Python, and net new features rely on newer versions.
