### ISSUE TITLE
Correct Way to comunicate flow with server

### ISSUE THREAD

**Issue by ideivitcom** [Netflix/metaflow#136]
Hi.
Imagine a Flask server. I get a petition, and i need start a flow with the request information. 
All the examples show:
if __name__ .. .
And i need start with python script.py run .
By the moment i using subprocess comunication to start the flow, but... What is the correct solution for this? Can i implement a flow with a rabbitmq? How can i decouple the flow for the parameters? 

Best regards.

**Comment by romain-intel** [comment]
I believe this is a duplicate of #117. Please confirm and I will clsoe this issue.

**Comment by ideivitcom** [comment]
Yes is the same. Thanks.
