### ISSUE TITLE
Incompatible GPL-licensed dependency `pylint`

### ISSUE THREAD

**Issue by zhcxww** [Netflix/metaflow#1377]
Hello, 

We are a group of researchers developing tools to monitor and remediate open-source license incompatibilities in the PyPI ecosystem.

We find that your `metaflow` package has a **GPL-v2-or-later** licensed dependency `pylint`. This could be problematic because GPL-licensed software requires any of its derivative work to be also licensed under GPL, but `metaflow` is licensed under Apache 2.0. 

To remove this license incompatibility, the following possible remediations can be considered:

* Relicense `metaflow` under GPL 3.0
* Migrate `pylint` to `flake8`
* Remove `pylint`

Note that the above remediations are generated by an automated tool that is still under test, may be incorrect, and does not represent legal advice. We welcome any suggestions and feedback!

**Comment by savingoyal** [comment]
#1378 fixes this issue
