### ISSUE TITLE
Latest releases add additional double quotes to string parameters in argo workflows

### ISSUE THREAD

**Issue by ShantanuKumar** [Netflix/metaflow#1453]
Whenever I push a job to argo-workflows all parameters of `type=str` are saved as with additional double quotes in argo workflows.

For example:
```python
domain = Parameter("string_parameter", default="my_string_parameter")
```

When the flow is executed on argo-workflows the class variable will be shown as
```python
self.string_parameter = '"my_string_parameter"`
```

I have seen this happening from at least 2.9.1
Reported on outerbounds [slack](https://outerbounds-community.slack.com/archives/C02116BBNTU/p1685090276647929)

**Comment by saikonen** [comment]
From what I tested, this should now be fixed for Argo Workflows in the latest release https://github.com/Netflix/metaflow/releases/tag/2.9.5
