### ISSUE TITLE
Error when creating Flows as StepFunction 

### ISSUE THREAD

**Issue by doublethink13** [Netflix/metaflow#1472]
I'm having this error when following the docs ([https://docs.metaflow.org/production/scheduling-metaflow-flows/scheduling-with-aws-step-functions#pushing-a-flow-to-production](https://docs.metaflow.org/production/scheduling-metaflow-flows/scheduling-with-aws-step-functions#pushing-a-flow-to-production)):

```text
Invalid type for parameter containerProperties.jobRoleArn, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

What could possible be the cause?

**Comment by savingoyal** [comment]
@doublethink13 are you on a rather old version of boto3? we have seen this error pop up in those scenarios.

**Comment by doublethink13** [comment]
I have:

```txt
boto3==1.27.0
botocore==1.30.0
```
