### ISSUE TITLE
Error with bootstrapping environment: TypeError: rename: src should be string, bytes or os.PathLike, not NoneType

### ISSUE THREAD

**Issue by Sypek** [Netflix/metaflow#1477]
Hi,

I'm getting the following error while deploying my flow: `TypeError: rename: src should be string, bytes or os.PathLike, not NoneType` (stack trace below).

Description:
I have a flow that is created and deployed on AWS Step Functions. Code is triggered daily with scheduler (rule in AWS EventBridge). On most of the days, the whole flow ends up with a success. But on irregular basis, flow crashes at the first step while bootstrapping the environment. From this moment, every flow triggered on the next days fails as well.

I try to understand what can cause such error, especially the fact that I get it on irregular basis. Thanks in advance for any help.

Technical details:

In `~/.metaflowconfig/config.json` I have set `mamba` as dependency resolver:
`"METAFLOW_CONDA_DEPENDENCY_RESOLVER": "mamba"`

Metaflow version: 2.9.2
Python version: 3.10.4

```
Setting up task environment.
--
Downloading code package...
Code package downloaded.
Task is starting.
Bootstrapping environment...
Traceback (most recent call last):
File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/metaflow/metaflow/plugins/conda/batch_bootstrap.py", line 104, in <module>
bootstrap_environment(sys.argv[1], sys.argv[2], sys.argv[3])
File "/metaflow/metaflow/plugins/conda/batch_bootstrap.py", line 16, in bootstrap_environment
packages = download_conda_packages(flow_name, env_id, datastore_type)
File "/metaflow/metaflow/plugins/conda/batch_bootstrap.py", line 75, in download_conda_packages
shutil.move(
File "/usr/local/lib/python3.10/shutil.py", line 816, in move
os.rename(src, real_dst)
TypeError: rename: src should be string, bytes or os.PathLike, not NoneType
```

**Comment by DonIvanCorleone** [comment]
Same holds true for an on-prem kubernetes instance with 

Metaflow : 2.9.8
Environment: Conda
Python 3.10.10

**Comment by saikonen** [comment]
Thank you for the deep dive to the issue, it sped up testing the issue quite a bit :)
I implemented the fix as proposed as it is quite a straightforward fix. Also took the time to comb through the code for any other outliers so the `ServerSideEncryption` feature shouldn't cause any further issues.

**Comment by DonIvanCorleone** [comment]
Glad it helped. And thank you for your super fast support here. 👍

**Comment by Sypek** [comment]
@DonIvanCorleone, @saikonen thanks for your effort.
Although, I've already pulled metaflow version `2.9.9` and I'm getting the same error again :( 

Do you have any more ideas, what can cause that error?

**Comment by Ashton-Sidhu** [comment]
Getting the same error in 2.10.7 with the `pypi` datastore as well
