### ISSUE TITLE
Artifact not currently displayable in the UI, use the client to access it.

### ISSUE THREAD

**Issue by sangwoo-joh** [Netflix/metaflow#1493]
I'm currently using metaflow with local development settings.
I set up metaflow-service and metaflow-ui from [this document](https://github.com/Netflix/metaflow-ui/blob/master/docs/README.md#running-metaflow-metaflow-service-and-metaflow-ui-locally).
After I ran my metaflow flows, the ui shows all flows and other things except for the artifact with the following message:
> Artifact not currently displayable in the UI, use the client to access it.

What should I do to get artifact displayed in the ui with local development settings?

**Comment by savingoyal** [comment]
@sangwoo-joh can you help me with a screenshot of where are you seeing this message?
