### ISSUE TITLE
mf_env-creation.lock

### ISSUE THREAD

**Issue by JanPalasek** [Netflix/metaflow#1495]
As far as I understand, this file is created before some interactions with conda, like:

- Installation of the environment.
- Removal of the environment.

However if the process ends abruptly (user pressing Ctrl + C more times), this file can be left out and permanently prohibit users from creating any conda environment again. And since most users don't know about existence of this file, they might stop using Metaflow.

- Is it possible to somehow get rid of the file? This might also help multi-user settings, where more users develop on one virtual server.
- If not, can you mention this problem in the documentation? Or is it already mentioned and I missed it? :-(

**Comment by savingoyal** [comment]
@JanPalasek we are working on a revamp of `@conda` decorator that will get rid of this limitation

**Comment by romain-intel** [comment]
If you are in a rush, this drop-in replacement of conda: https://github.com/Netflix/metaflow-nflx-extensions/ will also get rid of this (or at least greatly improve it). In particular, if it can't get a lock, it prints out a message informing the user of the problem and allowing the user to rectify (it also does a better job with cleanup but it's hard to catch *all* cases :) ). As @savingoyal said though, an "official" version will also come out.

**Comment by savingoyal** [comment]
#1505 will address this

**Comment by savingoyal** [comment]
removed in #1505
