### ISSUE TITLE
Flow fails on "from google.cloud import bigquery" in a dependency file

### ISSUE THREAD

**Issue by chelseatroy** [Netflix/metaflow#1561]
I have the following, minimal flow. The content of the flow is not important: I started from scratch to pinpoint exactly what was wrong with my flow. 

```
from metaflow import FlowSpec, step

class LinearFlow(FlowSpec):

    @step
    def start(self):
        self.my_var = 'hello world'
        self.next(self.retrieve_metrics)

    @step
    def retrieve_metrics(self):
        print('the data artifact is: %s' % self.my_var)
        self.next(self.record_results)

    @step
    def record_results(self):
        print('the data artifact is: %s' % self.my_var)
        self.next(self.end)

    @step
    def end(self):
        print('the data artifact is still: %s' % self.my_var)

if __name__ == '__main__':
    LinearFlow()
```
When I run the flow like _this_, it succeeds. 

For my _actual_ flow, I need to import some functions, `retrieve_data_validation_metrics` and `record_validation_results`, from another file. 

So I add this to the top of the flow file:

`from data_validation import retrieve_data_validation_metrics, record_validation_results`

Once I do that, my flow fails:

```
Metaflow 2.9.15 executing LinearFlow for user:chelseatroy
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
2023-09-29 15:26:06.632 Workflow starting (run-id 1696019166623313):
2023-09-29 15:26:06.639 [1696019166623313/start/1 (pid 34061)] Task is starting.
2023-09-29 15:26:07.852 [1696019166623313/start/1 (pid 34061)] Task failed with a segmentation fault.
2023-09-29 15:26:07.853 Workflow failed.
2023-09-29 15:26:07.854 Terminating 0 active tasks...
2023-09-29 15:26:07.854 Flushing logs...
    Step failure:
    Step start (task-id 1) failed.

Segmentation fault: 11
```

Note that I am not yet _calling_ either of the functions I just imported.

The top of the `data_validation.py` file that I imported the functions from includes _this_ line:

`from google.cloud import bigquery`

When I move that line from the top of the file down into the function that needs bigquery, my flow _works_!

However, when I edit the flow to now _call_ one of the functions that uses bigquery (and therefore has that import in it)—for example if I call `retrieve_data_validation_metrics` in the `retrieve_metrics` step function, Metaflow again fails, this time at the `retrieve_metrics` step, again with a segfault.

What's clear to me from running these experiments is that the flow in metaflow fails when it hits the line to import bigquery from google.cloud.

I have a plain python script that does the same set of steps I'm trying to move into metaflow, and that script looks like this:

```
import argparse
import pandas as pd

from datetime import date, timedelta
from collections import namedtuple

from data_validation import retrieve_data_validation_metrics, record_validation_results

print("Dependencies successfully imported!")

parser = argparse.ArgumentParser(
    description="Validate Recent Search Input Against Historical Norms",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
)
parser.add_argument(
    "--data_validation_origin", help="Origin table for data validation metrics"
)
parser.add_argument(
    "--data_validation_reporting_destination",
    help="Table to store data validation metric test results",
)
print("Parser successfully instantiated!")

args = parser.parse_args()
print("Args successfully parsed!")
print(f"Data Validation Origin: {args.data_validation_origin}")
print(f"Data Validation Reporting Destination: {args.data_validation_reporting_destination}")

print("Retrieving Data Validation Metrics Now...")
validation_df = retrieve_data_validation_metrics(args.data_validation_origin)
print(f"Input Dataframe Shape: {validation_df.shape}")

print("Recording validation results...")
record_validation_results(validation_df, args.data_validation_reporting_destination)
```

This imports the same functions I'm trying to import in my flow. When I run this file, which lives in the same directory and environment as the flow file, this works as expected.

**The question: any tricks I should know to run a Metaflow flow that calls functions that use `google.cloud`'s `bigquery`?**

Thank you!

**Comment by savingoyal** [comment]
it seems this was fixed by updating to a more recent version of `google.cloud`
