### ISSUE TITLE
cannot use AWS multiple profiles

### ISSUE THREAD

**Issue by BeeShall** [Netflix/metaflow#158]
The current solution always selects the `[default]` aws profile. If you have multiple aws profiles, you'll literally have to go into `~/.aws/credentials` and rename the profile you want to use to `default`. Other wise you keep getting `Unable to locate credentials` error.

**Comment by savingoyal** [comment]
If you are using named `aws credentials`, you can always export the profile you want to use - `export AWS_PROFILE=blah` or `AWS_PROFILE=blah python myflow.py run`. This is completely independent of metaflow.

**Comment by BeeShall** [comment]
My bad. Long day with corporate AWS environment.
