### ISSUE TITLE
Add tags to run retrospectively

### ISSUE THREAD

**Issue by Niggl0n** [Netflix/metaflow#159]
Currently there is no functionality provided to add tags to runs in retrospect. 
Adding that would help organising runs and results, for example while inspecting via jupyter notebook.

**Comment by MusHusKat** [comment]
Hi friends, just wanted to check what's the priority for this issue. We are increasingly feeling the need for this to organize our historic flows to conform to ever-evolving patterns. Thank you.

**Comment by savingoyal** [comment]
@MusHusKat This is actively being worked upon as of last week. We should be able to conclude this work over the next few weeks.

**Comment by MusHusKat** [comment]
Thanks @savingoyal , that's excellent news. Looking forward to this new feature. Best of luck!

**Comment by savingoyal** [comment]
This functionality is now available - https://outerbounds.com/blog/five-ways-to-use-the-new-metaflow-tags
