### ISSUE TITLE
Implement step function terminate

### ISSUE THREAD

**Issue by martinbattentive** [Netflix/metaflow#1594]
I was looking for a way to stop a running step function and ran across this TODO in metaflow/plugins/aws/step_functions/step_functions_client.py:

```
def terminate_execution(self, state_machine_arn, execution_arn):
    # TODO
    pass
```

Any chance of this getting implemented in the near future?

**Comment by mikesteroonie** [comment]
I tried implementing this in pr #1596. Are you running into loop behavior as of now? Or do you need to shut down the instance to stop the step function?

**Comment by madhur-ob** [comment]
Done by https://github.com/Netflix/metaflow/pull/1695
