### ISSUE TITLE
Integration with DVC

### ISSUE THREAD

**Issue by hammacktony** [Netflix/metaflow#161]
I am curious if there is a way to integrate Metaflow and DVC. I can see both working in tandem.

**Comment by tuulos** [comment]
@hammacktony yep! DVC and Metaflow are quite complementary tools.

One way to use DVC with Metaflow is to store immutable pointers to DVC data as Metaflow artfiacts. See related discussions here https://gitter.im/metaflow_org/community?at=5e612c9a90a829582408e7c1

It would be great to publish an example how to use DVC with Metaflow #todo
