### ISSUE TITLE
link two flows

### ISSUE THREAD

**Issue by themantalope** [Netflix/metaflow#162]
Not sure if I just haven't found the right verbage in the documentations, or if there are other built in ways to do this but I want to be able to prospectively link two flows together. For example, let's say there is `FlowA` and `FlowB`, and `FlowA` for example pre-processes data that gets utilized in `FlowB`. Is there a way I can make sure that I know which data from `FlowA` was utilized by a certain run in `FlowB`? One way I guess would be to tag both flows with the same tag or unique ID, does anyone know how to programmatically tag a flow within itself? Should I just combine the two flows into one?

Thanks

**Comment by savingoyal** [comment]
@themantalope [Tagging](https://docs.metaflow.org/metaflow/tagging#tagging) is definitely one approach. How are you currently accessing data from `FlowA` in your `FlowB`? You could simply store the relevant `run id` for `FlowA` in `FlowB` and access it using the Client API.

We have #159 open which will provide programmatic capabilities for tagging a flow retrospectively.

**Comment by themantalope** [comment]
I see, so in the first step of `FlowB` I could do something link

```python
from metaflow import FlowSpec, Flow

class FlowB(FlowSpec):
    @step    
    def start(self):
         self.last_flow_a_run_id = Flow('FlowA').latest_run.run_id
    // rest of code etc.

```

And when the data from the `FlowB` is stored, the data in `last_flow_a_run_id` will get saved to disk, correct?

**Comment by savingoyal** [comment]
Yep, correct.

**Comment by themantalope** [comment]
Great! Really appreciate it!
