### ISSUE TITLE
Specifying the location of metadata provider in local mode

### ISSUE THREAD

**Issue by sunho** [Netflix/metaflow#163]
Hello. 

I'm using metaflow in local mode and wondering how to specify the location of meta data provider (which is by default .metaflow folder of working directory)

I'm working with some project that uses the artifacts from another project, and this project has Makefile script in its root. It's very annoying to be not able to run commands from the project root directory.

**Comment by savingoyal** [comment]
@sunho How are you accessing the artifacts across projects? If you are using the Client API, you can specify the path to your folder using [metadata](https://docs.metaflow.org/metaflow/client#metadata-provider) - `metadata('<path>')`. Would that address your issue?

**Comment by sunho** [comment]
I somehow missed that section. It works very well now. Thank you!
