### ISSUE TITLE
Question: Access hash of a card while being populated

### ISSUE THREAD

**Issue by cserpellZF** [Netflix/metaflow#1665]
Is it possible to access the card hash while being populated in the same step, or in a following step of a flow?

For context, I tried using `cards.get_cards` but didn't find it there, neither in the `current.card` objects.

**Comment by valayDave** [comment]
Hey ! You will be able to access the card hash in the subsequent steps; Here is a quick snippet for that : 

```
@step
def end(self):
    from metaflow import current
    from metaflow.cards import get_cards
    # You can replace `start` with any step name in the flow that has a card
    print(get_cards(current.run["start"].task)[0].hash)
```

**Comment by cserpellZF** [comment]
Thanks valayDave, it worked.
