### ISSUE TITLE
S3 access denied even if I have full access to S3

### ISSUE THREAD

**Issue by CompareSan** [Netflix/metaflow#1677]
Hi,

I deployed metaflow in AWS with Terraform but when I launch my script (--with batch option) I get the following error:

<img width="1085" alt="Screenshot 2024-01-11 at 12 31 10" src="https://github.com/Netflix/metaflow/assets/72796580/8a33a002-1175-4af0-bdf3-9c207faeff7b">

Really appreciate if someone can help me.

**Comment by mdhuggins** [comment]
@CompareSan How did you resolve the issue? I am facing something similar
