### ISSUE TITLE
Metaflow break in opencv processing and not information is throw

### ISSUE THREAD

**Issue by ideivitcom** [Netflix/metaflow#168]
I'm executing eleven chunks. Each chunk have a dictionary with the fullpath of the image. Each chunk have arround 100k of images.

By the moment i have cut and only one chunk is passed to the function (foreach in other step, but with ony a chunk).

The first image is the code. This works, but if we uncomment the line  starting with denoise = ... metaflow is down and no message is output.

The second image below is that i get.
![image (1)](https://user-images.githubusercontent.com/48516073/78027341-80e70d00-735d-11ea-8c72-f9b144444281.png)
![image](https://user-images.githubusercontent.com/48516073/78027343-82183a00-735d-11ea-8dac-e689dc1ed3a8.png)

**Comment by savingoyal** [comment]
I don't think OpenCV throws a catchable exception while processing corrupt JPEGs.

**Comment by ideivitcom** [comment]
Yes it is probable... now i just remove all images with problems and i get:

It is posible get any log about the problem?
![image](https://user-images.githubusercontent.com/48516073/78374335-03750400-75cc-11ea-9152-26580ed0a77e.png)

Best regards

**Comment by savingoyal** [comment]
Can you post the execution log with the @catch decorator?

**Comment by ideivitcom** [comment]
Thank you for the fast answer.
I checked the documentation and i now i have the catch message, but the extrange is that i haven't any request in the code

/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

**Comment by ideivitcom** [comment]
I think this is other issue, so i will close and open a new once.
