### ISSUE TITLE
Support github pulls within Conda

### ISSUE THREAD

**Issue by romain-intel** [Netflix/metaflow#173]
In some cases, code that needs to be used comes from a Github repository and not a full package.

Pip, for example, allows code to be pulled directly from a Github repository. A feature similar to this would be nice with the conda decorator; in other words, the ability to point to code/package/something in a specific github. See also #170  for more context.

**Comment by savingoyal** [comment]
Conda installs from a binary (tarball) and not source (unlike pip), so unless the GitHub repo also contains a release binary we can't use conda for dependency installation.
