### ISSUE TITLE
SSL Request in parallel foreach 

### ISSUE THREAD

**Issue by ideivitcom** [Netflix/metaflow#174]
Hi. all the task died in a jupyter lab. 
No request in code, so i suppose that is the foreach.

/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)

**Comment by savingoyal** [comment]
These warnings can be safely ignored right now. For tracking, this is a follow-up to #168

**Comment by savingoyal** [comment]
Have you tried executing your code outside of Metaflow?
