### ISSUE TITLE
Is there any way to access local module?

### ISSUE THREAD

**Issue by miloszbednarzak** [Netflix/metaflow#175]
Is there any way of doing something that would work like this:

Having project structure such as below
```
project
│   flow.py   
│  __init__.py
│  
└───package
│   │   
│   │  __init__.py
│   │  module1.py
│   └  module2.py
```

Create flow that would use local package as dependecy and not needing to create conda dependency from this package like this:
```
# flow.py

from metaflow import FlowSpec, step

class LinearFlow(FlowSpec):

    @step
    def start(self):
        import package
        self.my_var = package.module1.function()
        self.next(self.end)

    @step
    def end(self):
        import package
        self.my_var2 = package.module2.function(self.my_var)
        print(f"output {self.my_var2}")
```

or that:
```
# flow.py

from metaflow import FlowSpec, step
import package

class LinearFlow(FlowSpec):

    @step
    def start(self):
        self.my_var = package.module1.function()
        self.next(self.end)

    @step
    def end(self):
        self.my_var2 = package.module2.function(self.my_var)
        print(f"output {self.my_var2}")
```

Maintaining this code in a separate dependency makes it harder to introduce any changes (e.g. lack of refactoring features such as renaming).

Do you have any idea how to handle this?

**Comment by bergdavidj** [comment]
@miloszbednarzak , put the module in its own directory at the same level as your flow, and make sure it as a proper `__inti__.py`. You should then be able to import it in your flow. 

project_dir
	-- my_flow.py
	-- module_dir
		-- __init__.py
		-- my_module.py
			
   
Say `my_module.py` defines a function `my_function` that you want to expose. `__init__.py` should have a line:
 ```
from .my_module import my_function
```

In you flow you can then do:
```
import module_dir
module_dir.my_function()
```

You Might also find this answer to this related question useful - https://github.com/Netflix/metaflow/issues/49#issuecomment-584255151

**Comment by miloszbednarzak** [comment]
Ok, my problem was in incorrect placing `flow.py` and lack of `__init__.py`. Thanks for help! 
And example in  https://github.com/Netflix/metaflow/issues/49#issuecomment-584255151 is also very useful.
