### ISSUE TITLE
Follow symlinks while packaging code

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#176]
More context - https://gitter.im/metaflow_org/community?at=5e8ee0ad5d148a0460f4f8d6

**Comment by dpatschke** [comment]
I would like to upvote support for this functionality. I currently have a subclass in its own file that I would like to use across multiple flows and thought I was being smart by storing it in a central location in my repo and then symlinking to it only to find out Metaflow doesn't handle this.

Is there another suggested method that Metaflow supports that doesn't require having multiple hard copies of the same 'subclass' file in multiple directories alongside with their accompanying Flow files?

**Comment by romain-intel** [comment]
This was fixed in #958.
