### ISSUE TITLE
Make default kubernetes resources configurable

### ISSUE THREAD

**Issue by martinhausio** [Netflix/metaflow#1769]
We recently upgraded our GKE Autopilot cluster to 1.29 and to our surprise, it is no longer calculating the resource allocation the same way, and the default metaflow resources are now "just a little" too large, resulting in our workflows being rejected.

I found the defaults are configured [here](https://github.com/Netflix/metaflow/blob/fbe4aa10280873beeada332390faf3fd45b5d8bb/metaflow/plugins/kubernetes/kubernetes_decorator.py#L96), and we also have many ways to configure the resources, but it would be ideal for us to be able to configure the default resources via an environment variable, much the same way we can set the nodeSelector.

**Comment by savingoyal** [comment]
Great idea! We would be open to a PR if you would like to submit one!

**Comment by martinhausio** [comment]
@savingoyal , I just submitted a quick PR for it! Hope this helps.
