### ISSUE TITLE
Invalid CloudWatch log group prefix

### ISSUE THREAD

**Issue by stathva** [Netflix/metaflow#1776]
https://github.com/Netflix/metaflow/blob/82898293ff4f6e66278c51d3ab4a5065b50aba3d/metaflow/plugins/aws/batch/batch_client.py#L214

The default CloudWatch log group prefix above is invalid. AWS reserves log groups starting with `AWS/`. Perhaps change it to `/aws/batch/job`

**Comment by madhur-ob** [comment]
According to https://docs.aws.amazon.com/batch/latest/userguide/using_awslogs.html#create_awslogs_logdriver_options
the default is `aws/batch/job`

Moreover, check the usage here: https://github.com/Netflix/metaflow/pull/1767#issue-2194180976
We supply `try/batch/custom/demo` i.e. without the `/` in beginning and it worked as shown in https://github.com/Netflix/metaflow/pull/1767#issuecomment-2005997732

**Comment by madhur-ob** [comment]
@stathva Did you have issues with running flows with what we have here i.e. `aws/batch/job` without the `/` in beginning?

**Comment by stathva** [comment]
>@stathva Did you have issues with running flows with what we have here i.e. aws/batch/job without the / in beginning?

@madhur-ob yes, we deployy Metflow Wofklows as StepFunctions, our workflow is using the `@batch` decorator to define the container image and step resource requirements but it doesn't specify a log group. 

The jobs failed with the following error:
```
"Reason": "CannotStartContainerError: Error response from daemon: failed to initialize logging driver: failed to create Cloudwatch log stream: InvalidParameterException: Log groups starting with AWS/ are reserved for AWS.",
```

So the problem is not missing `/` in general like in the `try/batch/custom/demo` example but using `aws/*` since its reserved.

**Comment by madhur-ob** [comment]
Aah, I think the fix is to not include it at all I guess...let me remove it, that way, it will consider `aws/batch/job` by default..

**Comment by simonhs87** [comment]
This happened to me now for unknown reasons. The "fix" is to assign log_options=["awslogs-group:/aws/batch/job"] to every batch step in the step functions i create. Using metaflow 2.11.6.

**Comment by madhur-ob** [comment]
@simonhs87 Can you please try with `2.11.9`? There was one more fix made in https://github.com/Netflix/metaflow/pull/1786
