### ISSUE TITLE
Issue with tutorial #4

### ISSUE THREAD

**Issue by minhtuev** [Netflix/metaflow#18]
Currently I am using pyenv local for my Python environment

```
➜  metaflow-tutorials python 04-playlist-plus/playlist.py run
Metaflow 2.0.0 executing PlayListFlow for user:minhtue
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
    Incompatible environment:
    The @conda decorator requires --environment=conda

**Comment by seeravikiran** [comment]
This has also pre requisities to install conda - which is our dependency management solution; and this tutorial is meant to showcase the feature.

**Comment by SteNicholas** [comment]
@minhtuev You can firstly install conda from https://conda.io/projects/conda/en/latest/user-guide/install/index.html. And then execute command "pip install PyLint". The tutorial will work when above steps complete.

**Comment by romain-intel** [comment]
A few comments here as well:
  - you definitely need to install Conda if you haven't already
  - Pylint is not required (but installing it will check to make sure your flow is up to snuff)
  - To run use `python 04-playlist-plus/playlist.py --environment=conda run (note the --environment flag).

**Comment by romain-intel** [comment]
@minhtuev, let me know if this resolved your issues and if so, please close the issue.

**Comment by minhtuev** [comment]
Sorry I haven't tried.

**Comment by savingoyal** [comment]
Closing this issue for now. Please comment and re-open for any follow-up.
