### ISSUE TITLE
support stdlibrary logging 

### ISSUE THREAD

**Issue by nicoa** [Netflix/metaflow#180]
Hey,

for me it would be great if metaflow used [the standard library logging module](https://docs.python.org/3/library/logging.html) instead of the current setup with printing (or would at least support to add some logging handler to the current procedures).

This would enable one to not only see this in cloudwatch but also to add custom handlers (filehandlers, google cloud logging, ...) and integrate metaflow better in existing infrastructure which is using the logging module often.

tbh, I did not dig that much into the code for now to understand how much work this would be, but consider this a really nice feature.

Please drop your thoughts on this, I'd like to discuss if this is possible :)

**Comment by savingoyal** [comment]
@nicoa Excellent point. We do something similar internally as well where all the execution logs are pushed into our data warehouse via an event stream enabled by a side-car. You can take a look at the [debugLogger](https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/__init__.py#L48) implementation for starters.

**Comment by nicoa** [comment]
Thanks! I will have a look. Already thought about that but wasn't sure how to use in the CLI with own SideCar Class - do I have to patch this into the implementation or can I somehow implement in a file and point there?

Will for sure try out the debugLogger - this should be simple by invoking with `--event-logger=debugLogger`, correct?

**Comment by savingoyal** [comment]
Currently, you will have to patch this into the metaflow code base. Going forward, we should make it easier to do BYOC but we are not there yet. Yes, right now you should be able to do `--event-logger=debugLogger` to execute - [here is the pointer](https://github.com/Netflix/metaflow/blob/master/metaflow/cli.py#L701) to relevant CLI args.

**Comment by savingoyal** [comment]
@nicoa Please comment and re-open this issue if needed.

**Comment by nicoa** [comment]
I think the logging thing would still be interesting (aka on initialization add some python logging handler or manipulate instead of passing the event-logger param), what would you think?

**Comment by timschulz91** [comment]
Also looking forward to having standard logging supported. I just don't like seeing `print(...)` in my code.

As a workaround (and I don't think this really addresses the other concerns in this issue), I have implemented something like this:
```python
import logging

from metaflow import FlowSpec

class PrintLogger(logging.Logger):
    def handle(self, record):
        print(f'{record.name}: {record.msg}')

class MyFlow(FlowSpec):
    @property
    def logger(self):
        """
        Get the logger for this class
        """
        logger = PrintLogger(name=self.__class__.__name__, level=logging.INFO)
        return logger

    @step
    def start(self):
        self.logger.info('Starting flow')
```

**Comment by saulbein** [comment]
Standard python logging support would also be greatly appreciated in order to get logs from libraries that use it (that is, most of them). It also helps in the rarer case of having to reuse code between projects which includes logging via stdlib. This would also give the users full control over logging formats, log levels in various libraries and external log aggregator support.
