### ISSUE TITLE
subprocess spawned from step times out

### ISSUE THREAD

**Issue by nicoa** [Netflix/metaflow#181]
Hey,

crossposting this from here: https://stackoverflow.com/questions/61186961/python-subprocess-stuck-in-aws-batch-job-spawned-via-metaflow

We experience some issues on AWS batch when executing steps calling suprocesses.

Since R is not supported, we prepare some data in the step and then execute the R script as a subprocess. 
It seems the R script runs fine (we log to google cloud logging from R as well as from python), but then the python script doesn't continue.
Either the R process doesn't terminate correctly after the last command or the python process hangs when trying to continue. At some point the whole step times out (by metaflow functionality used).

What works: running the whole Flow locally on a EC2 instance.
What doesn't: running the Flow locally with the R related steps running on batch (by decorating with @batch). Doing only python stuff in that step on batch works fine.

What I will try to maybe somehow make this more reproducible in the upcoming days (and will of course update if this yields to better understanding of the issues):
* run the whole script "locally", but in the docker container we pushed to AWS ECR to test whether this also times out.
* invoke the Flow not directly but as a subprocess from a python script

I hope somebody here may have some idea on what is happening and can help. Not sure whether this is more related to metaflow or to batch - feel free to request more information or to direct me to AWS to clarify this stuff.

**Comment by savingoyal** [comment]
This is interesting. Would it be possible to share the job logs? I think the next best step would be to run your code by yourself within the docker container that you use for AWS Batch.

**Comment by nicoa** [comment]
I'll add them later, can't find them anymore in cloudwatch and will re-run both the working and the not working version to provide both logs.

Regarding the docker container idea: yeah, we had the same idea and tried it yesterday (be on the EC2 instance, create docker container, mount the folder containing the Flow, login to container and run this python script from there) - succeded.

**Comment by nicoa** [comment]
Hmm, it seems this is not reproducible anymore and I really don't know what it was :-D Will observe in the next few days (running the Flow on a daily basis) and close this if I can't make it to re-occur.

**Comment by nicoa** [comment]
It seems this may be related to some problem with the docker image or whatsoever, I don't know. Will close this and re-open if it is reproducible in the future.
