### ISSUE TITLE
[QUESTION] Is it possible to use metaflow.S3 outside of standard metaflow use?

### ISSUE THREAD

**Issue by manugarri** [Netflix/metaflow#183]
First of all, my apologies if this is not the appropriate channel for questions.

After researching metaflow, I believe metaflow's implementation of parallel s3 reading is significantly faster than other alternatives (looking for a replacement of dask internal s3fs reading logic).

However, I cant seem to be able to read valid data from metaflow.S3. Here is a snippet that shows my issue:
```
S3_PATH = "s3://s3-bucket/path/"
s3 = S3(s3root=S3_PATH) 
s3 = s3.__enter__() # issue is the same with context manager
data = s3.get_all() # read all files in the root

first_file = data[0]
first_file.text   
```

The text representation of the files seems to be encoded in a way I cant figure out how to deserialize? How can we properly deserialize these string representations?

I also tried deserializing the locally downloaded data using metaflow datastore 

``` 
with gzip.GzipFile(data[0].path, mode="rb") as f: 
    r = f.read()
```

Yields `Not a gzipped file (b'15')`

**Comment by tuulos** [comment]
Hi @manugarri - this is an appropriate channel 🙂 

What's the error you are seeing with the first snippet? `.text` tries to [decode the object as UTF-8](https://github.com/Netflix/metaflow/blob/master/metaflow/datatools/s3.py#L145). If you want raw bytes which you can decode by yourself, use `first_file.blob`.

The issue with the second snippet seems to be that the file is not compressed with `gzip`. If you print out `data[0].path`, are you sure the file is a `gz` file?

**Comment by manugarri** [comment]
great, actually you were right on the 2 part, the file i was testing was a pointer that wasnt gzip encoded, so option 2 (reading the local temp file) works with gzipped files.

And regarding option 1, the best way to deserialized gzip bytes into the strings is with `gzip.decompress(data[1].blob)`.

I will close this issue, will comment if i get  a performance boost in dask with this!.
