### ISSUE TITLE
Integrating with an event-driven architecture

### ISSUE THREAD

**Issue by jhagege** [Netflix/metaflow#192]
Hi, is there any possibility to integrate a metaflow pipeline with an event-driven architecture. 
I'd like to have steps trigger external jobs on different infra and block until those jobs communicate their response through existing pubsub infrastructure. 
On successful receival, I'd like to unblock the step and pass him the result from the pubsub message.
Can you think of any possibility to handle it ? 
Thanks.

**Comment by savingoyal** [comment]
@jhagege You can embed your pubsub client and make a blocking request (sync call or an sync call with a callback/long polling job status) from inside of your step. 
```
@step 
def my_step(self):
    import my_pubsub_client
    self.token = my_pubsub_client.async(self.payload)
    while True:
        self.job_status = my_pubsub_client.get_job_status(self.token)
        if self.job_status.is_finished():
            break
    self.next(self.my_next_step())
```

**Comment by jhagege** [comment]
Thanks, looks good. 
Would it be possible to pass a "future" parameter to a step and poll it ? 
That would be similar to what you are suggesting but relating to a specific type of message.

**Comment by jhagege** [comment]
@savingoyal Any idea how to support awaiting for an asyncio.Future() inside the step ? 
For now it is not possible to prefix the function with 'async', could it be supported somehow ?
Thanks.

**Comment by savingoyal** [comment]
@jhagege we don't support `async` steps. Internally at Netflix, folks deploy their workflows to a [production scheduler](https://netflixtechblog.com/meson-workflow-orchestration-for-netflix-recommendations-fc932625c1d9) and these workflows trigger on certain events (a cron, or successful execution of upstream flows). We have a [similar integration for OSS](#202) with AWS Step Functions that might address your use case for now.

**Comment by jhagege** [comment]
Thanks for the detailed reply.
