### ISSUE TITLE
Argo Workflows Overrides Image in @kubernetes annotation.

### ISSUE THREAD

**Issue by stobias123** [Netflix/metaflow#1943]
I've configured a kubernetes annotation as shown...

```
    @kubernetes(
        gpu=1,
        image="path-to-my-image:2024.07.31-8",
        service_account="metaflow",
        shared_memory=8196,
        persistent_volume_claims={"metaflow-training": "/cache"},
    )
```

Executing interactively works fine, but once I execute in argo all of my resources and image config are lost. Do I need a different annotation?

**Comment by savingoyal** [comment]
@stobias123 that shouldn't be the case - what does your pod specification look like for workloads running on Argo Workflows?

**Comment by stobias123** [comment]
Ah this is my bad, slight confusion on my part. 

I need to annotate all steps (even start/end) with my kubernetes image. Even though the start/end steps aren't calling any code from libraries in my image, they seem to need those deps installed. Annotating all steps with my `@kubernetes` decorator resolved the issue.
