### ISSUE TITLE
metaflow failed to resume a flow

### ISSUE THREAD

**Issue by xujiboy** [Netflix/metaflow#1965]
Hi, recently I noticed that metaflow is having trouble to resume a previously failed run. My call pattern is like the following:
```bash
python my_flow resume my_step --origin-run-id 12345678
``` 
then I got this error msg, no matter which step I choose to resume: 
```
Data store error:
    No completed attempts of the task was found for task 'MyFlow/1723829756519226/infer_train_and_test_dates/41'
```
From the exection log I can see that metaflow is not cloning the previous successful steps from the `start`.

This issues was observed for metaflow version `2.12.11`, but it goes away if I downgrade to `2.12.5`.

**Comment by savingoyal** [comment]
#1956 is addressing this bug :)
