### ISSUE TITLE
Support for AWS Step functions

### ISSUE THREAD

**Issue by romain-intel** [Netflix/metaflow#2]
Metaflow on AWS currently requires a human-in-the-loop to execute and cannot automatically be scheduled. Metaflow could be made to work with AWS Step functions to allow the orchestration of Metaflow steps to be done by AWS.

**Comment by gonzalodiaz** [comment]
I just arrived to Metaflow and I'm thrilled to give it a try in my company.
Currently we are using Airflow on Kubernetes to schedule workflows. I would like to hear if you analyzed the possibility of scheduling Metaflow over Airflow. And if it would be possible to use K8s as infrastructure to run the steps. Thanks!

**Comment by savingoyal** [comment]
Hi @gonzalodiaz 
Thanks for giving Metaflow a try. We follow a plugins based architecture and it is indeed possible to schedule flows over Airflow and use K8s as the compute substrate and something we would like to offer in the near future. We welcome feature requests. Please open one.

**Comment by thundergolfer** [comment]
Is your team familiar with https://github.com/argoproj/argo? In theory you could compile your Flows down into Argo's workflow spec format (JSON/YAML) and then Argo could take care of execution.

**Comment by savingoyal** [comment]
Thanks for the link. Yes I am familiar with argo but haven’t looked at it deeply.

**Comment by impredicative** [comment]
Given that Metaflow is evidently seriously lacking a scheduler, either Step Functions or better yet an open source component of Metaflow itself can probably fill in the gap. Without a scheduler, indeed it seems to be an incomplete solution.

**Comment by codypenta** [comment]
For step function integration, is it possible to incorporate https://github.com/aws/aws-step-functions-data-science-sdk-python?

**Comment by impredicative** [comment]
As an observer, I don't see any need for AWS Step Functions integration since Metaflow should be able to manage workflow steps directly. Why pay extra for Step Functions?

**Comment by hgahlot** [comment]
AWS Step Functions need to be scheduled through CloudWatch. They do not have an in-built scheduler. However, CloudWatch has  a direct integration with Step Functions. It might be better to look into how CloudWatch + Lambda may be leveraged to act as a scheduler for Metaflow, separate from Step Functions.

> Metaflow could be made to work with AWS Step functions to allow the orchestration of Metaflow steps to be done by AWS.
Metaflow is an orchestrator itself so I think the only missing piece is to figure out the scheduling aspect. Using Step Functions as an orchestrator just because we need it to schedule Metaflow workflows is an overkill, IMO.

**Comment by impredicative** [comment]
Metaflow could in principle then manage those Cloudwatch Events and Lambdas too using a single job+schedule definition. That would be great.

**Comment by steveash** [comment]
Also maybe check out Glue Workflows which are a little more DAG-like compared to the Step Functions model https://docs.aws.amazon.com/glue/latest/dg/workflows_overview.html

**Comment by kylejmcintyre** [comment]
I'm confused about this statement:

> Netflix uses an internal DAG scheduler to orchestrate most modeling and ETL pipelines in production. Metaflow flows can be deployed to the production scheduler with a single command. A similar integration could be provided e.g. for AWS Step Functions (Github issue)

Is this saying that there isn't yet a way to schedule a flow to run in production, or that there's no DAG schedulor/executor to actually run a flow in a production setting? Thank you.

**Comment by savingoyal** [comment]
@kylejmcintyre Internally we export metaflow flows to a [DAG scheduler](https://netflixtechblog.com/meson-workflow-orchestration-for-netflix-recommendations-fc932625c1d9). A similar integration with AWS Step Functions is in the works.

**Comment by kylejmcintyre** [comment]
Thanks for your reply @savingoyal . Is what you do internally available to me as an open-source consumer? If so, is it considered a hidden/internal implementation detail currently that runs on my provisioned compute resources? Or is executing flows in a production setting not yet supported for folks outside of Netflix?

**Comment by savingoyal** [comment]
@kylejmcintyre Given that the DAG scheduler ([Meson](https://netflixtechblog.com/meson-workflow-orchestration-for-netflix-recommendations-fc932625c1d9)) we use internally is not an open-source project, we are working on an equivalent integration with AWS Step Functions to offer similar capabilities in metaflow OSS is in the works as we speak.

**Comment by impredicative** [comment]
Why is AWS Step Functions even needed then? It's just going to increase the bill by doing something that open source software can do for free. The real hardware which is needed is provided by AWS Batch/EC2/ECS and similar services.

**Comment by savingoyal** [comment]
@impredicative There are not very many production-grade DAG schedulers (no SPOF, HA, scalable) with good adoption in the open-source community. AWS Step Functions offers the guarantees that we seek from a production-grade scheduler and our integration can serve as a reference implementation for integrations with other schedulers.

**Comment by joe153** [comment]
I am interested in using this project but the obvious blocker is the scheduler. @savingoyal: do you have a rough timeline when it could be available?

**Comment by impredicative** [comment]
> @impredicative There are not very many production-grade DAG schedulers (no SPOF, HA, scalable) with good adoption in the open-source community. AWS Step Functions offers the guarantees that we seek from a production-grade scheduler and our integration can serve as a reference implementation for integrations with other schedulers.

As it has been noted in this thread before, Step Functions still use Cloudwatch Events for scheduling. Has this changed? If not, why is Step Functions being referred to a scheduler? Do you then really still need Step Functions, or is it Cloudwatch Events that you need?

**Comment by savingoyal** [comment]
@impredicative AWS Step Functions is a scheduler as it schedules tasks on AWS Batch. The state machine by itself can be triggered by using CloudWatch Events. Metaflow is **not** meant to be a replacement for a production-grade scheduler and through [our integrations](https://github.com/Netflix/metaflow/issues/202), we advocate that users publish their production workflows onto a production scheduler.

**Comment by savingoyal** [comment]
This feature is now generally available. The launch blog post is [here](https://netflixtechblog.com/unbundling-data-science-workflows-with-metaflow-and-aws-step-functions-d454780c6280) and the documentation is [here](https://docs.metaflow.org/going-to-production-with-metaflow/scheduling-metaflow-flows).
