### ISSUE TITLE
Tasks status not updated in RDS after retry 

### ISSUE THREAD

**Issue by jcasse** [Netflix/metaflow#201]
Tweak FAILURE_PERCENTAGE until you get at least one failure, but a success after retry in the following flow code:

```
import random

from metaflow import FlowSpec, current, step, retry


class Flow(FlowSpec):

    @step
    def start(self):
        random.seed(1)
        self.next(self.unreliable_step)

    @retry
    @step
    def unreliable_step(self):
        FAILURE_PERCENTAGE = 75
        failure = random.random() < (FAILURE_PERCENTAGE / 100)
        if failure:
            open('nonexistent_file')
        self.next(self.end)

    @step
    def end(self):
        print(f'{current.step_name}()')


if __name__ == '__main__':
    Flow()
```

It seems that the status on RDS is the one from the first attempt and does not get updated after retries.
However, if the metadata is stored locally (not RDS), the task status is updated correctly.

**Comment by jwang01** [comment]
I am able to duplicate the error.

**Comment by savingoyal** [comment]
Thanks for the issue @jcasse. @ferras will have a fix ready for consumption at the soonest. Coincidentally, we discovered the same issue earlier this morning.
