### ISSUE TITLE
Hearbeat daemon creates a run out of production namespace

### ISSUE THREAD

**Issue by dkarlo2** [Netflix/metaflow#2029]
When heartbeat daemon is enabled, running a flow deployed in production namespace sometimes results in a run executed under user namespace. This often causes `Object not in the current namespace` errors, and often runs fail.
This seems to happen when heartbeat daemon starts before the start step.
I identified a probable cause to this issue - some Metaflow environment variables are missing when deploying daemon (e.g. METAFLOW_PRODUCTION_TOKEN) [here](https://github.com/Netflix/metaflow/blob/f4f0a09c20c0d0efd7e013a3bb1289a5738916d3/metaflow/plugins/argo/argo_workflows.py#L2561-L2575).
What I assume happens is that daemon [here](https://github.com/Netflix/metaflow/blob/f4f0a09c20c0d0efd7e013a3bb1289a5738916d3/metaflow/plugins/argo/daemon.py#L48) registers a run in user namespace instead of production namespace.

**Comment by saikonen** [comment]
Opened a PR with a possible fix for this if you want to give it a spin. I was unable to get my test flows to outright fail, but did notice that the runs sometimes register with incorrect project info as reported. 

This being so timing dependant makes reliable testing a bit flaky, but from what I observed, adding the missing envs did seem to fix the issue.

**Comment by saikonen** [comment]
looping back on this, the complete fix was introduced in https://github.com/Netflix/metaflow/releases/tag/2.12.22 where the argo workflows daemon now correctly registers all project related system tags for a flow.
