### ISSUE TITLE
Set memory limit to equal memory request?

### ISSUE THREAD

**Issue by tylerpotts** [Netflix/metaflow#2046]
Currently Metaflow doesn't set the memory limit for jobs on Kubernetes. This can be an issue if there are two memory-hungry jobs running on the same node. If both flows together use more than is available on the node, then the node crashes with an OOM error which is difficult to debug.

I suggest that the memory limit be set to equal the memory request on Kubernetes to avoid this situation.

**Comment by savingoyal** [comment]
hi - this is available now. if you set `@kubernetes(cpu=2, memory=8000, qos='Guaranteed')` it will set requests to limits on the kubernetes pod.
