### ISSUE TITLE
Inspect foreach step failure flow

### ISSUE THREAD

**Issue by ghsama** [Netflix/metaflow#207]
Hello,
thank you or this wonderful work.
I have a question about an issue i faced, when i have a foreach workflow, how can i access a specific 'each' that causes the failure using jupyter widgets to inspect it.
COuld we se the PID ?
When i try to inspect it using  the path like '1590575755239670/savedata/648' i got an empty step with no data inside to inspect. and when i use the last run (which is the one failed) and access the step to inspect (which is parallelized for many inputs) it gives an arbitrary one and not the last one that caused the failure .
Any trick to access a specific step in a foreach case scenario ?

**Comment by savingoyal** [comment]
Hi @ghsama!
You can list all the tasks for a step. For `foreach` a step will result in multiple tasks - You can very simply just do - `Step(MyFlow/1/step).tasks` to get an iterator to all the tasks launched by that step.

**Comment by ghsama** [comment]
Thank you .. that's what i'm looking for (y)
