### ISSUE TITLE
The card viewer server should load data from METAFLOW_CARD_LOCALROOT location

### ISSUE THREAD

**Issue by svpino** [Netflix/metaflow#2120]
We can configure the location of the metadata and cards using the METAFLOW_DATASTORE_SYSROOT_LOCAL and METAFLOW_CARD_LOCALROOT.

Unfortunately, the card viewer server doesn't use these environment variables to determine where the metadata is located. Instead, we have to run the command from the same folder where the metadata is.

Consider relying on the env variables so we don't have to change folders whenever we have to run the card server.

An alternative solution is to add a parameter to control the location of the folder. Something like this:

```
python pipeline.py card server --metadata-dir /.metaflow
```

**Comment by savingoyal** [comment]
thanks for the bug report! we are looking into it

**Comment by ch-enfuse** [comment]
Hi, currently having an issue with this, I saw the changes went in for the latest release (2.12.29) Im still not sure what i need to do to not have the cards create a .metaflow folder
