### ISSUE TITLE
Add `environment` parameter to conda decorator

### ISSUE THREAD

**Issue by sergiocalde94** [Netflix/metaflow#216]
Imagine you want to run a step with an environmnet that has a lot of dependencies. It is very verbose to include all of the libraries in the `libraries` parameter.

It would be very useful to have a parameter or something that allows metaflow to use a conda environment path directly.

I don´t know if you have already done this but I can´t found it :(

Thank you!

**Comment by savingoyal** [comment]
@sergiocalde94 The reason we ask for explicit listing in the `libraries` parameter is that it then makes your flow portable and reproducible. Not every existing conda environment is reproducible by default (for example - multiple `conda installs` within the same environment might lead to an inconsistent environment). 

You can also list your dependencies using a variable - 
```
...
    @conda(libraries=PACKAGES)
    @step
    def start(self):
    ...
```
where `PACKAGES` is a dict that can be manually obtained by 
`conda list -n my_environement --json | jq '.[] | {name, version} | with_entries(if .key == "name" then .key = "key" else . end | if .key == "version" then .key = "value" else . end)' | jq -s '. | from_entries' `.

**Comment by sergiocalde94** [comment]
Thank you very much for your response, for our problem this is not a valid answer because we have some differents problems, but here is the implementation of our helper method thanks yo your comment, then we apply it in conda decorator with `conda(**get_conda_environment('metaflow_step_X_env'))`:

```python
def get_conda_environment(env_name: str) -> Dict[str, str]:
    """Get libraries ready to add to metaflow
    conda decorator given a conda environment
    `env_name`
    """
    str_libraries = (subprocess.check_output(
        f'../scripts/get_conda_libraries.zsh {env_name}',
        shell=True,
        universal_newlines=True)
    ).replace('\n', '')

    re_search_libraries = [
        re.search('"(.*)": "(.*)"', library_and_version)
        for library_and_version in str_libraries.split(',')
    ]

    dict_libraries = dict(
        ((re_search.group(1), re_search.group(2))
         for re_search in re_search_libraries)
    )

    return dict(libraries=dict(((library, version)
                                for library, version in dict_libraries.items()
                                if library != 'python')),
                python=dict_libraries['python'])
```

One of the main problems I see is when yo try to develop with metaflow in a non internet (nor conda installed) environment. For example our discovery environment in my company has neither internet nor conda.

We build conda environments in local and we deploy them to our server with conda-pack tool, so we can use conda even we haven´t got it installed.

So for us is a problem if we cannot use an already existing environment because we cannot install packages in our develop environments :(

I think we will try to develop a plugin to allow users to do this, if we get it I will open a PR if you want :)

**Comment by sergiocalde94** [comment]
Hi again @savingoyal 

I talked with my mate @tomasborrella and we are very grateful about your comments.

If you will not add this environment parameter I think that it´s better to close this issue, what do you think about it?

If we develop a new plugin or modify the existing one (I don´t know what you prefer) we will make a PR to metaflow repo if you consider it useful.

Thank you again for your help :)

**Comment by sergiocalde94** [comment]
@savingoyal for me that option suits perfectly, but I don´t know if we can fit this solution in our enterprise environment :(

Once we decide what is the best between that solution, create a new plugin or modify the existing one I will send it to you here! 👍

**Comment by savingoyal** [comment]
Sounds good. Looking forward to your PR!

**Comment by savingoyal** [comment]
@sergiocalde94 #240 should also allow you maintain your own set of plugins internally at Orange. We will post docs around that shortly.

**Comment by savingoyal** [comment]
@romain-intel FYI, whenever #240 is ready for prime-time.

**Comment by sergiocalde94** [comment]
@savingoyal great news :)
