### ISSUE TITLE
Adding black as an option to check code style

### ISSUE THREAD

**Issue by mkemka** [Netflix/metaflow#218]
pylint is fantastic and has some checks but black (https://black.readthedocs.io/en/stable/) has some additional adjustments to code formatting that might be beneficial at the 'run' step instead of a git commit step.

**Comment by savingoyal** [comment]
Yes, we are looking into other options given that the more recent versions of pylint aren't happy with our use of `self.next(...)` and it can be rather slow while recursing through dependencies. `Black` and `pyflakes` are two options we are looking into.
