### ISSUE TITLE
Metaflow is changing indentation

### ISSUE THREAD

**Issue by sergiocalde94** [Netflix/metaflow#223]
Hi again, sorry for the spam (👎 to me)

I have also found this, it turns out that metaflow eliminates all the indentation from the logs, I find the truth a bit strange but I'm sure you can tell me the reason for this.

In addition, related to #221 it also happens that the prints are logged at the end of the code and the tqdm (in this case) even if it appears later than the prints in the code comes out first in the final log of Metaflow.

`dummy_flow.py` code for reproducibility:

```python
from metaflow import FlowSpec, step
from time import sleep
from tqdm import tqdm


class DummyFlow(FlowSpec):
    """Dummy flow
    """
    @step
    def start(self):
        """Start of our dummy flow
        """
        print('Welcome to your dummy flow! \N{grinning face}')

        self.next(self.test_logs)

    @step
    def test_logs(self):
        """Test indentation and progress bar
        """
        print("             Hi! I am an indented text...")
        print("Hello, I´m not!")
        
        for i in tqdm(range(10000)):
            sleep(.00001)
            continue

        self.next(self.end)

    @step
    def end(self):
        """
        Last step in the flow, says goodbye
        """
        print('Goodbye!.')


if __name__ == '__main__':
    DummyFlow()

```

And the output:

![metaflow](https://user-images.githubusercontent.com/22750693/85052264-e7c7d580-b198-11ea-9c1b-8d443acc7530.png)

Some advices about this? Thanks!

**Comment by savingoyal** [comment]
Thanks for the issue! Let me look into this.

**Comment by sergiocalde94** [comment]
Thanks for closing this :) @savingoyal
