### ISSUE TITLE
Formatting error for run timestamps

### ISSUE THREAD

**Issue by vlandeiro** [Netflix/metaflow#224]
It looks like Metaflow uses `time` to store the `created_at` and `finished_at` information inside the run: https://github.com/Netflix/metaflow/blob/c2f70c73782549fdce6c418410ecd9b305199b28/metaflow/client/core.py#L340-L341

`time` does not support the `%f` directive: https://docs.python.org/3/library/time.html#time.strftime
This creates strings that are not easily parsable by `datetime` or `time` and lack the millisecond information. The missing information is not a big deal in my opinion as we are not looking at sub-second Metaflow runs. However, the strings require custom parsing which is not ideal.

See the following example to reproduce outside of Metaflow:

```python
import time

ts_epoch = int(round(time.time() * 1000))
ts_str = time.strftime('%Y-%m-%dT%H:%M:%S.%fZ', time.gmtime(ts_epoch//1000))
print(ts_str)
time.strptime(ts_str, '%Y-%m-%dT%H:%M:%S.%fZ')
```

The output when running this is:
```
2020-06-22T16:00:51.fZ
```
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-165-7b973d37458a> in <module>
      4 ts_str = time.strftime('%Y-%m-%dT%H:%M:%S.%fZ', time.gmtime(ts_epoch//1000))
      5 print(ts_str)
----> 6 time.strptime(ts_str, '%Y-%m-%dT%H:%M:%S.%fZ')

~/miniconda3/envs/risk_models/lib/python3.6/_strptime.py in _strptime_time(data_string, format)
    557     """Return a time struct based on the input string and the
    558     format string."""
--> 559     tt = _strptime(data_string, format)[0]
    560     return time.struct_time(tt[:time._STRUCT_TM_ITEMS])
    561 

~/miniconda3/envs/risk_models/lib/python3.6/_strptime.py in _strptime(data_string, format)
    360     if not found:
    361         raise ValueError("time data %r does not match format %r" %
--> 362                          (data_string, format))
    363     if len(data_string) != found.end():
    364         raise ValueError("unconverted data remains: %s" %

ValueError: time data '2020-06-22T16:00:51.fZ' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

Note the `f` in the printed timestamp that causes an issue at parsing time.

One solution would be to use `datetime` to format the time as it supports `%f`. Something like this:

```python
import time
from datetime import datetime

ts_epoch = int(round(time.time() * 1000))
ts_struct = time.gmtime(ts_epoch//1000)
dt = datetime.fromtimestamp(time.mktime(ts_struct))
dt_str = datetime.strftime(dt, '%Y-%m-%dT%H:%M:%S.%fZ')
print(dt_str)
datetime.strptime(dt_str, '%Y-%m-%dT%H:%M:%S.%fZ')
```
output:
```
2020-06-22T17:02:49.000000Z
datetime.datetime(2020, 6, 22, 17, 2, 49)
```

Let me know if I'm missing something. If this sounds like a good solution to you, I'm happy to open a PR

**Comment by savingoyal** [comment]
@vlandeiro Thanks for opening the issue! We should just drop `%f` since we are not exposing timings at a millisecond grain. Can you open a PR for that?

**Comment by vlandeiro** [comment]
Thanks for the quick feedback @savingoyal. I opened #227 to remove `%f` from `strftime`
