### ISSUE TITLE
Error: no such option --environment

### ISSUE THREAD

**Issue by mausch** [Netflix/metaflow#229]
I have a simple FlowSpec class using `@conda_base`.

when I try to run it with `python my_flow.py run` I get:

```
Metaflow 2.0.5 executing xxx for user:mauricio
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
    Incompatible environment:
    The @conda decorator requires --environment=conda
```

so I add `--environment=conda` as requested, only to get:

```
Metaflow 2.0.5 executing xxx for user:mauricio
Usage: xxx.py run [OPTIONS]
Try 'xxx.py run --help' for help.

Error: no such option: --environment
```

**Comment by savingoyal** [comment]
Try `python my_flow.py --environment=conda run`

**Comment by mausch** [comment]
Thanks, that worked. 

BTW this _is_ documented in https://docs.metaflow.org/metaflow/dependencies#local-execution , my bad for not RTFM ! :slightly_smiling_face:
