### ISSUE TITLE
Installation instruction to use conda

### ISSUE THREAD

**Issue by oonisim** [Netflix/metaflow#246]
Please consider modifying the installation instruction to use conda instead of pip.

Metaflow requires conda. However the instruction in https://docs.metaflow.org/getting-started/install tells:
```
pip install metaflow
```

As in https://www.anaconda.com/blog/using-pip-in-a-conda-environment, conda and pip are different package management system which are not meant to be used together.

> Unfortunately, issues can arise when conda and pip are used together to create an environment, especially when the tools are used back-to-back multiple times, establishing a state that can be hard to reproduce. Most of these issues stem from that fact that conda, like other package managers, has limited abilities to control packages it did not install. Running conda after pip has the potential to overwrite and potentially break packages installed via pip. Similarly, pip may upgrade or remove a package which a conda-installed package requires. In some cases these breakages are cosmetic, where a few files are present that should have been removed, but in other cases the environment may evolve into an unusable state.

Conda can install metaflow, hence I suppose there would not be a reason that we need to use pip.
```
$ conda config --add channels conda-forge
$ conda install metaflow
Collecting package metadata (current_repodata.json): done
Solving environment: done
## Package Plan ##
  environment location: /Users/user/opt/anaconda3/envs/test
  added / updated specs:
    - metaflow
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    brotlipy-0.7.0             |py36h37b9a7d_1000         353 KB  conda-forge
    cffi-1.14.0                |   py36h356ff06_0         214 KB  conda-forge
    chardet-3.0.4              |py36h9f0ad1d_1006         187 KB  conda-forge
    cryptography-2.9.2         |   py36hc9d8292_0         599 KB  conda-forge
    docutils-0.15.2            |           py36_0         739 KB  conda-forge
    pysocks-1.7.1              |   py36h9f0ad1d_1          27 KB  conda-forge
    s3transfer-0.3.3           |   py36h9f0ad1d_1          90 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.2 MB

The following NEW packages will be INSTALLED:

  boto3              conda-forge/noarch::boto3-1.14.16-pyh9f0ad1d_0
  botocore           conda-forge/noarch::botocore-1.17.16-pyh9f0ad1d_0
  brotlipy           conda-forge/osx-64::brotlipy-0.7.0-py36h37b9a7d_1000
  cffi               conda-forge/osx-64::cffi-1.14.0-py36h356ff06_0
  chardet            conda-forge/osx-64::chardet-3.0.4-py36h9f0ad1d_1006
  click              conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0
  cryptography       conda-forge/osx-64::cryptography-2.9.2-py36hc9d8292_0
  docutils           conda-forge/osx-64::docutils-0.15.2-py36_0
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  jmespath           conda-forge/noarch::jmespath-0.10.0-pyh9f0ad1d_0
  metaflow           conda-forge/noarch::metaflow-2.0.5-pyh9f0ad1d_0
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py36h9f0ad1d_1
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  requests           conda-forge/noarch::requests-2.24.0-pyh9f0ad1d_0
  s3transfer         conda-forge/osx-64::s3transfer-0.3.3-py36h9f0ad1d_1
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  urllib3            conda-forge/noarch::urllib3-1.25.9-py_0

Proceed ([y]/n)? 
```

It looks there are efforts to make pip compatible within conda but looks still work in progress.

PyPy builds on conda-forge
mproving interoperability with pip

**Comment by savingoyal** [comment]
@oonisim The dependency management feature of Metaflow uses conda behind the scenes. So you can easily use `pip` (or conda) to install metaflow and then use `@conda` decorator to execute your metaflow steps within specific conda environments. The `@conda` decorator has no dependency on `pip` which allows us to avoid the inter-op issues that you mentioned. 

Let me know if you need more clarification.

**Comment by oonisim** [comment]
See https://github.com/Netflix/metaflow/issues/250.
