### ISSUE TITLE
Tutorial episode 2 failure with pylint 

### ISSUE THREAD

**Issue by oonisim** [Netflix/metaflow#247]
# Problem
The tutorial does not specify the pylint issue described in the release note 2.0.5.
>Upper-bound pylint version to < 2.5.0.
pylint version 2.5.0 would mark Metaflow's self.next() syntax as an error. As a
result, python helloworld.py run would fail at the pylint check step unless we run with
--no-pylint . This version upper-bound is supposed to automatically downgrade
pylint during metaflow installation if pylint==2.5.0 has been installed.

Hence, it causes the issue and blocks the tutorials.

```
$ python 02-statistics/stats.py run
Metaflow 2.0.5 executing MovieStatsFlow for user:onishim4p
Validating your flow...
    The graph looks good!
Running pylint...
    02-statistics/stats.py:57:8: E1102: self.next is not callable (not-callable)
    02-statistics/stats.py:82:8: E1102: self.next is not callable (not-callable)
    02-statistics/stats.py:96:8: E1102: self.next is not callable (not-callable)
    Pylint is not happy:
    Fix Pylint warnings listed above or say --no-pylint.
```

# Environment
Using conda environment.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101

$ python --version
Python 3.7.6

$ conda --version
conda 4.8.2
```

# Request

Please be specific with the pylint version in the tutorial or specify the option to disable it.
```
$ python 02-statistics/stats.py --no-pylint run
```

**Comment by savingoyal** [comment]
Good point. The conda package didn't have the constraint `pylint<2.5.0` which exists for the pip package. I just made the [change](https://github.com/conda-forge/metaflow-feedstock/commit/037e2e72a046884c4d2a56b09232428cc4ae756c#diff-e178b687b10a71a3348107ae3154e44cR29).

**Comment by ryan-williams** [comment]
I believe I just saw this failure with pylint 2.3.1 as well; using pylint 2.4.4 seemed to work.
