### ISSUE TITLE
Integration with Kubeflow pipelines

### ISSUE THREAD

**Issue by BAlmeidaS** [Netflix/metaflow#25]
First things first, thanks to open this project!! We are working in a very similar project, and Metaflow is going to help us a lot.

Do you plan to create a kind of integration with Kubeflow Pipelines? For us, this is very helpful to deploy these pipelines in our production environment.

**Comment by SteNicholas** [comment]
@BAlmeidaS I mentioned this integration with kubeflow in issue [Support for Airflow and Kubernetes](https://github.com/Netflix/metaflow/issues/16)comment. I really thought that metaflow integration with kubeflow reduce work in integration on Kubernetes.

**Comment by BAlmeidaS** [comment]
Yes @SteNicholas I saw the issue, I decided opened mine anyway because I thought that one thing is integration with k8s and deploy an orchestrated pipeline with docker. Another thing is to deploy a Kubeflow pipelines targz (which is similar but not the same thing).

**Comment by savingoyal** [comment]
Thanks for opening the issue, @BAlmeidaS . Issues like these are really informative as we go about planning our roadmap.

**Comment by Jeffwan** [comment]
@BAlmeidaS @
There's different options to integrate with KFP. User could use KFP SDK in metaflow or do something further and change orchestration and computing layer to kubeflow. Do you have some ideas in mind?

**Comment by valayDave** [comment]
Kubeflow's Pipeline features are a little different from Metaflow's DAG features. Kubeflow supports [conditional Steps in workflows](https://www.kubeflow.org/docs/pipelines/overview/concepts/graph/). Metaflow doesn't have support for conditional flows.

**Comment by talebzeghmi** [comment]
Kubeflow supports conditional branching concept that Metaflow doesn't.  Metaflow could compile to Kubeflow via an intermediate representation (https://github.com/kubeflow/pipelines/issues/3703)

**Comment by savingoyal** [comment]
@talebzeghmi I responded in [this other thread](https://github.com/Netflix/metaflow/issues/16#issuecomment-631004976). Our current integration to AWS Step Functions' State Machine Representation is in PR #202.

**Comment by savingoyal** [comment]
The reference [implementation for AWS Step Functions](https://app.gitbook.com/@hawkins/s/metaflow/going-to-production-with-metaflow/scheduling-metaflow-flows) is available [here](https://github.com/Netflix/metaflow/tree/master/metaflow/plugins/aws/step_functions) now. This should serve as a good starting point for any other scheduler integration.

**Comment by BAlmeidaS** [comment]
Sorry for the enormous delay to answer this, I lose the tracking about this project. I was very excited about it when it launched but we developed our own solution to integrate with kfp. Answering @Jeffwan, IMO we could use kfp to deploy via metaflow. User may not notice that she is deploying a pipeline in kubeflow. Even metaflow doesn't having some features that kubeflow pipelines has. What you guys think about it??

**Comment by savingoyal** [comment]
Closing this issue given that #992 that addresses #50 has been merged. Kubeflow Pipelines also uses Argo Workflows under the hood so a layer of indirection through Kubeflow Pipelines doesn't really serve much benefit currently.

**Comment by mt-ob** [comment]
Hi folks, we have the `metaflow-kubeflow` extension available here: https://github.com/outerbounds/metaflow-kubeflow
CC: @BAlmeidaS @SteNicholas @Jeffwan @talebzeghmi
