### ISSUE TITLE
Offload flow variables to disk

### ISSUE THREAD

**Issue by puntopasta** [Netflix/metaflow#254]
dear metaflow team,

thanks for making this awesome toolkit available for all of us to use :)

One thing I run into when creating flows with forks, especially "foreach" fork/join flows, the outcome of each of the forked steps will be loaded simultaneously into memory and made available in the join step. This makes sense since all of this data is needed at the join-step, but when you do a fork over a large database this always means you will run out of memory when working locally.

My request is to add an option where flow variables are written to disk upon completion of a step, and can be loaded by the next step one by one for processing.

 Of course I can do this on my own, but abstracting this away from the core logic would make for a more "out of the box" experience. I can imagine a solution using the getter/setter property decorators to create custom get/set functions for different types of stores (with default being in-memory)

**Comment by savingoyal** [comment]
@puntopasta The variables are written to the disk when the step ends and read lazily in subsequent steps as needed. Has your experience been different?

**Comment by puntopasta** [comment]
I didn't know this was already in place, thanks for explaining and great that this has been thought about already 👍  Somehow my memory does overload when I run the pipeline over the entire dataset as opposed to running it in chunks. I assumed this was the cause but then I'll have to do some further digging to understand the cause next week. Will get back to you when I single out the issue.

**Comment by puntopasta** [comment]
hi @savingoyal 

So I tried to see what's happening. See below. 

- In this first example, I load all data from a previous run in the start step and then dispatch it in a foreach-fork

    @step
    def start(self):
        with open(self.run) as f:
            run_id = f.readline()
        run = Run(self.flow_name+'/'+run_id)
        start_step = Step(self.flow_name+'/'+run_id+'/start').task
        self.days = []
        for ix, routing_step in enumerate(Step(self.flow_name+'/'+run_id+'/route_drivers_per_day').tasks()):
            drivers = routing_step.data.drivers_matrix
            drivers_segmented = routing_step.data.drivers_segmented
            requests = start_step.data.requests.loc[drivers.index]
            drivers_to_suggest = run.data.drivers_to_suggest[ix]
            movements = run.data.movements[run.data.movements.timestep.isin(drivers.index)]
            self.days+=[(drivers,drivers_segmented, requests, drivers_to_suggest, movements)]
            self.days +=[routing_step]
        self.next(self.process_day, foreach='days')
            
    @step
    def process_day(self):
        """Loads all data designated for this day
        """
        import numpy as np
        drivers,drivers_segmented, requests, drivers_to_suggest, movements = self.input`



- In this second example, I only identify which steps to load in the start step, and then let the workers load the data by themselves after the foreach-fork.


      @step
       def start(self):
        """
        The start step:
        1) Identifies the steps to be loaded and dispatches to parallel processing

        """
        with open(self.run) as f:
            self.run_id = f.readline()

        self.days = []
        for ix, routing_step in enumerate(Step(self.flow_name+'/'+self.run_id+'/route_drivers_per_day').tasks()):
            self.days += [(ix, routing_step)]
        self.next(self.process_day, foreach='days')
            
            
    @step
    def process_day(self):
        """Loads the data designated for this worker
        """
        run = Run(self.flow_name+'/'+self.run_id)
        start_step = Step(self.flow_name+'/'+self.run_id+'/start').task
        ix, routing_step = self.input
        drivers = routing_step.data.drivers_matrix
        drivers_segmented = routing_step.data.drivers_segmented
        requests = start_step.data.requests.loc[drivers.index]
        drivers_to_suggest = run.data.drivers_to_suggest[ix]
        movements = run.data.movements[run.data.movements.timestep.isin(drivers.index)]`


In both examples, the exact same data is being loaded. The difference is that in the first example all data is loaded upfront and dispatched to parallel workers, whereas in example 2 the data is loaded within the workers. The number of parallel workers is in both cases the same. In the second example, the amount of memory being used while parallel processing is about 3 GB which runs fine on my machine. In the first example however, even though step 1 successfully loads the entire dataset into the self.days variable (takes about 8 GB of ram), after that when the parallel processing starts the memory quickly spikes and fills up my entire RAM (16 GB) and then Ubuntu comes to a full freeze ;) That's why I thought that all data was somehow being duplicated across workers.

**Comment by romain-intel** [comment]
I think you have properly identified the issue here. To access `self.input`, Metaflow downloads the entire variable `self.days` here and then returns the proper slice for it which explains that each `process_day` process is trying to download the entire array (thus causing your out of memory issue). I think the approach you use in the second case is definitely the proper approach in this case. Artifacts are persisted at the object level (ie: not a item level for an array for example). For isolation, this may not be a great solution either (but maybe a bit better than this), you could maybe consider storing each day as a separate artifact, something like: 
```
# In your start step
drivers = routing_step.data.drivers_matrix
drivers_segmented = routing_step.data.drivers_segmented
requests = start_step.data.requests.loc[drivers.index]
drivers_to_suggest = run.data.drivers_to_suggest[ix]
movements = run.data.movements[run.data.movements.timestep.isin(drivers.index)]
setattr(self, 'day_%d' % ix, (drivers, drivers_segmented, requests, drivers_to_suggest, movements))
self.days += [(ix, routing_step)]

# In your process_day step
ix, routing_step = self.input
drivers, drivers_segmented, requests, drivers_to_suggest, movements = getattr(self, 'day_%d' % ix)
```

**Comment by puntopasta** [comment]
Thanks for the clarification. I hadn't thought about the work-around of dynamically assigning variable names, makes sense to do that now that I know that variables are read lazily. 

For me personally, I can move forward with this knowledge, but I can imagine you might want to document this behavior and in the future support to load only a slice of the array when self.input is read in a for-each worker. This might no be straight-forward though.. I see you are using NamedTemporaryFile locally, and blob storage in S3, which both are difficult to "sub-select" data from. Anyway, just food for thought ;)

Thanks for the help 👍

**Comment by romain-intel** [comment]
Yes, it is not easy to extract "slices" from python objects dynamically. Artifacts are pickled and gzipped which makes it much harder but it may be interesting to support something that is explicitly sliceable as you suggest. I will close this issue for now but feel free to re-open if needed.
