### ISSUE TITLE
Make s3 and boto optional

### ISSUE THREAD

**Issue by pombredanne** [Netflix/metaflow#261]
There are a __lot__ of dependencies that come with boto and that are not typical production dependencies such as docutils and sphinx. Could it be possible to avoid always having these as dependencies, maybe as optional deps?
Would you be open to a PR for that?

**Comment by savingoyal** [comment]
@pombredanne `boto` is currently optional in the sense that you can do `pip install click requests metaflow --no-deps` and metaflow will work correctly in all local mode. Moving `boto` to an explicit optional-deps will end up breaking the current experience.

**Comment by pombredanne** [comment]
@savingoyal you made an excellent point! ... I forgot about no-deps. Thanks! closing this then

**Comment by pombredanne** [comment]
Actually I mistakenly reported docutils and sphinx as deps of boto... and that's not correct and was coming from some other sources. In anycase the --no-deps works for me.
