### ISSUE TITLE
pylint 2.5.x compatibility. 

### ISSUE THREAD

**Issue by melanopsis** [Netflix/metaflow#271]
Any chance you update your pylint dependency to version 2.5.x? 

All the best.

**Comment by savingoyal** [comment]
some of the changes in the more recent versions of pylint break the lint behavior. You can always disable pylint checks by passing `--no-pylint` flag to your executions. You can install metaflow without pylint by simply doing `pip install requests click boto3 metaflow --no-deps`

**Comment by melanopsis** [comment]
I see that pylint is no longer pinned to a specific version #462. Closing this.
