### ISSUE TITLE
Dynamic Allocation Of Resources for Local/Batch based Flows

### ISSUE THREAD

**Issue by valayDave** [Netflix/metaflow#301]
I am working with ML experiments with Pytorch which require precise allocation of resources(GPUs) according to the some selected hyperparameter generated within the flow. Currently, I have to allocate static branches when doing a flow for resource provisioning or I have to over-provision according to the way below if I use a foreach.  
```
class CurrentResourceFlow(FlowSpec):
    
    @step 
    def start(self):
        self.hyper_params = [1,2,3,4,5]
        self.next(self.train_fan_out,foreach='hyper_params')

    @resource(gpu=8)
    @step
    def train_fan_out(self)
        '''
            train function which leverages GPU's according to 
            self.input
        '''
        self.checkpoint = trainer(args,num_gpus=self.input)
    
    @step 
    def join(self,inputs):
        pass
    

    @step
    def end(self):
        pass
```
Based on current MF spec :
1) I can make static branches based on underlying compute need 
OR 
2) parameterize resource specs at the start of the flow. 

But these somehow make the flow very compute dependent.  

Can there be a way to do dynamic resource provisioning via some construct?

**Comment by tuulos** [comment]
Right, today it is not possible directly. The current recommendation is to define a few static branches, e.g. small/medium/large, with corresponding `@resources` and have logic in the code that divides work amongst the branches. A challenge is that some runtime environments may need the resources to be specified in advance, so defining them on the fly is not always possible. Anyways, we could think about creative ways to support this.

Some previous threads about the topic:
 - https://gitter.im/metaflow_org/community?at=60146d510eed905f187c6c70
 - https://gitter.im/metaflow_org/community?at=5f05dec33e4a827d19b1439a

**Comment by seanv507** [comment]
AFAIK there seems to be a problem with the suggested workaround?

If I create static branches of small, medium, large, then there must be at least 1 item of each type otherwise metaflow creates an 
exception. 

What do you suggest? Do I have to create a dummy array: `self.large_inputs = ["do_nothing"]`  and handle appropriately?


My expected behaviour is that if the loop is empty then that branch would proceed to the corresponding join step  

```
flow TestLoop step loop_large> failed:
2021-06-22 19:21:27.258 [2417/loop_large/120792 (pid 64942)]     Invalid self.next() transition detected on line 34:
2021-06-22 19:21:27.258 [2417/loop_large/120792 (pid 64942)]     Foreach iterator over large_inputs in step loop_large produced zero splits. Check your variable.
```

```
#!/usr/bin/env python
from typing import Optional

from metaflow import (
    FlowSpec,
    Parameter,
    current,
    environment,
    resources,
    retry,
    step,
)

class TestLoop(FlowSpec):
    
    @step
    def start(self):
        self.small_inputs = [0,1]
        self.medium_inputs = [2]
        self.large_inputs = []
        self.next(self.loop_small, self.loop_medium, self.loop_large)

    @step
    def loop_small(self):
        self.next(self.run_small, foreach="small_inputs")

    @step
    def loop_medium(self):
        self.next(self.run_medium, foreach="medium_inputs")
    
    @step
    def loop_large(self):
        self.next(self.run_large, foreach="large_inputs")
    
    @resources(memory=100)
    @step
    def run_small(self):
        self.result = self.input * 2
        self.next(self.join_small)

    @resources(memory=500)
    @step
    def run_medium(self):
        self.result = self.input * 4
        self.next(self.join_medium)

    @resources(memory=1000)
    @step
    def run_large(self):
        self.result = self.input * 10
        print(self.input)
        self.next(self.join_large)
    
    @step
    def join_small(self,inputs):
        self.result = [input.result for input in inputs]
        self.next(self.join_resources)
    
    @step
    def join_medium(self,inputs):
        self.result = [input.result for input in inputs]
        self.next(self.join_resources)

    @step
    def join_large(self,inputs):
        self.result = [input.result for input in inputs]
        self.next(self.join_resources)

    @step
    def join_resources(self, inputs):
        self.result = {"small": inputs.join_small.result, "medium": inputs.join_medium.result, "large": inputs.join_large.result}
        self.next(self.end)

    @step
    def end(self):
        print(self.result)
if __name__ == "__main__":
    TestLoop()
```

**Comment by banjtheman** [comment]
I ended up just adding a dummy_object to the array and setting a flag to skip processing

i.e

```
       ....
        if len(self.my_array) == 0:
            self.my_array.append("dummy_object")
            self.is_dummy = True
            logging.info("No items found, adding dummy object")
        else:
            self.is_dummy = False

        self.next(self.next_step, foreach="my_array")


    @step
    def next_step(self):
        """
        This step runs the next step
        """
        if not self.is_dummy:
            ....

```

**Comment by tuulos** [comment]
[As of Metaflow 2.13, you can use `Config` to assigns values to `@resources`](https://docs.metaflow.org/metaflow/configuring-flows/introduction) through a config file. It doesn't allow runtime `@resources`, but you can use it to do config-driven experimentation with automatically assigned `@resources` much more easily than before

**Comment by savingoyal** [comment]
yet another option is to use [conditionals](https://outerbounds.com/blog/agentic-metaflow)

**Comment by breno-costa** [comment]
> yet another option is to use [conditionals](https://outerbounds.com/blog/agentic-metaflow)

how can `conditionals` be used to configure `@resources` at runtime?
