### ISSUE TITLE
continuously updating data

### ISSUE THREAD

**Issue by andaag** [Netflix/metaflow#31]
```
self.days = [0 to NOW]
self.next(self.compute_day, foreach='days')
```

This will work, but if I rerun it it will recompute days 0 to NOW. I can easily "hack" that by interfacing with s3 directly to skip running day 0 if we already have the results... but that breaks local testing. 

There's a few ways of doing this, params/client api/interfacing with s3 directly, but they are not super elegant.

Is this a pattern that you've discussed? Is it a valid usecase of metaflow, or do you recommend delegating this to airflow or similar?

**Comment by savingoyal** [comment]
@andaag We do have similar use-cases at Netflix. The recommendation is that you should [parameterize your flow](https://docs.metaflow.org/metaflow/basics#how-to-define-parameters-for-flows) to execute on a list of days and some other external system should be able to trigger your workflow with the appropriate list of days you should be processing upon. At Netflix, our production scheduler [Meson](https://medium.com/netflix-techblog/meson-workflow-orchestration-for-netflix-recommendations-fc932625c1d9) supports event based triggers which plays elegantly with this pattern. Another, not so elegant, alternative is to embed a light-wieght check before your `self.next` call to filter out done days.

**Comment by andaag** [comment]
How do you then easily join that data? Do you use the client api to query the specific segments, or do you store the data outside of the metaflow dataartifact?

**Comment by seeravikiran** [comment]
Yes. Or if it were internal they leverage the hosting service - see open issues - which makes accessing any specific dateint depending on what we’re deployed (has a versioned REST endpoint) or promoted to be the latest.
The client API will help you - if you want to join all the data for your use case. In the internal ones; they are usually interested in the latest - when running in a cron like fashion.

**Comment by savingoyal** [comment]
@andaag Not sure I understood your question around joining the data appropriately. According to my interpretation, you can use the client API in a separate job (or even in the same flow as a separate step) to look up all the dates that haven't been successfully processed yet (might have to take care of current inflight dates being processed by another instantiation of your workflow appropriately) and trigger your workflow with those dates as parameters (or use those dates as foreach arg if embedding this logic as a step in your flow). Let me know if I ended up answering something else entirely.

**Comment by andaag** [comment]
Using the client api + foreach sounds fairly sane 👍. A bit manual compared to the built in support for split/join, but very manageable.

My question was just to doublecheck if there was a more elegant way of doing this.
