### ISSUE TITLE
Error in match.arg(algo): 'arg' should be one of “md5”, “sha1”, “crc32”, “sha256”, “sha512”, “xxhash32”, “xxhash64”, “murmur32”

### ISSUE THREAD

**Issue by hatemr** [Netflix/metaflow#313]
Running `metaflow::test()` using Metaflow in R gives this error. Any idea what's going on?

`> metaflow::test()`
Error in match.arg(algo) : 
  'arg' should be one of “md5”, “sha1”, “crc32”, “sha256”, “sha512”, “xxhash32”, “xxhash64”, “murmur32”

**Comment by jasonge27** [comment]
Metaflow depends on `digest` library for some hashing functions -- can you update `digest` and give it a try? We will make it more robust in the next release. Thanks for reporting this problem!

**Comment by savingoyal** [comment]
@hatemr If you force reinstall the package again, the issue should be fixed.
