### ISSUE TITLE
How to get location of data after IncludeFile()

### ISSUE THREAD

**Issue by smolendawid** [Netflix/metaflow#325]
I'm struggling to use Metaflow in my project to use it on AWS. In the project, I use `lmdb` package to store and load images from `.mdb` files. Each data set is written in binary files `data.mdb` and `lock.mdb`. To load the data, we have to pass the directory containing these two files to `lmdb.open()` function and there's no other way to use the package at the moment. However after using `IncludeFile() `I have these two files in object fields and they are stored somewhere on s3 in the directory that I can find.

Is there any way to dump data from `self` to a directory in a correct format? Or should I approach the problem differently? For example, I could get the path on a target docker of the cached data sets but I don't know how to look for it

Thanks

**Comment by romain-intel** [comment]
IncludeFile is specifically designed to import files and make them available as artifacts to your flows so it does not look like it would necessarily be a good use case in your situation. Files are also renamed (so they won't be named `data.mdb` and `lock.mdb`) which, if I understood the question properly, seems to be something you need.

I would approach this problem a little differently and use the S3 data tools to access the files properly. You can use the S3 data tools to upload, download and list files so depending on where your source images are, you could:
- use the data tools to upload the images to a bucket in S3 in the proper directory structure (this could be a first step that runs locally on your machine if the images are initially on your machine)
- depending on how `lmdb` works, pass it the S3 bucket path directly or use the S3 tools to download the files appropriately. This could run on batch.

To answer your question directly, you can of course just do something like:
```
with open('somedir/data.mdb', mode='w') as f:
    f.write(self.data_mdb)
```
to dump what you have to a local file in the proper directory. Again, I am not sure this is the best approach in your case but IncludeFile does have the advantage of persisting the images "with" your run in some fashion (so you can actually always get the image back using the client even if you erase them from your local machine). If this is important, IncludeFile may be a good solution.

I hope this helps. Happy to give more help if I missed the mark.

**Comment by smolendawid** [comment]
Sorry if the question wasn't clear enough. Somehow I can't use the last solution you wrote, because I can't dump this object to file like that. Maybe some pickling would help but it may have other problems.

The idea of utilizing s3 bucket is simple and good enough. I didn't get this idea on my own, I have to get used to AWS. I solved my problem uploading data to s3 in local `@step` and downloading it in `@batch @step`. 

Thanks
