### ISSUE TITLE
Default CloudFormation - how to get info about experiments

### ISSUE THREAD

**Issue by smolendawid** [Netflix/metaflow#327]
I am creating a new SageMaker notebook on Sagemaker notebook instance that was created in default CloudFormation stack. After that the code

```
from metaflow import Flow, get_metadata, namespace
print("Current metadata provider: %s" % get_metadata())
```
returns

> Current metadata provider: service@http://metaflo-NLB-12TQDX9Y6OGI6-0794ea3cdb38a394.elb.eu-central-1.amazonaws.com/

However this

```
from metaflow import Metaflow
print(Metaflow().flows)

```

Prints empty list. I run at least a few experiments and flows and I can see Metaflow logs in some s3 bucket created by the stack.

What can I do to see my flows on this instance?

**Comment by savingoyal** [comment]
@smolendawid You need to [switch to the global namespace](https://docs.metaflow.org/metaflow/tagging#switching-namespaces) to see all flows.
```
set_namespace(None)
```

**Comment by savingoyal** [comment]
Please reopen this issue if you have any followups.

**Comment by smolendawid** [comment]
Great, thank you. Sorry I missed the closure of the issue
