### ISSUE TITLE
Any way to stop the main instance automatically after flow execution?

### ISSUE THREAD

**Issue by smolendawid** [Netflix/metaflow#334]
I noticed after my flow executes it does not stop the instance. If I use foreach, additional instances are created and then stopped, but one instance is always active. 

How can I tell the instance to always stop after the experiment?

**Comment by smolendawid** [comment]
Is it correct behavior that one instance is always on?

**Comment by savingoyal** [comment]
@smolendawid It depends on how you are configuring your AWS Batch compute environment. If you set the minVCPUs to 0, AWS Batch should scale down your cluster to 0 instances. Do note that instance scale up/down policies for AWS Batch are slightly non-trivial and you might not see scale down to 0 immediately even after you pin minVCPUs to 0.

**Comment by savingoyal** [comment]
Please reopen this issue if you have any followups.
