### ISSUE TITLE
Support spark Dataframe

### ISSUE THREAD

**Issue by zhouqb** [Netflix/metaflow#335]
It seems that we couldn't use spark dataframe as a data artifact, since metaflow is all in-memory processing. What's the best way to extend metaflow to support spark df?

**Comment by tuulos** [comment]
hi @zhouqb! At Netflix we use Spark actively for ETL. We materialize the results of Spark jobs (Spark dataframes) to Parquet files, e.g. in Hive tables. Metaflow flows may then refer to the tables or the Parquet files directly as artifacts.

**Comment by qibin-integral** [comment]
@tuulos Thanks!!! Do you have an example of how to pass parquets between steps.

**Comment by chanansh** [comment]
What about batch sql job from metaflow as a preprocessing step?

**Comment by savingoyal** [comment]
https://github.com/outerbounds/metaflow-pyspark
