### ISSUE TITLE
Meta @batch, @resources, @schedule decorators

### ISSUE THREAD

**Issue by talebzeghmi** [Netflix/metaflow#336]
These decorators are named generically yet are specifically tied to AWS Batch or AWS Step Functions.  As Metaflow expands to other runtimes, this proposal is to keep the Metaflow DSL and decorators detached from the runtime for the data scientist.     

This issue is coming up as we are experimenting with a Kubeflow Pipeline plugin, and find the need to duplicate or create copy @resources and @schedule decorators.  I was under the original impression that @batch and @resources were abstract following the "meta" philosophy in the name Metaflow.

The issue also arises when running an example Flow with a batch decorator in another runtime, like Kubeflow or Kubernetes with a provided plugin.

**Comment by savingoyal** [comment]
@talebzeghmi The `@resources` and `@schedule` decorators are intended to be _meta_ in the way you refer. They live in the same directory as `aws/batch` or `aws/stepfunctions` since those are the current execution/orchestration backends we support currently on AWS. You should be able to rely on `@resources` and `@schedule` without any changes to them and introduce a new decorator `@k8s` which can function similar to `@batch`.

**Comment by talebzeghmi** [comment]
That's great that `@resources` and `@schedule` are _meta_! 

It's a pity that a FlowSpec Python file is bound to the runtime via `@batch` or future `@k8s` like decorators.  Could there be a way in which a `step` is decorated with `@batch`, but is bound at runtime?


```python
    @batch(cpu=1, memory=500)
    @step
    def hello(self)
      ...
```      

```bash
metaflow helloaws.py run --on=<aws_batch | k8s | gcp | ...>   # default could be AWS Batch
```

But can be specified if necessary in code:
```python
    @batch(cpu=1, memory=500, on="aws_batch")
    @step
    def hello(self)
      ...
```

**Comment by savingoyal** [comment]
`@batch` is tied to AWS Batch and the expected usage pattern for `@resources` is 
```
    @resources(cpu=1, memory=500)
    @step
    def hello(self)
      ...
```
```
python helloaws.py run --with batch
```
or 
```
python helloaws.py run --with k8s
```

The `@resources` decorator just specifies the resources that the task needs and the `--with` directive provides the runtime context.

**Comment by talebzeghmi** [comment]
Thank you @savingoyal, this is awesome !
