### ISSUE TITLE
Add content type & encoding to s3 objects on put

### ISSUE THREAD

**Issue by hajapy** [Netflix/metaflow#337]
It does not seem possible to set the content type or encoding of objects we put to s3 using metaflow's s3 methods. Having a way to either set this manually or have it be guessed automatically from the object key's file extension would be beneficial for applications that want to serve these objects to web browsers through pre-signed urls or even just for users browsing the files in s3 through the aws console (otherwise all links automatically result in a download). This is especially useful for media types like images and video, but it can be nice even for text, json, and other formats as well. 

I previously contributed a similar patch to mlflow: https://github.com/mlflow/mlflow/pull/2881, which is based on guessing the content type/encoding using the [stdlib's mimetypes.guess_type method](https://docs.python.org/3.8/library/mimetypes.html#mimetypes.guess_type). I suggest something like this, or at least a user-provided way to pass such keys down the stack so that ultimately the s3 client calls can be given the ExtraArgs obj with ContentType set.

**Comment by tuulos** [comment]
@hajapy great suggestion! We have been planning to add support for custom headers in `metaflow.S3`. Would this work for you? Do you care if the information is stored in a custom header in S3 (`x-amz-meta-my-content-type`) vs. the standard `content-type` header?

**Comment by hajapy** [comment]
I don't believe a custom header would address the primary use case I had in mind, since those objects would still appear as `binary/octet-stream` from s3's perspective. When you produce a pre-signed url to get the object, the browser will not natively handle them even if they should be supported media types. 

You can test that by using the aws console and clicking Open on such an object (eg. an image file) - rather than opening in a new tab, it will be downloaded.

**Comment by romain-intel** [comment]
This is addressed in #351  if you want to follow-along and comment on the API. We will support both content-type header as well as any custom user header.

**Comment by hajapy** [comment]
Thanks @romain-intel, that looks good! I can make use of the these to handle adding content type when directly storing objects into s3 (which happens often for us as our workflows output things like images, json, video). 

The only thing missing is it won't automatically guess the file type (when using `s3.put_file`), which is perhaps something to consider as a follow up. There may be a way to set that as an opt-in flag, like say `with S3(guess_file_content_type=False) as s3: ...`. Regardless, this is nice!
