### ISSUE TITLE
Copy and Paste error in docs

### ISSUE THREAD

**Issue by jonaschn** [Netflix/metaflow#339]
I found a small copy and paste error in your docs:
https://admin-docs.metaflow.org/metaflow-on-aws/deployment-guide/manual-deployment
Current:
```
METAFLOW_DATASTORE_SYSROOT_S3 = s3://metaflow-s3/flows
METAFLOW_DATASTORE_SYSROOT_S3 = s3://metaflow-s3/data-tools
METAFLOW_DEFAULT_DATASTORE=s3
```
Expected:
```
METAFLOW_DATASTORE_SYSROOT_S3 = s3://metaflow-s3/flows
METAFLOW_DATATOOLS_SYSROOT_S3 = s3://metaflow-s3/data-tools
METAFLOW_DEFAULT_DATASTORE=s3
```
Fix: DATASTORE --> DATA**TOOLS**

**Comment by savingoyal** [comment]
@jonaschn Thanks for catching the error. I have made the fix.
