### ISSUE TITLE
urlparse can not parse s3 url correctly

### ISSUE THREAD

**Issue by xiaochuan-du** [Netflix/metaflow#34]
After setting s3 bucket, an error occurs:
```
S3 datastore operation _put_s3_object failed (Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"). Retrying 7 more times..
```
This is due to in `metaflow/datastore/s3.py` `urlparse` can not figure out schema and `netloc` correctly.

A simple workaround is replacing the following content
```
try:
    # python2
    from urlparse import urlparse
    import cStringIO
    BytesIO = cStringIO.StringIO
except:
    # python3
    from urllib.parse import urlparse as offcial_urlparse
    import io
    BytesIO = io.BytesIO
```
with
```
try:
    # python2
    from urlparse import urlparse as offcial_urlparse
    import cStringIO
    BytesIO = cStringIO.StringIO
except:
    # python3
    import io
    from urllib.parse import urlparse as offcial_urlparse
    BytesIO = io.BytesIO
# modified by Kevin
# 07/12/2019
def urlparse(path):
    return offcial_urlparse(path if path.startswith('s3:') else 's3://' + path)
```
There should be a more elegant way to fix the issue

**Comment by savingoyal** [comment]
What’s the schema for your S3 bucket that you are configuring?

**Comment by xiaochuan-du** [comment]
> What’s the schema for your S3 bucket that you are configuring? We expect paths to be prefixed by s3://.

In `.metaflowconfig/config.json` "METAFLOW_DATASTORE_SYSROOT_S3": "s3://tsproj"

**Comment by savingoyal** [comment]
And that isn't working? What are the steps you took to reproduce the behavior?

**Comment by savingoyal** [comment]
It will work if you remove the `s3://` prefix. We will make a small patch to handle this in the next release.

**Comment by xiaochuan-du** [comment]
> It will work if you remove the `s3://` prefix. We will make a small patch to handle this in the next release.

Thanks, mate. It helps
