### ISSUE TITLE
Locally access data from S3 datastore using non-local metadata-service

### ISSUE THREAD

**Issue by jonaschn** [Netflix/metaflow#340]
I tried to run the metadata-service as well as the s3 datastore (but locally using the s3-compatible minio).
When I tried to access the results by connecting to 
```
from metaflow import Metaflow, Flow, Run, get_metadata, metadata, get_namespace, namespace
metadata('http://localhost:6789')
namespace('user:data-service')
```
the metadata is fetched correctly but there is no way to set the datastore.
I assumed that the service communicates the datastore that is in use (in my case s3) for fetching the artifacts.

However when accessing the data for a specific run:
```
run = Run('Preprocessing/2')
print(run.tags)
print(run.data.y_train)
```
The following exception occurs:
```
~/.pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/metaflow/client/filecache.py in _internal_get_data(self, ds_type, flow_name, run_id, step_name, task_id, path, load_func)
    103 
    104         if ds_cls.datastore_root is None:
--> 105             raise FileCacheException('Cannot locate datastore root')
    106 
    107         fileobj = None

FileCacheException: Cannot locate datastore root
```
Workaround:
Set the env variable `METAFLOW_DATASTORE_SYSROOT_S3` in `~/.metaflowconfig/config.json`, e.g., `s3://metaflow/flows`

Proposed Solution:
introduce helper functions `get_datastore` and `datastore`:
```
from metaflow import Metaflow, Flow, Run, get_metadata, metadata, get_namespace, namespace, get_datastore, datastore
metadata('http://localhost:6789')
datastore('http://s3host:port', 's3://bucket/prefix')
// datastore(METAFLOW_S3_ENDPOINT_URL, METAFLOW_DATASTORE_SYSROOT_S3)
namespace('user:data-service')
```

**Comment by seeravikiran** [comment]
I think the workaround you suggested is probably the right thing to do; since metaflow (and the client) pick up your datastore configuration from the environment variables. 
You can also set them using `metaflow configure`.

To understand if there is room for improvement in the messaging could you share the configuration prior to the error to see if you just accidentally set up datastore=s3 but didn't set the root?

cc @romain-intel If you want to add something.

**Comment by jonaschn** [comment]
@seeravikiran I ran `metaflow configure reset` (on my local machine) so there was no "local" configuration in `~/.metaflowconfig/config.json`

**Comment by savingoyal** [comment]
@jonaschn This should be resolved now with the newer versions of Metaflow
