### ISSUE TITLE
The target directory exists, but it is not a conda environment.

### ISSUE THREAD

**Issue by smolendawid** [Netflix/metaflow#352]
Hello 

I want to run a node on batch. With only `@conda` decorator and deps code works locally for me. 

However, when I add `@batch`, I am facing a pretty verbose error:

> RuntimeError: command '['/Users/dasm/miniconda3/condabin/conda', 'create', '--yes', '--no-default-packages', '--name', 'metaflow_LeaveOneOutTraining_linux-64_9bfd73f19fe9363a6bb7d3ad2615700b1ea980ae', '--quiet', b'python==3.7.8', b'click==7.1.2', b'requests==2.24.0', b'boto3==1.14.61', b'coverage==4.5.4', b'metaflow==2.2.3', b'scikit-learn==0.23.2', b'plotly==4.10.0', b'pandas==0.23.2', b'mlflow==1.8.0']' returned error (1): b'{\n  "command": "/Users/dasm/miniconda3/condabin/conda create --yes --no-default-packages --name metaflow_LeaveOneOutTraining_linux-64_9bfd73f19fe9363a6bb7d3ad2615700b1ea980ae --quiet python==3.7.8 click==7.1.2 requests==2.24.0 boto3==1.14.61 coverage==4.5.4 metaflow==2.2.3 scikit-learn==0.23.2 plotly==4.10.0 pandas==0.23.2 mlflow==1.8.0",\n  "conda_info": {\n    "GID": 417684552,\n    "UID": 1796363309,\n    "active_prefix": "/Users/dasm/miniconda3/envs/my_project",\n    "active_prefix_name": "my_project",\n    "channels": [\n      "https://conda.anaconda.org/conda-forge/linux-64",\n      "https://conda.anaconda.org/conda-forge/noarch",\n      "https://repo.anaconda.com/pkgs/main/linux-64",\n      "https://repo.anaconda.com/pkgs/main/noarch",\n      "https://repo.anaconda.com/pkgs/r/linux-64",\n      "https://repo.anaconda.com/pkgs/r/noarch",\n      "https://conda.anaconda.org/pytorch/linux-64",\n      "https://conda.anaconda.org/pytorch/noarch"\n    ],\n    "conda_build_version": "not installed",\n    "conda_env_version": "4.8.5",\n    "conda_location": "/Users/dasm/miniconda3/lib/python3.7/site-packages/conda",\n    "conda_prefix": "/Users/dasm/miniconda3",\n    "conda_private": false,\n    "conda_shlvl": 2,\n    "conda_version": "4.8.5",\n    "config_files": [\n      "/Users/dasm/.condarc"\n    ],\n    "default_prefix": "/Users/dasm/miniconda3/envs/my_project",\n    "env_vars": {\n      "CIO_TEST": "<not set>",\n      "CONDA_DEFAULT_ENV": "my_project",\n      "CONDA_EXE": "/Users/dasm/miniconda3/bin/conda",\n      "CONDA_JSON": "True",\n      "CONDA_PREFIX": "/Users/dasm/miniconda3/envs/my_project",\n      "CONDA_PROMPT_MODIFIER": "(my_project) ",\n      "CONDA_PYTHON_EXE": "/Users/dasm/miniconda3/bin/python",\n      "CONDA_ROOT": "/Users/dasm/miniconda3",\n      "CONDA_SHLVL": "2",\n      "CONDA_SUBDIR": "linux-64",\n      "CONDA_USE_ONLY_TAR_BZ2": "True",\n      "CURL_CA_BUNDLE": "<not set>",\n      "PATH": "/Users/dasm/google-cloud-sdk/bin:/Users/dasm/opt/miniconda3/bin:/Users/dasm/miniconda3/envs/my_project/bin:/Users/dasm/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin",\n      "PYTHONIOENCODING": "UTF-8",\n      "PYTHONNOUSERSITE": "1",\n      "PYTHONPATH": "/Users/dasm/projects/my_project",\n      "PYTHONUNBUFFERED": "1",\n      "REQUESTS_CA_BUNDLE": "<not set>",\n      "SSL_CERT_FILE": "<not set>"\n    },\n    "envs": [],\n    "envs_dirs": [\n      "/Users/dasm/miniconda3/envs",\n      "/Users/dasm/.conda/envs"\n    ],\n    "netrc_file": null,\n    "offline": false,\n    "pkgs_dirs": [\n      "/Users/dasm/miniconda3/pkgs",\n      "/Users/dasm/.conda/pkgs"\n    ],\n    "platform": "linux-64",\n    "python_version": "3.7.4.final.0",\n    "rc_path": "/Users/dasm/.condarc",\n    "requests_version": "2.24.0",\n    "root_prefix": "/Users/dasm/miniconda3",\n    "root_writable": true,\n    "site_dirs": [],\n    "sys.executable": "/Users/dasm/miniconda3/bin/python",\n    "sys.prefix": "/Users/dasm/miniconda3",\n    "sys.version": "3.7.4 (default, Aug 13 2019, 15:17:50) \\n[Clang 4.0.1 (tags/RELEASE_401/final)]",\n    "sys_rc_path": "/Users/dasm/miniconda3/.condarc",\n    "user_agent": "conda/4.8.5 requests/2.24.0 CPython/3.7.4 Darwin/19.5.0 OSX/10.15.5",\n    "user_rc_path": "/Users/dasm/.condarc",\n    "virtual_pkgs": [\n      [\n        "__osx",\n        "10.15.5"\n      ]\n    ]\n  },\n  "error": "OSError(62, \'Too many levels of symbolic links\')",\n  "exception_name": "OSError",\n  "exception_type": "<class \'OSError\'>",\n  "traceback": "Traceback (most recent call last):\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/exceptions.py\\", line 1079, in __call__\\n    return func(args, kwargs)\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/cli/main.py\\", line 84, in _main\\n    exit_code = do_call(args, p)\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py\\", line 83, in do_call\\n    return getattr(module, func_name)(args, parser)\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py\\", line 41, in execute\\n    install(args, parser, \'create\')\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/cli/install.py\\", line 317, in install\\n    handle_txn(unlink_link_transaction, prefix, args, newenv)\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/cli/install.py\\", line 346, in handle_txn\\n    unlink_link_transaction.execute()\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/core/link.py\\", line 244, in execute\\n    self.verify()\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/common/io.py\\", line 88, in decorated\\n    return f(args, kwds)\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/core/link.py\\", line 231, in verify\\n    exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/core/link.py\\", line 591, in _verify\\n    itervalues(prefix_action_groups)):\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/common/io.py\\", line 525, in map\\n    yield func(thing)\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/core/link.py\\", line 411, in _verify_individual_level\\n    error_result = axn.verify()\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/site-packages/conda/core/path_actions.py\\", line 323, in verify\\n    source_size_in_bytes = getsize(self.source_full_path)\\n  File \\"/Users/dasm/miniconda3/lib/python3.7/genericpath.py\\", line 50, in getsize\\n    return os.stat(filename).st_size\\nOSError: [Errno 62] Too many levels of symbolic links: \'/Users/dasm/miniconda3/pkgs/ncurses-6.2-he1b5a44_2/share/terminfo/N/NCR260VT300WPP\'\\n"\n}\nUpload successful.\n'

After that, when I run the same code without any mods for a second time:

> Validating your flow...
>     The graph looks good!
>     Conda ran into an error while setting up environment.:
>     Step: train, Error: DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
>     Use 'conda create' to convert the directory to a conda environment.
>       target directory: /Users/dasm/miniconda3/envs/metaflow_LeaveOneOutTraining_linux-64_9bfd73f19fe9363a6bb7d3ad2615700b1ea980ae
> 

Earlier my pipelines were working with `@batch` decorator for sure, so I have no idea what is happening?

**Comment by savingoyal** [comment]
@smolendawid Thanks for opening the issue. We were notified of a similar issue on [gitter](https://gitter.im/metaflow_org/community?at=5f84e9b999e1ab4dd1f69086) as well. One of the transitive dependencies for your environment is causing this issue. 

The reason why you only see this issue when running `--with batch` is because we force Conda to perform dependency resolution for Linux even if you are on macOS, and one of the underlying dependency broke. A workaround, for now, is to set `anaconda` as your highest priority channel, while we work on a longer-term fix. For example - `CONDA_CHANNELS=anaconda,conda-forge python3 myflow.py --environment=conda run --with batch`

**Comment by smolendawid** [comment]
Thanks for the workaround

**Comment by zexuan-zhou** [comment]
Just experienced with the same issue. I'm running metaflow inside a docker image on my local machine, and the `~/.conda/environments.txt` in my docker image got corrupted. I restarted my docker and now it works.
