### ISSUE TITLE
Selecting specific foreach tasks by ID/input

### ISSUE THREAD

**Issue by Viveckh** [Netflix/metaflow#359]
Lets say I'm running `analyze_person` step using `foreach` and passing in personID as input.
I want to be able to access the data artifacts produced by the step for person x, person y, person z.

I know joining the `foreach` outcomes eventually when it is done running that step for all people is an option, but there are a lot of people to process, and I don't want to have to wait until it completes for all people to utilize the results. or lose the processed outcomes if it the flow fails halfway for some reason.

The documentation for `Step.task` states that :

`Convenience method to return the unique Task associated with this Step. If a Step has more than one Task, this will return any of them (no order guaranteed).` 

Is there a way I can access a specific task through some ID or input param.

**Comment by savingoyal** [comment]
@Viveckh You can access a specific task by using its identifier - `Task('MyFlow/1/a/42')` where `MyFlow` is the flow name, `1` is the run ID, `a` is the step name and `42` is the task ID. You can also do - 
```
step = Step('MyFlow/1/a')
task = step['42']
```

**Comment by Viveckh** [comment]
Thanks @savingoyal ! Is the task ID something I can assign?

If not, is it something I can access from within the task while its' running, so I can store it elsewhere and tie person x to the their specific task ID

**Comment by samithaj** [comment]
@Viveckh please let me know how to access this current object ?

**Comment by adiamb** [comment]
this seems to work - 
```
step = Step('MyFlow/1/a')
task_list=list(step.tasks())
```
