### ISSUE TITLE
Integration with Ray Distributed for batch processing

### ISSUE THREAD

**Issue by crypdick** [Netflix/metaflow#365]
My company extensively uses Ray Distributed across our projects, but especially for hyperparameter tournaments and model inference. Metaflow looks like a great tool, but porting all our distributed computation from Ray to AWS Batch doesn't make sense.

**Comment by tuulos** [comment]
@crypdick Can you elaborate on your use case? Could you e.g. submit Ray jobs in Metaflow steps? It shouldn't require any special integration. This is how we integrate with e.g. Spark today.

**Comment by crypdick** [comment]
@tuulos Yes, I can use Ray within Metaflow steps, but without special integration I believe I am limited to using only the resources on the driver machine. However, I need to be able to take advantage of Ray's cluster autoscaling capabilities.

We have numerous use cases, but for example, for model serving we need to fetch terabytes of imagery off S3, pre-process, and pass to GPUs. We find that network I/O is a bottleneck, so our solution is to spin up many g3.8xlarge instances, which gives us a higher bandwidth to GPU ratio than (say) p3 instances. Ray lets us scale workloads from desktop to an arbitrarily large cluster, with some key features:

- the cluster can have heterogeneous instance types
- I can configure how aggressive I want elastic scaling based on usage and AWS spot instance pricing
- Ray has some nice tooling around cluster monitoring, which I rely on for debugging issues when architecting distributed systems and gaining observability on system health

**Comment by tuulos** [comment]
I apologize for silly questions since I haven't used Ray but can't you submit jobs to the Ray cluster, not just the local machine? There must be a way how you submit jobs to the cluster without Metaflow. Could you use the same method *with* Metaflow?

**Comment by crypdick** [comment]
@tuulos Ray does not have an API to submit "jobs" (standing up, running commands, and tearing down). It does have a CLI API which allows you to stand up/tear down clusters, and to execute commands on the cluster (but not via Python). The worker nodes will spin down when they go idle but I believe the head node will stay alive until told to shut down. However, I believe it's on the roadmap (cc @worldveil @simon-mo)

**Comment by savingoyal** [comment]
A hacky workaround, for now, could be to simply wrap the Ray CLIs call in `subprocess.check_call(...)` within a Metaflow step.

**Comment by tuulos** [comment]
@crypdick please give the `check_call` approach that @savingoyal suggested a try. We'd love to hear what kind of friction it causes (if any). It can guide our thinking towards a more "official" integration.

**Comment by crypdick** [comment]
@tuulos please let me know if this is right:

- inside each step, pass the `current.step_name` to the `check_call` so that Ray can use properly save datasets using `metaflow.S3`
- when I schedule the flow on AWS Step Functions, I need to set-up a driver node to actually run the `check_call`? So, set-up a Lambda (?) that will setup and tear down a cluster. After Ray is done Step Functions can execute the next flow step?

**Comment by Chris-Fourie** [comment]
@crypdick Hi =) 

I am looking into a similar integration of Metaflow and Ray - curious to know if your suggestion above worked out?

**Comment by crypdick** [comment]
@Chris-Fourie good timing! Anyscale (founded by the creators of Ray) has recently created a Python SDK to interact with clusters. It lets you setup and tear down Ray cluster sessions and run arbitrary commands, along with a bunch of other goodies. We have a ticket to make a nice `@anyscale` decorator using their SDK but it's unlikely that we're going to get to it before Q3. 

cc @anabranch @worldveil

**Comment by Chris-Fourie** [comment]
@crypdick Big thanks! =D 

Busy checking out the [Anyscale SDK ](https://anyscale-product.readthedocs-hosted.com/en/latest/developer-tools/sdk/index.html#) to get an idea of how one could use an `@anyscale` decorator with Metaflow? 

Would this wrap a Metaflow node? or would it be used to wrap something within a Metaflow node? 

Would it be possible to link to the ticket for the `@anyscale` decorator?

**Comment by crypdick** [comment]
@Chris-Fourie to clarify, I do not work for Anyscale, and the `@anyscale` decorator is a wishlist item in our (private) issue tracker. We have not started designing it yet, but I imagine it being a drop-in replacement for `@batch`.

**Comment by savingoyal** [comment]
here is the experimental decorator - https://github.com/outerbounds/metaflow-ray

**Comment by crypdick** [comment]
@savingoyal this is awesome!
