### ISSUE TITLE
File format of Data Artifacts?

### ISSUE THREAD

**Issue by Viveckh** [Netflix/metaflow#369]
Trying to understand what file format the artifacts / data files are stored in s3.

I want the frontend to be able to download the artifacts directly given the path of the artifacts, without using the Metaflow API. Any suggestions on how to decompress the artifacts file and have it ready for use without the API?

Also,

Is there an alternative to find a particular task in a list of tasks triggered by a `foreach` WITHOUT USING `task_id`. I know I can run an iterator through the `tasks` but that wouldn't be fast if there are thousands of tasks triggered by `foreach`. To use the task id solution, I have to first track the task ids in some table and map it with the input which is extra work. It would be nice if I could search and find the task of interest based on the input value it used.

**Comment by romain-intel** [comment]
The current format is typically gzipped pickled data. For your second question, do you mean you want to find the task that ran for a particular value of input?
