### ISSUE TITLE
Error on running metaflow on Mac

### ISSUE THREAD

**Issue by shivamy** [Netflix/metaflow#37]
(py3) [temp]> python -V
Python 3.5.2

(py3) [temp]> metaflow
Traceback (most recent call last):
  File "/Users/.../venv/py3/bin/metaflow", line 5, in <module>
    from metaflow.main_cli import main
  File "/Users/.../venv/py3/lib/python3.5/site-packages/metaflow/main_cli.py", line 243, in <module>
    @click.argument('episode', autocompletion=autocomplete_episodes)
  File "/Users/.../venv/py3/lib/python3.5/site-packages/click/decorators.py", line 151, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/Users/.../venv/py3/lib/python3.5/site-packages/click/core.py", line 1699, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'autocompletion'

**Comment by savingoyal** [comment]
@seeravikiran can you assist @shivamy on this?

**Comment by seeravikiran** [comment]
@shivamy could you also print the version of click present in your python environment as indicated in this github issue -
https://github.com/pallets/click/issues/966

It seems it was unfortunately broken in between and fixed after click 7.0. Could you try upgrading the version of click and seeing if that fixes it for you?

Thanks for bringing this to our attention.

**Comment by CT83** [comment]
Hmm, is there any way we could add Travis CI Integration to this? Maybe I could help?

**Comment by savingoyal** [comment]
@CT83 we already integrate with GitHub actions.

**Comment by CT83** [comment]
Oh, we do? I guess, I missed it.

Nice! 😇

**Comment by shivamy** [comment]
Upgraded click to 7.0 and that fixed the issue.  Thanks @seeravikiran, @savingoyal .
> pip freeze | grep -i click
click==6.7
> pip install -U click
...
> pip freeze | grep -i click
Click==7.0
> metaflow
Metaflow (2.0.0): More data science, less engineering
...
