### ISSUE TITLE
R installation failled - 'memory not mapped'

### ISSUE THREAD

**Issue by PaulCristina** [Netflix/metaflow#374]
# Build env  and install python libraries:
conda create --name r-metaflow python=3.7
conda activate r-metaflow
pip install metaflow
pip install numpy
pip install pandas

# R file
# set path for python
Sys.setenv(RETICULATE_PYTHON = "/home/paulc/anaconda3/envs/r-metaflow/bin/python")

reticulate::py_config()
#> python:         /home/paulc/anaconda3/envs/r-metaflow/bin/python
#> libpython:      /home/paulc/anaconda3/envs/r-metaflow/lib/libpython3.6m.so
#> pythonhome:     /home/paulc/anaconda3/envs/r-metaflow:/home/paulc/anaconda3/envs/r-metaflow
#> version:        3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)  [GCC 7.3.0]
#> numpy:          /home/paulc/anaconda3/envs/r-metaflow/lib/python3.6/site-packages/numpy
#> numpy_version:  1.19.2
#> 
#> NOTE: Python version was forced by RETICULATE_PYTHON

# install
devtools::install_github("Netflix/metaflow", subdir="R")
#> Downloading GitHub repo Netflix/metaflow@master
#> 
#>      checking for file ‘/tmp/RtmpCnnOPb/remotes8c322172c7e7/Netflix-metaflow-e47576f/R/DESCRIPTION’ ...  ✓  checking for file ‘/tmp/RtmpCnnOPb/remotes8c322172c7e7/Netflix-metaflow-e47576f/R/DESCRIPTION’ (364ms)
#>   ─  preparing ‘metaflow’:
#> ✓  checking DESCRIPTION meta-information
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>   ─  building ‘metaflow_2.2.0.tar.gz’
#>      
#> 
#> Installing package into '/home/paulc/R/x86_64-pc-linux-gnu-library/4.0'
#> (as 'lib' is unspecified)
metaflow::install_metaflow()
#> Metaflow (R) 2.2.0 loaded
#> Metaflow (Python) 2.2.4 loaded
# test installation
> metaflow::test()
Metaflow (R) 2.2.0 loaded
Metaflow (Python) 2.2.4 loaded
WARNING: ignoring environment value of R_HOME

 *** caught segfault ***
address 0x162e6, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(name)
 7: getNamespace(ns)
 8: asNamespace(ns)
 9: getExportedValue(pkg, name)
10: reticulate::virtualenv_list
11: envname %in% reticulate::virtualenv_list()
12: check_environment(envname)
13: activate_metaflow_env(pkg.env$envname)
14: fun(libname, pkgname)
15: doTryCatch(return(expr), name, parentenv, handler)
16: tryCatchOne(expr, names, parentenv, handlers[[1L]])
17: tryCatchList(expr, classes, parentenv, handlers)
18: tryCatch(fun(libname, pkgname), error = identity)
19: runHook(".onLoad", env, package.lib, package)
20: loadNamespace(package, lib.loc)
21: doTryCatch(return(expr), name, parentenv, handler)
22: tryCatchOne(expr, names, parentenv, handlers[[1L]])
23: tryCatchList(expr, classes, parentenv, handlers)
24: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
25: library(metaflow)
26: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
27: suppressPackageStartupMessages(library(metaflow))
An irrecoverable exception occurred. R is aborting now ...

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        pillar_1.4.6      compiler_4.0.2    remotes_2.1.1     prettyunits_1.1.1 tools_4.0.2       testthat_2.3.2    pkgload_1.1.0     digest_0.6.27    
[10] pkgbuild_1.1.0    jsonlite_1.7.1    evaluate_0.14     memoise_1.1.0     lifecycle_0.2.0   tibble_3.0.4      lattice_0.20-41   pkgconfig_2.0.3   rlang_0.4.8      
[19] reprex_0.3.0      Matrix_1.2-18     cli_2.1.0         rstudioapi_0.11   xfun_0.17         withr_2.3.0       knitr_1.29.4      rappdirs_0.3.1    desc_1.2.0       
[28] fs_1.5.0          vctrs_0.3.4       devtools_2.3.0    rprojroot_1.3-2   grid_4.0.2        reticulate_1.18   glue_1.4.2        R6_2.5.0          processx_3.4.4   
[37] fansi_0.4.1       rmarkdown_2.3     sessioninfo_1.1.1 callr_3.5.1       clipr_0.7.1       magrittr_1.5      whisker_0.4       usethis_1.6.3     backports_1.1.10 
[46] ps_1.4.0          ellipsis_0.3.1    htmltools_0.5.0   assertthat_0.2.1  renv_0.12.0-12    metaflow_2.2.0    crayon_1.3.4

**Comment by jasonge27** [comment]
hey @PaulCristina thanks for reporting the issue. Unfortunately, I wasn't able to reproduce. There're a few moving pieces for example pandas/numpy/reticulate versions, and your existing conda installation settings. 

I tried to install with R 4.0.2 ( the one you're using ) in a clean docker and it worked fine for me
```
from rocker/ml:4.0.2

RUN Rscript -e 'devtools::install_github("Netflix/metaflow", subdir="R")'
RUN Rscript -e 'metaflow::install_metaflow(method="conda", prompt=FALSE)'
ENV USERNAME mfuser
RUN Rscript -e 'metaflow::test()'
```
If you save it as a Dockerfile and build it via `docker build`, it should work smoothly. If the docker works, maybe you can compare the environment with the error instance, and triage the problem that's causing the segfault?
