### ISSUE TITLE
Issue due to New Dockerhub Pull Limits

### ISSUE THREAD

**Issue by Viveckh** [Netflix/metaflow#380]
Dockerhub released an update this week limiting the number of image pulls to about 100 every 6 hours. 

This affects the batch jobs for metaflow, which are pulling the base python image from Dockerhub to set up containers for every task. The limit of 100 is hit pretty fast.

To counteract this, I wanted to set up an ECR repo and put the default image that metaflow uses there. 
Which image would you recommend for me to pull from Dockerhub? Would latest python image be good?

Also would metaflow take care of installing the dependencies like in the past?

**Comment by savingoyal** [comment]
Hi!
By default, Metaflow pulls in the [Python docker image](https://hub.docker.com/_/python) corresponding to the version of the Python interpreter on your laptop. You can copy over the relevant image into ECR and configure metaflow (`metaflow configure aws`) to pull from ECR instead. 

Another option is to change your AWS Batch compute environment settings to authenticate with docker hub - https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/

**Comment by Viveckh** [comment]
Thanks @savingoyal . So while configuring is this the proper way to enter the ECR Repository URL and image name?

```
METAFLOW_BATCH_CONTAINER_REGISTRY: "{account_id}.dkr.ecr.us-east-1.amazonaws.com/{repo_name}" 
METAFLOW_BATCH_CONTAINER_IMAGE: "{repo_name}:latest"
```

I'm confused because the image name already seems to be a part of the repository URL provided by AWS ECR. So not sure then what should be entered in container name.

**Comment by savingoyal** [comment]
@Viveckh if say your repo name is `metaflow-images` and you are storing python images (`python:latest`) in it - 
```
METAFLOW_BATCH_CONTAINER_REGISTRY: "{account_id}.dkr.ecr.us-east-1.amazonaws.com/metaflow-images" 
METAFLOW_BATCH_CONTAINER_IMAGE: "python:latest"
```

**Comment by Viveckh** [comment]
Thanks @savingoyal . I actually have been using the following format, and it seems to be working.

```
METAFLOW_BATCH_CONTAINER_REGISTRY: "{account_id}.dkr.ecr.us-east-1.amazonaws.com" 
METAFLOW_BATCH_CONTAINER_IMAGE: "{repo_name}:latest"
```

**Comment by joe153** [comment]
ECR is definitely an easier route. ECR step by step:
1. create a new ECR repo called "metaflow-python"
2. tag the python image 
`docker tag docker_image_id account_id.dkr.ecr.us-east-2.amazonaws.com/metaflow-python:latest`
3. push the python image
`docker push account_id.dkr.ecr.us-east-2.amazonaws.com/metaflow-python:latest`
4. update metaflow config
```
"METAFLOW_BATCH_CONTAINER_REGISTRY": " account_id.dkr.ecr.us-east-2.amazonaws.com"
"METAFLOW_BATCH_CONTAINER_IMAGE": "metaflow-python:latest"
```
