### ISSUE TITLE
[Errno 62]: Too many levels of symbolic links - Issue building for Batch on OSX

### ISSUE THREAD

**Issue by iiAnderson** [Netflix/metaflow#381]
Hi,

So in the last week or so I've been getting a new issue when attempting to push Conda Flows to batch on OSX. This error has been reported by multiple people I work with all running OSX.
The error is huge, so I'll add it as an attached file.

1. Attempting to run the locally works perfectly, no issues. The only issue is when it's built for Batch.

2. Conda environment re-creation
I won't post the entire result from `conda list` but I'm utilising scikit-learn with pandas running under python3.7. I have recreated this environment several times all with the same error. I have also tried switching python versions within the Conda environment to no avail.

3. Running this same flow on a Linux machine (running ubuntu 18.04) allows me to push to Batch without an error, this error seems specific to building for linux-64 on OSX.

4. Attempting to run this command ('/Users/robanderson/anaconda3/bin/conda', 'create', '--yes', '--no-default-packages', '--name', 'metaflow_WorkshopModel_linux-64_9b36ea1f58460fc6b2af6d62b38172efacf658b4', '--quiet', b'python==3.7.8', b'click==7.1.2', b'requests==2.24.0', b'boto3==1.14.47', b'coverage==4.5.4', b'scikit-learn==0.20.1', b'pandas==1.1.4') mentioned in the error works ONLY if the conda environment does not exist, if it exists then the command fails. However, even if i ensure this environment is removed and attempt to deploy my Flow to Batch it still fails with the same error.

Does anyone know what's going on here? Because I'm at a loss as to what to try next!

(Also note, while I've said deploying to batch gives this issue, running step-functions create also gives the same error as shown below)
**Error**:
[error.txt](https://github.com/Netflix/metaflow/files/5522978/error.txt)

**Comment by savingoyal** [comment]
Hi! We have merged a fix for this issue - https://github.com/Netflix/metaflow/pull/377. I will make a release in a couple of hours.

**Comment by savingoyal** [comment]
The [release](https://github.com/Netflix/metaflow/actions/runs/357585862) is in-flight.

**Comment by iiAnderson** [comment]
Awesome - thanks for a speedy response!
