### ISSUE TITLE
Step Function Tasks Not Adding Tags

### ISSUE THREAD

**Issue by bassrock** [Netflix/metaflow#384]
I am currently using the following command to deploy a workflow to AWS Step Functions 

```
python Task.py --environment=conda --with retry step-functions create --tag production
```

All workflows run by the step-function are not getting this new `production` tag assigned to them. 

When I look at the Step Function definition in the AWS console, I do see that it is adding the tag to the command to run: `--with=batch --tag production` at the tail end so it is making it into the definition.

I've also tried the tag both locally from my machine and locally with AWS batch and they are getting applied there, so this seems limited to step functions.

**Comment by savingoyal** [comment]
I am able to reproduce this. Let me figure out what's happening and roll out a fix.

**Comment by savingoyal** [comment]
Which version of Metaflow are you running?

**Comment by bassrock** [comment]
@savingoyal Awesome! I am on 2.2.5 of Metaflow

**Comment by savingoyal** [comment]
@bassrock I am making a PR to fix this. In the meantime, you can access the tags from the corresponding steps - 
`tags = Run('MyFlow/42')['start'].tags`

**Comment by bassrock** [comment]
@savingoyal Thanks for the quick investigation! 

Unfortunately, we were trying to use this as a namespace to access all "production" flows easily. But we sidestepped for the time being by using `runtime:step-functions` (only our production flows are in step functions)

**Comment by savingoyal** [comment]
@bassrock You can use the above PR to unblock yourself. We will make a release on Monday.

**Comment by bassrock** [comment]
@savingoyal awesome thank you!
