### ISSUE TITLE
Non-trivial example

### ISSUE THREAD

**Issue by bonnevm** [Netflix/metaflow#39]
Is there a non-trivial example of a flow where steps are not running directly in the FlowSpec, but in different docker container?

```
    @step
    def a(self):
        # Step should be processed by a worker running "DockerImageA"
        self.next(self.b)
   @step
    def b(self):
        # Step should be processed by a worker running "DockerImageB"
        self.next(self.end)
```

**Comment by savingoyal** [comment]
Yes, indeed - you can run on AWS Batch with your own container - 
```
@batch(image="my_image")
@step 
def step(self):
    ...
```

**Comment by bonnevm** [comment]
Is there a way to run such a flow locally?

**Comment by savingoyal** [comment]
Not currently. What would be your use-case? You can specify specific dependencies locally using the `@conda` decorator as well.

**Comment by bonnevm** [comment]
Essentially testing workflows locally, where some of the steps are built by other teams in potentially other languages.

**Comment by savingoyal** [comment]
We don't support this today on the local instances. Our recommendation is to use `@conda` and/or execute in the cloud.

**Comment by seeravikiran** [comment]
Does @savingoyal 's last response answer your question? I'm wondering if we can close this issue as "will not fix".

**Comment by bonnevm** [comment]
Sorry for the delay. Yes it's answering my question.
