### ISSUE TITLE
Support for batch on fargate?

### ISSUE THREAD

**Issue by bcgalvin** [Netflix/metaflow#398]
This was recently announced at re:Invent and I've been trying to get it to work without much luck. Are there plans to support this or is Fargate not in the cards because of the lack of support for gpu etc?

**Comment by savingoyal** [comment]
@bcgalvin Great timing! I am working on a PR for that. Unfortunately, you won't be able to specify resources at the grain that batch + ecs allows but it will allow for quicker job start-up times.

**Comment by joe153** [comment]
This is huge when it comes to the quicker job start up time
