### ISSUE TITLE
Leave conda dependencies floating instead of pinned

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#399]
`@conda` currently pins some dependencies to specific versions (`requests`, `click` etc.). This can cause conflict with some other user-defined packages (`snowflake-client` etc.) which might pin the same packages to a different version. Also, anytime Metaflow updates the package versions, it ends up resolving the user environment again, which is undesirable. We should leave the dependencies floating.

**Comment by rchui** [comment]
@bishax The branch fell way behind and slipped off the backlog for the metaflow. You're welcome to revive it and give it another try.

**Comment by savingoyal** [comment]
addressed in #1505
