### ISSUE TITLE
Example / helper library for integrating with Spark/EMR

### ISSUE THREAD

**Issue by tuulos** [Netflix/metaflow#410]
Metaflow can be readily used with EMR/Spark on AWS using `boto` in a Metaflow task. However, this requires knowledge of `boto` and many other technical details. We could provide a wrapper library that makes e.g. using Spark for data processing more straightforward.

Context:

https://gitter.im/metaflow_org/community?at=5ff42c71c746c6431cf78fc2

**Comment by skamdar** [comment]
@tuulos what if we can have @emr like @batch decorator to execute Metaflow step in EMR.

**Comment by JensRoland** [comment]
Note that this same pattern would be useful not only for Spark, but also other types of jobs, e.g. Hive and Pig, as well as any future frameworks AWS decides to add.

**Comment by tuulos** [comment]
Yep, actually so it happens that I've been just developing an example showcasing this feature. Stay tuned!

**Comment by aabdullah-getguru** [comment]
Any update on this? I would love to use metaflow at my org, but basically some sort of EMR support and integration (even if its by example only) would be a must-have to get team buy in.

**Comment by npow** [comment]
The example is here: https://github.com/outerbounds/metaflow-pyspark/
