### ISSUE TITLE
Support AWS Batch Array Jobs

### ISSUE THREAD

**Issue by rchui** [Netflix/metaflow#415]
Metaflow should have the ability to invoke AWS Batch jobs as array jobs. Currently the preferred method of handling parallelism is to break out into multiple tasks using the `foreach` parameter but this creates a parallel task in the AWS state machine and can cause the AWS State machine to hit the maximum 25k state transitions very quickly. Throw in multiprocessing to resolve the history issue, and the solution for large scale outs can quickly become unwieldy.

AWS Batch array jobs were specifically designed to handle problems like this and it is a core feature of AWS Batch.

**Comment by savingoyal** [comment]
Thanks for the issue @rchui! We looked into AWS Batch array jobs while implementing both the `@batch` decorator as well as the AWS Step Functions integration. The parallelism semantics of array jobs don't allow us to control concurrency (`--max-workers`). Also, it's a bit non-trivial to implement nested `for-eaches` with array jobs. 

We have been in touch with the AWS Step Functions team to figure out a way to lift the 25k state transitions restrictions since it impacts all sorts of tall and(/or) wide workflows. But in any case, array jobs warrant a relook.

**Comment by seanv507** [comment]
Given https://gitter.im/metaflow_org/community?at=6030537c9337c51bc69a1543 which means that only 40 jobs can be parallelised at a time is there any way to help prioritise/collaborate on this?

**Comment by savingoyal** [comment]
Yes, @rchui and team are currently hacking an AWS Batch array implementation. We would love to understand your use case to make sure it can be supported.

**Comment by seanv507** [comment]
Our use case is that we have 1000s of models that we would like to train in parallel.  We have been using batch array jobs to handle this.  We would like to move to using metaflow, but realised that we will be very slow if only 40 jobs can run at once (using step functions).

**Comment by dgerlanc** [comment]
> Yes, @rchui and team are currently hacking an AWS Batch array implementation. We would love to understand your use case to make sure it can be supported.

Are ya'll looking for some assistance in getting this working?

**Comment by savingoyal** [comment]
We can definitely loop you in. Also, happy to brainstorm short-term fixes to unblock your use cases.

**Comment by dgerlanc** [comment]
We're attempting to run 100k plus MCMC sampling processes so we're hitting a wall  with Step Functions.

Even 5,000 separate flow executions exceeds the 25k Step Function limit.

Let me know what's the best way to chat further! You can email me at dan@gerlanc.com

**Comment by savingoyal** [comment]
Sending an email.

**Comment by savingoyal** [comment]
Metaflow now supports distributed map in step functions, that reduces the need to support Batch array jobs to work around the 25k state event limit
