### ISSUE TITLE
Global timeout for an entire flow

### ISSUE THREAD

**Issue by zexuan-zhou** [Netflix/metaflow#416]
I did some research on the documentation but couldn't find a desired answer. Is there a way to set up timeout for an entire Metaflow Flow?

Something like a `@timeout` decorator for the `FlowSpec` class?
```
from metaflow import FlowSpec, timeout, step
import time

@timeout(seconds=5)
class TimeoutFlow(FlowSpec):

    @step
    def start(self):
        time.sleep(10)
        self.next(self.end)

    @step
    def end(self):
        pass

if __name__ == '__main__':
    TimeoutFlow()
```

Thank you!

**Comment by tuulos** [comment]
@zexuan-zhou `step-functions create` supports a global `--workflow-timeout`. Having a flow-level `@timeout` like you suggested would be a good idea, so it would work for local runs too.

Thanks for the suggestion!

**Comment by zexuan-zhou** [comment]
> @zexuan-zhou `step-functions create` supports a global `--workflow-timeout`. Having a flow-level `@timeout` like you suggested would be a good idea, so it would work for local runs too.
> 
> Thanks for the suggestion!

Thank you for the fast reply. I wasn't aware of the timeout functionality in step functions. Appreciate it.
