### ISSUE TITLE
Support for another public cloud - Google Cloud Platform

### ISSUE THREAD

**Issue by IRLeif** [Netflix/metaflow#42]
Currently, Metaflow is set up to work with AWS as the default public cloud. The architecture of Metaflow allows for additional public clouds to be supported.

Adding support for Google Cloud Platform might broaden the potential user base, which could increase the adaption rate. This, in turn, could lead to increased community attention.

**Comment by savingoyal** [comment]
Duplicate of #22. Let's move the conversation to that issue.

**Comment by IRLeif** [comment]
Ah! Thanks for merging these issues, @savingoyal. I didn't notice that it already existed due to the abbreviated name in the other issue.
