### ISSUE TITLE
New S3 permissions in new releases?

### ISSUE THREAD

**Issue by Viveckh** [Netflix/metaflow#439]
So we adopted metaflow when it had first been open-sourced and we'd been using 2.0.2 until now. 
We decided to update to the latest 2.2.7 last week to benefit from the new updates, but now the flow fails when kicked off from the same EC2 instances stating the following error.

Were there new required S3 permissions that were added over time? And is dynamoDB an absolute requirement?
The S3 permissions I have are: 
* GetObject
* PutObject
* DeleteObject
* ListBucket

![image](https://user-images.githubusercontent.com/9113166/107965862-0c1ec080-6f79-11eb-84b5-5883272d7693.png)

**Comment by savingoyal** [comment]
Looks like `click>=7.0` isn't available in your python environment. Can you double-check that? We haven't introduced any new S3 permissions. DynamoDB is needed if you are converting your Metaflow flows into Step Functions state machines.

**Comment by Viveckh** [comment]
I see `click==7.1.2` installed along with metaflow in the python environment in the EC2.

**Comment by savingoyal** [comment]
Can you try again by installing `metaflow==2.2.7` in a `virtualenv` or a `condaenv` and executing your flow against the interpreter in that env? I tried to execute a flow with `metaflow==2.0.2` and the same flow with `metaflow=2.2.7` and was able to execute successfully.

**Comment by Viveckh** [comment]
Thank you @savingoyal, setting up a virtualenv and installing metaflow within it did the trick.
