### ISSUE TITLE
Adding volume info to batch decorator

### ISSUE THREAD

**Issue by mattmcclean** [Netflix/metaflow#441]
Would be useful to add volume information into the batch decorator so that EBS, EFS or FSx volumes can be attached to the jobs to access data quickly for training, cache pre-trained weights, cache data from S3 etc. 

Simplest version would be to pass in a mount path parameter into the decorator that will add two entries: `volumes` and `mountPoints` to the AWS Batch Job Definition `containerProperties` object.

https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#containerProperties

**Comment by savingoyal** [comment]
Makes sense. I will add it in the next release.

**Comment by savingoyal** [comment]
also, ulimits could be a great addition - https://gitter.im/metaflow_org/community?at=60403e47d2619a4f2e1f6766

**Comment by samuelthan** [comment]
Yeah, looking for to have this implement too. Our use case if more of intergration with AWS CodeArtifact to pull pip libraries, however there needs to be away of sharing the logged in mechanism :)

**Comment by savingoyal** [comment]
An update - a partial fix for this issue was part of Metaflow 2.3.5 - https://github.com/Netflix/metaflow/releases/tag/2.3.5#441

cc @samuelthan @mattmcclean

**Comment by NerdToMars** [comment]
hi, @savingoyal  do you have any plan to fully support this? 
I am new to metaflow. What I did is to modify the metaflow-aws terraform code to create efs with the correct subnet settings and mount efs when booting using the user data (https://aws.amazon.com/premiumsupport/knowledge-center/batch-mount-efs/). 

 Another tots is to modify the metaflow to create full volume json objects in the container definition, but will require user modify their cloud infra. Also clear documentation is required.
