### ISSUE TITLE
Code Version as Flow/Run/Step/Task Metadata

### ISSUE THREAD

**Issue by dorukhansergin** [Netflix/metaflow#442]
A similar tool, MLflow, also includes [git commit hash used for each run](https://mlflow.org/docs/latest/tracking.html#concepts), if the code is versioned via git.

This could be a nice feature to organize results even better. Especially since deleting previous runs are not as straightforward by design. I can filter out runs by whether they belong to the "valid code versions".

Whether at which level this information should be kept is unclear to me as I'm not familiar with the codebase. Especially being able to resume experiments complicate things a bit. I'm sorry I cannot provide more description on that side.

**Comment by savingoyal** [comment]
@dorukhansergin You can simply tag your run using the git commit hash - 
```
python myflow.py run `git rev-parse HEAD`
```
This will tag all the Metaflow artifacts with your current commit hash.

**Comment by dorukhansergin** [comment]
That's a fair solution @savingoyal . I respect the team's decision to stay unopinionated about this even though I think it's a must have. Thank you for the answer, I can close the issue if you're okay with that.
