### ISSUE TITLE
Metaflow 2.0.0 executing HelloFlow    Unknown user

### ISSUE THREAD

**Issue by ponggung** [Netflix/metaflow#45]
I am trying to run metaflow-tutorials on local mac.
after
```
pip install metaflow
metaflow
cd 00-helloworld 
python 00-helloworld/helloworld.py show
```

It shows the error
```
Metaflow could not determine your user name based on environment variables ($USERNAME etc.)
```

Did't I miss some step?
thanks

**Comment by meibenjin** [comment]
> I am trying to run metaflow-tutorials on local mac.
> after
> 
> ```
> pip install metaflow
> metaflow
> cd 00-helloworld 
> python 00-helloworld/helloworld.py show
> ```
> 
> It shows the error
> 
> ```
> Metaflow could not determine your user name based on environment variables ($USERNAME etc.)
> ```
> 
> Did't I miss some step?
> thanks

you can export USERNAME='your-name' to resolve this problem，see：https://github.com/Netflix/metaflow/blob/5c047cf6950975e5ea1b69bbc89fa1ff80cfa004/metaflow/util.py#L136

**Comment by tduffy000** [comment]
@ponggung 
They get resolved in the following order:
```
METAFLOW_USER
SUDO_USER
USERNAME
USER
```
So, as to @meibenjin 's point, try exporting something to any of them.

**Comment by savingoyal** [comment]
@ponggung Yes, @meibenjin and @tduffy000 are correct with their recommendations. That should get you going.

**Comment by seeravikiran** [comment]
@ponggung Please close this issue once you get unblocked. Thanks in advance.

**Comment by ponggung** [comment]
@meibenjin @savingoyal  
Thanks for your help~
` export USERNAME='your-name` works for me.
I build app with docker, so some environmental variables are empty.

**Comment by dr3s** [comment]
I don't know if this is the same issue but I wondering why this occurs, if the $USERNAME is already exported
```
➜  metaflow-tutorials python 01-playlist/playlist.py show
Metaflow 2.0.0 executing PlayListFlow    Unknown user:
    Metaflow could not determine your user name based on environment variables ($USERNAME etc.)

➜  metaflow-tutorials echo $USERNAME                        
amarch
```

**Comment by mausch** [comment]
I just got this error code too and when I googled I landed on this github issue.
Where are all the environment variables documented? If I google "METAFLOW_USER" I get four results: two from github issues and two from gitter.
