### ISSUE TITLE
Control the naming of metaflow output

### ISSUE THREAD

**Issue by Veganveins** [Netflix/metaflow#458]
It didn't look to me like there already was an issue related to this question so hopefully I'm not duplicating anything. Currently we're using metaflow to help train hundreds of thousands of different time series models concurrently, and the results are written to S3.

My question has to do with whether or not its possible to tell metaflow how you want it to name the files as they are written out to S3. One challenge I'm seeing is that the results appear to be written out such that the files are named according to the corresponding run_id / step_id / task_id. This makes it challenging to figure out, once all the models have been fit, which results correspond to which files.

For example: If I identify 100,000 models by the business segment it focuses on, each business segment has a segment_id (1, 2, .... n). When I use metaflow to fit models across all of these segments, the results are written out such that they files aren't named `results_1, results2, .... results_n.` Instead they're written out such that the files have somewhat mysterious names. 

Has anyone worked on a way to either: 

a) obtain a mapping from the segment_id that the results correspond to and the name metaflow assigns to the results?

or b) overwrite the default name metaflow assigns to the results with something based on the segment id, so when a user manually logs into S3 they can easily find and download the result for a segment of interest?

Hopefully this question makes sense. Happy to clarify further if not.

**Comment by savingoyal** [comment]
Hi @Veganveins,
There are a few different ways to achieve your objective - 
1. You can write your data to S3 explicitly by using the [`metaflow.s3` client](https://docs.metaflow.org/metaflow/data#data-in-s-3-metaflow-s3)
2. You can also use the metaflow client to identify the s3 location of a data artifact -
```
Run('MyFlow/42')['start'].task.artifacts.name._object['s3_location']
```

**Comment by savingoyal** [comment]
@Veganveins Please re-open the issue in case you need more clarification :)
