### ISSUE TITLE
How to set `--shm-size` for Docker when running Metaflow in AWS Batch

### ISSUE THREAD

**Issue by zexuan-zhou** [Netflix/metaflow#460]
Hello. Thanks for making Metaflow.

I recently ran into an issue that says

```shell
WARNING services.py:1567 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
```

I wonder how I can set `--shm-size` for the docker container Metaflow uses when running in AWS batch. 
Is it possible to pass it to the `@batch` decorator?

**Comment by savingoyal** [comment]
Yes, indeed - you can set it using the `shared_memory` attribute in `@batch`

**Comment by zexuan-zhou** [comment]
> Yes, indeed - you can set it using the `shared_memory` attribute in `@batch`

Thank you! I looked at the batch_client code and I wonder what's the difference between the `environment_variable` and the `@environment` decorator? https://github.com/Netflix/metaflow/blob/a655de9ef62870a668d68a1f656bd7b9b92b7a71/metaflow/plugins/aws/batch/batch_client.py#L301
Is it possible to pass multiple environment variables to the `environment_variable` in the `@batch` decorator?

**Comment by savingoyal** [comment]
You can pass multiple environment variables to your task by using the `@environment` decorator - `@environment(vars={'foo':'bar', 'alpha':'beta'})`
