### ISSUE TITLE
Start using mypy/typing (and drop Python 2.x support)

### ISSUE THREAD

**Issue by oavdeev** [Netflix/metaflow#473]
Creating this issue to start a discussion on possibly deprecating Python 2.x support, and introducing [optional typing](https://docs.python.org/3.6/library/typing.html) into Metaflow codebase.

### The Proposal
Stop supporting Python 2.x and require Python 3.6+ starting from the next Metaflow release, and start using `typing` where appropriate in the codebase. I think doing the same with Metaflow would make it much more contributor friendly, and will allow to remove a bunch of workarounds and tests that exist for 2.x

Going forward, follow the official [Python EOL timelines](https://endoflife.date/python) timelines for new Metaflow releases.

Naturally, older versions of Metaflow will continue to work with older versions of Python.

### Why
Most if not all mainstream data science-related project dropped support for Python 2.x quite a while ago, and started relying on typing features that are arguably quite useful in catching trivial bugs, while allowing to have fewer unit tests. 

Latest stable versions of Airflow, pandas, numpy, dbt,  all require Python 3.6+ if not 3.7+ these days. In fact, I struggle to find another OSS project tin this space that would still support 2.x. So even taking into account Metaflow focus on backwards compatibility, having Python 3.6 as a requirement seems to be a pretty conservative choice.

I have also pulled public stats from pip and only 0.05% of metaflow downloads are using less than 3.6 in March 2021 (28 downloads is the absolute number).

**Comment by romain-intel** [comment]
Python 2.x vs 3.6+ has been an interesting issue internally within Netflix (some flows were still on Python 2.x) but maybe something we can revisit. Not sure about typing (it may definitely help catch some bugs but also sometimes makes it a bit tricky). There are a bunch of other cleanup issues that have been raised which I think would be nice to address as a big cleanup effort after we merge the convergence branch.

**Comment by corleyma** [comment]
I fully support this and think adding typing (at least in key places) should make it much easier for new contributors to onboard to the Metaflow codebase.

In terms of benefits for consumers of Metaflow, there may be some obvious quick wins (e.g., making sure mypy et al. can correctly interpret `Parameter` objects).

**Comment by oavdeev** [comment]
@romain-intel are these 2.x flows still in use today?

Just to clarify, my proposal here is to simply declare that Python 2.x is no longer supported in Metaflow starting from version $N+1 so that contributors can start using Python3 syntax. That is, I wouldn't go and proactively add types everywhere in the existing code base right away, as that would complicate the convergence efforts. Rather, I imagine this will happen organically over time, where it makes sense.

**Comment by joe153** [comment]
@oavdeev  Thanks for doing the stats analysis. I agree with your above proposal. This would simplify things. 
https://python3statement.org/

**Comment by jimbudarz** [comment]
Is there any update on retiring Python 2 support? It would be nice to start contributing with Python 3 syntax, but of course it's possible some people are still using Python 2.

**Comment by savingoyal** [comment]
Typing support has been introduced in newer parts of the codebase - so this issue can be safely closed.

**Comment by vfilter** [comment]
Maybe I'm mistaken, but we're still getting typing issues on most imports with Pylance. Do we have tto manually import stubs?

![Image](https://github.com/user-attachments/assets/b8a69b5c-617e-47b9-96f7-0500645b2c1f)
