### ISSUE TITLE
Support for alternate conda package dependency resolver

### ISSUE THREAD

**Issue by jamesbsilva** [Netflix/metaflow#497]
I wanted to open this as a possible feature/enhancement. Solving for the environment can take some time in running flows and was wondering if support for alternate dependency resolvers like https://github.com/mamba-org/mamba is planned

The Proposal
Support for alternate dependancy resolver like  https://github.com/mamba-org/mamba to be able to speed up the part of running flows that requires resolving dependencies

Why
Iterate through flows faster

**Comment by savingoyal** [comment]
@jamesbsilva Yes, indeed a very timely issue. I have been wanting to carve out some time and test swapping out conda with mamba.

**Comment by savingoyal** [comment]
Also, linking #24 here.

**Comment by savingoyal** [comment]
Mamba as a conda package resolver is now available - you can set the environment variable (or add it into your `~/.metaflowconfig`) - `METAFLOW_CONDA_DEPENDENCY_RESOLVER=mamba` to use mamba instead of conda. The mamba executable needs to be in your `$PATH`.
