### ISSUE TITLE
A Metaflow slack bot

### ISSUE THREAD

**Issue by romain-intel** [Netflix/metaflow#5]
A Metaflow Slack bot could be used to query the status of currently running runs, inspect the results of past runs, etc. In other words, it is, among other things, a convenient interface to Metaflow's client API.

**Comment by SteNicholas** [comment]
@romain-intel Do you mean that this just reuse class Run to provide Run list?

**Comment by romain-intel** [comment]
In part yes. It's basically a different interface to the client API to, in part, see what's running and what has run through slack. Internally, this is useful for example for scheduled runs (something not yet supported in the OSS version but equivalent to Step Functions) because it's usually much easier to contact a slack bot than to open a terminal and type CLI commands :).

**Comment by SteNicholas** [comment]
@romain-intel Could I be assigned this issue to try to provide the interface?

**Comment by savingoyal** [comment]
@SteNicholas This issue relates to our plan around open-sourcing the slack bot that already exists internally at Netflix. You are of course most welcome to contribute a slack bot to the community. Please post a link to your repo/bot on this issue. Happy to provide any help as you go about it.

**Comment by savingoyal** [comment]
:tada: The Slack bot is now available in Open Source - https://github.com/outerbounds/metaflowbot. Please give us feedback at http://slack.outerbounds.co.
