### ISSUE TITLE
Support for Kubernetes (with Argo)

### ISSUE THREAD

**Issue by nlaille** [Netflix/metaflow#50]
Another implementation of #16 

This idea is to provide metaflow with native kubernetes implementation using Argo (https://github.com/argoproj/argo) for the workflow part.

**Comment by valayDave** [comment]
@nlaille : I was recently exploring building plugin support for Argo but the DAG templating seemed a little complicated to fit into Metaflow within a short amount of time. 

So meanwhile I have built a plugin to support Kubernetes with isolated self packaged deployments of the runtime itself to the cluster. It will require a service-based metadata provider. It will deploy the entire workflow's runtime as a job that will orchestrate different containerized jobs. So deploying your entire flow with its container orchestration on Kubernetes becomes one command: ``python myflow.py --with kube:cpu=2,memory=2000,image=python:3.7 kube-deploy run --custom_param_1 hello --custom_param_2 100``

It works using the `@kube` decorator. Supports the same features as the batch plugin. You can even use the ``--with kube:cpu=2,memory=2000,image=tensorflow/tensorflow:latest-py3``.  

https://github.com/valayDave/metaflow/tree/kube_cpu_stable

Documentation is in the links within that repo. The plugin is under constant development so there will be more features soon and hopefully even support Argo. But it is currently tied to S3 as its datastore and doesn't support GPUs. 

Hope this helps!

**Comment by alexec** [comment]
Argo team would be happy to help make this a reality.

**Comment by savingoyal** [comment]
@alexec That would be wonderful! Let me email you to set up some time.

**Comment by alexec** [comment]
You can book 30m: https://calendly.com/argoproj/30m

**Comment by repocho** [comment]
Ohhh my good. Thanks for this collaboration @alexec and @savingoyal  !!!

**Comment by terrytangyuan** [comment]
Is there any update on this? BTW, the URL for Argo Workflows has changed and the old URL does not redirect correctly. Here's the new location: https://github.com/argoproj/argo-workflows

**Comment by alexec** [comment]
This is an extremely popular issue. It'd be great to see it implemented.

**Comment by terrytangyuan** [comment]
FYI we now have a low-level Python SDK officially maintained by the Argo Workflows team. It should be much easier to use it to integrate Metaflow with Argo Workflows. https://github.com/argoproj/argo-workflows/tree/master/sdks/python

**Comment by savingoyal** [comment]
#992 is now available for review

**Comment by savingoyal** [comment]
#992 has been merged. The next Metaflow release will address this issue.

**Comment by alexec** [comment]
Yay!

**Comment by terrytangyuan** [comment]
Amazing work! Looking forward to the new release!

**Comment by repocho** [comment]
Thank you for making this possible !! 🥇

**Comment by savingoyal** [comment]
Support for Kubernetes and Argo Workflows is now available in Metaflow 2.6.0 - https://blog.argoproj.io/human-centric-data-science-on-kubernetes-with-metaflow-7f60aad34cba
