### ISSUE TITLE
How to run time consuming ML pipelines? - run user specified steps

### ISSUE THREAD

**Issue by ruaultadrien** [Netflix/metaflow#523]
I am currently using `DVC` as a ML pipelining framework. I just discovered `metaflow` and I am seriously considering using it as an alternative to `DVC`. Before that I just wanted to understand better the checkpointing mechanism and how we can deal with ML pipelines that are time consuming.

### Problem statement

Let's take the following 3 steps linear DAG example an let's imagine that the `preprocessing` step is very long to run:

`preprocessing -> model_selection -> evaluation`

My current understanding is that, using `metaflow`, we should encapsulate those three `steps` in a `FlowSpec` class to define a DAG. Now let's say that I change a bit the code of `preprocessing`, like some comments, but I still want its output to be checkpointed and be able only run the DAG from `model_selection` onward in my next DAG executions.

Is there a way to do this in `metaflow`?

### Ideas I was thinking of

- Shall I create a super DAG with `preprocessing` as a `FlowSpec` on its own?
- Or can I somehow instantiate the DAG and run a single step that reuses the latest version of the artifacts generated by previous steps?

**Comment by savingoyal** [comment]
@ruaultadrien Welcome to the Metaflow community! You can `resume` your flow from any arbitrary step and Metaflow will copy over the state from the previous steps and start the execution from the defined step. 

So, in your case - you could do `python flow.py resume model_selection` and Metaflow will copy over the results for `preprocessing` step from the last successful execution. If you want to copy over the results from a specific run, you can do `python flow.py resume model_selection --origin-run-id 42` and Metaflow will copy over results for `preprocessing` step from run number `42`. Here is some more information - https://docs.metaflow.org/metaflow/debugging#how-to-debug-failed-flows.

**Comment by ruaultadrien** [comment]
Thanks a lot for the answer :smile: , I'm gonna try this out!
