### ISSUE TITLE
Improve CTRL-C handling

### ISSUE THREAD

**Issue by romain-intel** [Netflix/metaflow#54]
The current handling of interrupted flows (ie: when the user hits CTRL-C while a flow is running) has two issues:
  - there is a mandatory 1 second wait for each and every subprocess running (ie: 1 per in-flight-task)
  - there is the possibility that the subprocesses are killed before they have a chance to clean up (this is particularly important for subprocesses handling Batch)

It should be possible to:
  - wait for all subprocess to properly shut down (with a timeout)
  - kill any stragglers

This would both eliminate the 1 second minimum time per task and avoid (or at least mitigate) early kills.

**Comment by savingoyal** [comment]
Fixed in https://github.com/Netflix/metaflow/pull/56
