### ISSUE TITLE
Error when creating workflow in Step Functions with non-default Dockerimage after upgrading Metaflow

### ISSUE THREAD

**Issue by denismaciel** [Netflix/metaflow#548]
I have upgraded Metaflow from 2.2.7 to 2.2.13 and the following command now errors:

```bash
$ python3 pipeline_shop_sales.py --package-suffixes='.json,.sql' step-functions --with batch:image=shop_sales create
Metaflow 2.2.13 executing ShopDailySalesFlow for user:denis
Usage: pipeline_shop_sales.py step-functions [OPTIONS] COMMAND [ARGS]...
Try 'pipeline_shop_sales.py step-functions --help' for help.

Error: No such option: --with
```
I have also tested it with 2.3.0 and the error persists.

I am trying to deploy a workflow to Step Functions with a custom Dockerimage.

**Comment by savingoyal** [comment]
Can you try - `$ python3 pipeline_shop_sales.py --package-suffixes='.json,.sql' --with batch:image=shop_sales step-functions create`

**Comment by denismaciel** [comment]
Problem solved, thanks, @savingoyal !
