### ISSUE TITLE
(R) Create individual `decorator` functions and improve documentation

### ISSUE THREAD

**Issue by mdneuzerling** [Netflix/metaflow#563]
Currently, R decorators are specified in a very general way:

```r
decorator(x, ...)
```

where `x` is the name of the decorator and `...` are the arguments provided to that specific decorator (similar to Python's `**kwargs`). This isn't ideal because it's difficult to:

* discover which decorators are available, 
* discover which arguments should be provided for a given decorator, 
* auto-complete arguments, and
* provide specific documentation for each decorator.

I propose that we create, for each decorator, a specific function that wraps the `decorator` function. For example,

```r
resources <- function(cpu = 1L, memory = 4096L) {
  decorator("resources", cpu = cpu, memory = memory)
}
``` 

Each of these can then be individually documented and unit tested, and we can link to available decorators from the man page for `decorator`.

There may be a slight issue with `environment`, which is a (pretty important) function in base R.

I'm happy to work on this as a PR, but I want to check that this approach is okay before I begin.

**Comment by savingoyal** [comment]
This makes total sense to me! @jasonge27 What are your thoughts?

**Comment by jasonge27** [comment]
Sounds like a good idea!
