### ISSUE TITLE
UnicodeDecodeError issue with 'MovieStatsFlow' tutorial

### ISSUE THREAD

**Issue by imohitmayank** [Netflix/metaflow#58]
After following the 'MovieStatsFlow' tutorial over [here](https://docs.metaflow.org/getting-started/tutorials/season-1-the-local-experience/episode02), after opening the jupyter lab on the provided notebook, getting 'UnicodeDecodeError' on the cell which gets the latest successful run.

`Exact error: UnicodeDecodeError: 'ascii' codec can't decode byte 0x85 in position 320: ordinal not in range(128)`

Image:
![Screenshot from 2019-12-15 21-57-56](https://user-images.githubusercontent.com/1883779/70865699-56c43780-1f86-11ea-8d11-c7c03f31c5ac.png)

**Comment by seeravikiran** [comment]
To help debug the issue could you print the python version in both the notebook and the environment when you ran the flow?
We have seen this happen before if the versions differ but just want to double check.

**Comment by imohitmayank** [comment]
Seems to be an Jupyter issue: [Jupyter running wrong python kernel](https://github.com/jupyter/jupyter/issues/270).

Running Python 3 on the both the sides (metaflow + lab) seems to work on my end. Lab is always loading python 3 (even if I specify python 2) and the environment was python 2 on default. 

Thank you.

**Comment by seeravikiran** [comment]
Thank you for reporting this. We ll look into reproducing the issue; and see if we can communicate this surprise in a better way.
cc @bergdavidj
