### ISSUE TITLE
Mutable default arguments usage in functions and methods

### ISSUE THREAD

**Issue by mpkocher** [Netflix/metaflow#6]
There appears to be several cases of mutable args (e.g., dict, list) set as default values in functions or methods. 

For example:
- metaflow/metadata/service.py
- metaflow/metadata/local.py

This pattern can often yield difficult to debug issues. 

https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

`pylint metaflow | grep W0102` can reveal the offending locations. 

Full list of sites: https://gist.github.com/mpkocher/7d2db19fcde3fc8e728c6143817fc024

**Comment by seeravikiran** [comment]
Thank you for reporting this. We will look into it and clean it up. 👍
