### ISSUE TITLE
More documention about when a task can clone vs re-run on resume

### ISSUE THREAD

**Issue by matt-land** [Netflix/metaflow#61]
If I have a flow defined with steps
- Foo
- Bar
- Baz

And I have a run where "Baz" fails...
And I explicitly resume my run at Baz...

...I want to know what causes Foo or Bar to rerun vs Clone, so I can re-write my code to not cause a re-run.

The current documentation says 
https://docs.metaflow.org/metaflow/debugging#resuming-from-an-arbitrary-step

>By default, resume resumes from the step that failed, like b above. Sometimes fixing the failed step requires re-execution of some steps that precede it.

That is pretty vague, so the user is left guessing.

**Comment by savingoyal** [comment]
Metaflow will always clone all the steps preceding the failed step by default and execute the failed step. If you type `python flow.py resume`, it will clone `foo` and `bar` and execute `baz` always. 

You can override that behavior and re-execute from an arbitrary preceding step by following the instructions - https://docs.metaflow.org/metaflow/debugging#resuming-from-an-arbitrary-step.  If you type `python flow.py resume bar`, it will clone `foo` and then execute `bar` always. 

Let me know if this answers your question.

**Comment by matt-land** [comment]
I think the confusion was that when metaflow chooses a default run to resume, it wasn't choosing the run that was furthest through the graph.

> run (5 steps in)
.... debug....
> resume (3 more steps in)
...
> resume (expected metaflow to to resume from the prior resume run)

**Comment by savingoyal** [comment]
Currently, metaflow `resume` resumes the last `run`. If you resume multiple times in succession (for example), you would notice that it resumes the same run id. You can override that behavior by specifying [`--origin-run-id`](https://docs.metaflow.org/metaflow/debugging#how-to-use-the-resume-command)

**Comment by savingoyal** [comment]
@matt-land Please comment and re-open the issue if you have any more concerns around this.
