### ISSUE TITLE
Metaflow should set propagated tags on AWS Batch Jobs

### ISSUE THREAD

**Issue by corleyma** [Netflix/metaflow#632]
Sometime last year, AWS Batch added the ability for the user to set tags (at job definition time, and at job submission time) that can [optionally propagate](https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#job-definition-parameters-propagate-tags) to the actual ECS tasks running the job.  This can be very useful because e.g. AWS Cost Explorer will let you attribute costs in ECS based on resource tags.

We should update the @batch/@stepfunctions integrations to enable tag propagation and begin setting the following tags when submitting a job:
- `metaflow.run_id`
- `metaflow.flow_name`
- `metaflow.step_name`

Optionally, these attributes might also be useful as resource tags:
- `metaflow.user`
- `metaflow.namespace`

There is a limit to the number of tags that can be set (50), and while we could expose functionality for users to pass through their own tags, this seems like the best MVP because these tags should be universally useful.

**Comment by savingoyal** [comment]
Also opened - https://github.com/Netflix/metaflow-tools/issues/35
