### ISSUE TITLE
Add API Reference to docs.metaflow.org

### ISSUE THREAD

**Issue by gatesyp** [Netflix/metaflow#636]
While implementing Metaflow with my team, I've been asked multiple times for some sort of API reference doc as a resource while getting up and running. 

On the docs currently there is a lot of situational documentation (eg [Developing with Metaflow](https://docs.metaflow.org/#developing-with-metaflow)), but there isn't an unopinionated collection of available methods / decorators / command line prompts / cli arguments (eg [python std lib reference docs](https://docs.python.org/3/library/), or [cpp reference](https://www.cplusplus.com/reference/)). 

We've started a personal scratch sheet of methods that we share as an internal reference as we learn more about Metaflow. 

Would having something like this fleshed out + added to the official documentation be useful to the project? 

EDIT: I see the [technical overview](https://docs.metaflow.org/internals-of-metaflow/technical-overview), which is a great start

**Comment by savingoyal** [comment]
That's good feedback that we will incorporate in our docs. Meanwhile, if you would like to open-source your internal scratch sheet, we can find an appropriate home for it. Let me now.

**Comment by swattstgtg** [comment]
Has there been any development on this? It would be incredibly useful to have something like a [read the docs](https://docs.readthedocs.io/en/stable/index.html) site that builds directly from the source code, so it is always a source of truth for the current state of the codebase

**Comment by savingoyal** [comment]
@swattstgtg Very timely - @hamelsmu is working on getting an initial version available soon.

**Comment by hamelsmu** [comment]
Related to https://github.com/Netflix/metaflow-docs/pull/37

**Comment by tuulos** [comment]
[A complete reference guide to all Metaflow APIs](https://docs.metaflow.org/api) was finally released today! Thanks for your patience 🙏
