### ISSUE TITLE
aws configure requires you to fill in optional fields

### ISSUE THREAD

**Issue by andaag** [Netflix/metaflow#64]
As per https://docs.metaflow.org/metaflow-on-aws/deploy-to-aws there is both optional and default fallbacks for variables. However, with metaflow configure aws you are required to fill them in instead of using defaults.

**Comment by savingoyal** [comment]
What version of Metaflow are you using? We released `2.0.1` yesterday fixing the issues outlined in #44.

**Comment by andaag** [comment]
Awesome, I'll give this another try and reopen if it's still an issue 👍.
