### ISSUE TITLE
can't create tasks in jobqueue

### ISSUE THREAD

**Issue by andaag** [Netflix/metaflow#65]
```
Metaflow 2.0.1 executing DataSelectionFlow for user:neuron
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
2019-12-17 18:24:58.096 Workflow starting (run-id 21):
2019-12-17 18:24:58.831 [21/start/39 (pid 21279)] Task is starting.
2019-12-17 18:24:59.709 [21/start/39 (pid 21279)] INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
2019-12-17 18:25:00.013 [21/start/39 (pid 21279)] An error occurred (ClientException) when calling the SubmitJob operation: JobQueue arn:aws:batch:eu-west-1:<accountid>:job-queue/job-queue-<local username>-metaflow-test not found.
2019-12-17 18:25:00.723 [21/start/39 (pid 21279)] Task failed.
2019-12-17 18:25:00.723 This failed task will not be retried.
    Internal error:
    The end step was not successful by the end of flow.
```

At the same time this works just fine:
```python
import os
import json
import boto3
client = boto3.client("batch")
queue = json.load(open(os.path.expanduser("~/.metaflowconfig/config.json"), "rb"))["METAFLOW_BATCH_JOB_QUEUE"]
client.list_jobs(jobQueue=queue)
```
Results in  'HTTPStatusCode': 200...

What am I doing wrong here?

My anonymized config:
```
{
    "METAFLOW_BATCH_JOB_QUEUE": "arn:aws:batch:eu-west-1:<account id>:job-queue/job-queue-<aws username>-metaflow-test",
    "METAFLOW_DATASTORE_SYSROOT_S3": "s3://<aws username>-metaflow-test-metaflows3bucket-<bucket identifier>",
    "METAFLOW_DATATOOLS_SYSROOT_S3": "s3://<aws username>-metaflow-test-metaflows3bucket-<bucket identifier>/data",
    "METAFLOW_DEFAULT_DATASTORE": "s3",
    "METAFLOW_DEFAULT_METADATA": "service",
    "METAFLOW_ECS_S3_ACCESS_IAM_ROLE": "arn:aws:iam::<account id>:role/<aws username>-metaflow-test-BatchS3TaskRole-<random identifier>",
    "METAFLOW_SERVICE_INTERNAL_URL": "https://<random identifier>.execute-api.eu-west-1.amazonaws.com/api/",
    "METAFLOW_SERVICE_URL": "https://<random identifier>.execute-api.eu-west-1.amazonaws.com/api/"
}
```

**Comment by savingoyal** [comment]
@andaag Did you use the latest version of the [cloudformation template](https://github.com/Netflix/metaflow-tools/blob/master/aws/cloudformation/metaflow-cfn-template.yml) to deploy your infrastructure? Does the user have `SubmitJob` privileges on the queue?

**Comment by savingoyal** [comment]
Also, given that you are using `eu-west-1`, can you confirm that `region = eu-west-1` in your AWS config?

**Comment by queueburt** [comment]
Seconding Savin on the region being the first place to start troubleshooting.  Specifically, the `An error occurred (ClientException) when calling the SubmitJob operation: JobQueue arn:aws:batch:eu-west-1:<accountid>:job-queue/job-queue-<local username>-metaflow-test not found.` error indicates that either the AWS shell is configured to default to a different region than the job-queue, the job-queue is either mistyped or non-existent, or there's a permissions problem.

Assuming the regions are correct, can you verify that you can see the Job Queue under the AWS Batch section of the console and that it's named correctly?

**Comment by andaag** [comment]
It was a region issue, thanks a lot for the help guys! I had "two" profile default's in my aws config. I'm guessing different defaults were read different places.

```
[profile default]
region = eu-west-1

[default]
region = eu-central-1
```

Thanks a lot for the help!
