### ISSUE TITLE
Don't hardcode `coverage` settings

### ISSUE THREAD

**Issue by tuulos** [Netflix/metaflow#650]
Currently, `coverage` is enabled automatically when you run Metaflow with `coverage run`. Its configuration is hardcoded https://github.com/Netflix/metaflow/blob/master/metaflow/cli.py#L848

which is problematic e.g. if you want to set `branch=False`. We should make it possible to disable `coverage` altogether and make it configurable.

**Comment by savingoyal** [comment]
Issue no longer applies since we have yanked coverage from the code base.
