### ISSUE TITLE
MetaflowExceptionWrapper always contains None?

### ISSUE THREAD

**Issue by lsimoneau** [Netflix/metaflow#677]
When calling `task.exception` the returned object is always `metaflow.exception.MetaflowExceptionWrapper(None)` regardless of the exception that was actually raised.

Looking at the code it seems like this is meant to be holding the underlying exception, so I imagine it's not supposed to just have `None`?

**Comment by savingoyal** [comment]
@lsimoneau Depending on how the task exited, the value of `task.exception` may well be None. If you can expand on your scenario, we can do some digging.

cc @oavdeev

**Comment by valayDave** [comment]
@lsimoneau : Can you check `task.exception.exception`. It is storing the exception but the `repr` is not perfect coming out perfect;  To see the exception better you can do `str(task.exception)`

**Comment by lsimoneau** [comment]
@valayDave Thanks for that, `task.exception.exception` does have the underlying exception. I can do a PR to add a `__repr__` here https://github.com/Netflix/metaflow/blob/master/metaflow/exception.py#L11 to at least show the class of the underlying exception at least?

**Comment by valayDave** [comment]
@lsimoneau: Maybe try `task.exception.type` to get the class of the underlying exception?
