### ISSUE TITLE
Tutorial suggestion: Batch prediction and real time prediction

### ISSUE THREAD

**Issue by elben10** [Netflix/metaflow#69]
Metaflow looks really promising! 

The issue is somewhat related to #49 

It would be really great with at least one example on how to use the library to do ML predictions. It would be great if it showed the following use cases

- Batch prediction (Fairly obsious)
- Real time prediction for instance in a rest service (Not as obvious)

**Comment by savingoyal** [comment]
Duplicate of #49. @elben10 let's move the conversation to that issue.

**Comment by savingoyal** [comment]
Duplicate of #49
