### ISSUE TITLE
Multi programs languages support. 

### ISSUE THREAD

**Issue by oshriPP** [Netflix/metaflow#74]
Hi,
I would like to know, how difficult is to integrate other program languages like Golang, Julia...?
Assume I have a Go program, that gets the input using local file and CLI args.
1. How can I deliver the Go exe file into the node/cluster?
2. What is the best way to download the data to a local file (with python that is used as a wrapper to download the data and run the Go program)?

**Comment by savingoyal** [comment]
You can use `—package-suffixes=.go` to include your .go files (or even IncludeFile for that matter) and ship them onto the remote cluster. That will allow you to execute them using a `os.system` or `subprocess.check` call within a Pythonic metaflow flow. Regarding the best way to download the data, that depends on where the data is stored, what is the volume and what is the access pattern. Can you elaborate on that?

**Comment by oshriPP** [comment]
Thank you for your help. 
I'll check the `-package-suffixes` option, I hope it will help me. 
I the data stored in Redis as a list-data-type. I need to download several keys save in local files, read the files with go, save the results in different files and upload the results with the Python wrapper.
