### ISSUE TITLE
No mention of the License in the Documentation

### ISSUE THREAD

**Issue by GadgetSteve** [Netflix/metaflow#75]
Hi it is great that you have Open Sourced MetaFlow but there is no mention of the actual license at https://docs.metaflow.org/introduction/what-is-metaflow (or the search engine doesn't find it).

At  a great many companies before you can use any Open Source components or workflows you have to get approval from the Lawyers and they tend to be much more comfortable if they can see the license in the documentation _(and not as happy digging into the source code)._

**Comment by savingoyal** [comment]
Thanks for pointing out. We will add the license to the docs.

**Comment by romain-intel** [comment]
Done. Added to the documentation.
