### ISSUE TITLE
Package code only once for execution on AWS Batch

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#759]
Context - https://outerbounds-community.slack.com/archives/C02116BBNTU/p1634152820010000 reachable via slack.outerbounds.co

**Comment by zexuan-zhou** [comment]
Hi just want to check if there is any update on this issue? Thanks

**Comment by savingoyal** [comment]
Not yet. Is it a blocker? If so, we can look into it.

**Comment by madhur-ob** [comment]
@savingoyal I guess this is already fixed, courtesy of https://github.com/Netflix/metaflow/blob/master/metaflow/cli.py#L830 and https://github.com/Netflix/metaflow/blob/master/metaflow/cli.py#L888

Also, seen from the screenshot below:
<img width="1199" alt="Screenshot 2024-01-18 at 5 04 43 AM" src="https://github.com/Netflix/metaflow/assets/155637867/2ff5c6c7-5ab4-4c8d-9263-a8be9eee49eb">

I have 3 steps here, all of them executing on `batch`...

The code is packaged only once, and not 3 times... as seen by the line:
`Code is packaged here...` in the screenshot above..

Further, I have tried to modify the contents of the flow while the flow is running -- at different times...
and I checked the logs on the UI, I didn't find my modified print statements in the logs..
So indeed, the code package is frozen at the start and editing of the code doesn't interfere with the flow that is submitted..

Thus, I guess this issue can be closed, unless something else has to be done here...
