### ISSUE TITLE
Meaning of 'self' is not clear in metaflow flows

### ISSUE THREAD

**Issue by akyrola** [Netflix/metaflow#787]
This is a metaflow design related comment that Ville asked me to write down. 

In metaflow flowspecs, the artifacts are recorded by setting them as attributes as "self". However, with foreach, the semantics of "self" become unclear:
- join() actually discards all fields of "self", and the attributes need to be merged from the "inputs" (merge_artifacts is good, but it is not applied automatically). If one does not do this, they simply disappear.
- what is the meaning of "self" in a foreach task, as there are many replicas? If one modifies some field in the self, would one expect all the others see the same change?

Same issue arises with steps that are run in parallel. There are many replicas of 'self'.

Perhaps a more intuitive and consistent design would be to explicitly pass a state object from step to another, instead of modifying "self". Then it is clearer that one works with copies.  This would maybe make flow composition easier as well.

**Comment by marcellovictorino** [comment]
That was very confusing indeed. I am glad I found this issue which helped me understand how to keep the self attributes after a join/merge in operation.

> See [documentation](https://docs.metaflow.org/metaflow/basics#data-flow-through-the-graph)

**Comment by vikramsoni2** [comment]
@akyrola self in foreach is indeed a copy of parent self object. It carries all variables from parent step. Also you can add more variables to self which can be accessible to next step ( if you have multiple steps inside foreach). each consecutive step will get only the object from its previous step of the same iteration. 
in the join step, you get array of inputs, where each member is an object and all variables you have created in self inside foreach will be assigned to this object. oh, it sounds really complicated..:D if you need an example I can post a gist.
