### ISSUE TITLE
wrong decorator sequence leads job failure

### ISSUE THREAD

**Issue by Jeffwan** [Netflix/metaflow#79]
If I put `@conda` decoration here, I get errors like following. Seems we have to put `@step` close to function first. From logs, seems this is by design, I am checking if there's need to ignore sequence if both of them exist.

```
    @step
    @conda(libraries={'pandas' : '0.24.2'})
    def compute_statistics(self):
```

Get errors like this.
```
Traceback (most recent call last):
  File "02-statistics/stats.py", line 17, in <module>
    class MovieStatsFlow(FlowSpec):
  File "02-statistics/stats.py", line 60, in MovieStatsFlow
    @conda(libraries={'pandas' : '0.24.2'})
  File "/usr/local/lib/python3.7/site-packages/metaflow/decorators.py", line 341, in wrap
    return _base_step_decorator(decotype, f, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/metaflow/decorators.py", line 326, in _base_step_decorator
    raise BadStepDecoratorException(decotype.name, func)
metaflow.decorators.BadStepDecoratorException: You tried to apply decorator 'conda' on 'compute_statistics' which is not declared as a @step. Make sure you apply this decorator on a function which has @step on the line just before the function name and @conda is above @step.
```

**Comment by savingoyal** [comment]
Can you clarify your concern? The error log is descriptive enough with respect to how to resolve this issue.

**Comment by Jeffwan** [comment]
Yeah, I agree. This is the first time I write a workflow. Log is pretty clear and I am wondering if we can remove this check or handle it in the backend and we won't see these kind of issues. This can be an improvement on the development experience.

**Comment by savingoyal** [comment]
Python decorators aren’t commutative and it’s better to have a consistent style in the codebase for better readability.
