### ISSUE TITLE
Trying to run HelloAWSFlow() from the tutorials after using console_scripts

### ISSUE THREAD

**Issue by siddarthsreeni** [Netflix/metaflow#808]
I'm trying to run HellowAWSFlow from `the metaflow-tutorials/05-hellowaws` py file. Instead my directory looks like this:
refer: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

```
src
  -- package_1
      --metaflow.py (same as helloaws.py)
setup.py # consists of console_script
requirements.txt
```
This wraps the metaflow.py into `bin/app` and helps make metaflow.py an executable. I'm getting errors in doing this. Any help? How can I run metaflow.py#main not as python3.6 metaflow.py run? 

```
On running : `app run` 

  File "build/bin/app", line 33, in <module>
  File "/home/<>/runtime/lib/python3.6/site-packages/package_1/metaflow.py", line 59, in main
    HelloAWSFlow()
  File "/home/<>/runtime/lib/python3.6/site-packages/metaflow/flowspec.py", line 78, in __init__
    self._graph = FlowGraph(self.__class__)
  File "/home/<>/runtime/lib/python3.6/site-packages/metaflow/graph.py", line 165, in __init__
    self.nodes = self._create_nodes(flow)
  File "/home/<>/runtime/lib/python3.6/site-packages/metaflow/graph.py", line 174, in _create_nodes
    if isinstance(n, ast.ClassDef) and n.name == self.name][0]
IndexError: list index out of range
```
UPDATE: 
```
python: 3.6.14
metaflow: 2.4.2
```
If I directly run python3 metaflow.py run (It is able to succesfully run and work)

**Comment by uvashisth** [comment]
I'm facing the same issue as well. Were you able to solve it?

**Comment by savingoyal** [comment]
can you create a new python file that simply invokes `subprocess.check_call(['python', 'flow.py', 'run'])` and make that file an executable?

**Comment by uvashisth** [comment]
Thank you very much @savingoyal, it worked for me :)
