### ISSUE TITLE
Add a way to securely inject secrets into AWS Batch

### ISSUE THREAD

**Issue by mmiermans** [Netflix/metaflow#814]
# Problem
Some of our Metaflow steps need to connect to a database using secret credentials. Currently we use boto3 to get these from AWS SecretsManager, but this requires [a little bit of code](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html#SecretsManager.Client.get_secret_value). It would be nice if these secrets would be securely injected as environment variables, which AWS Batch supports:

https://docs.aws.amazon.com/batch/latest/userguide/specifying-sensitive-data-secrets.html#secrets-envvar

# Solution
> We can enable this for AWS Batch. We have a similar functionality for Kubernetes. 

[Outerbounds Slack thread](https://outerbounds-community.slack.com/archives/C02116BBNTU/p1635958797165600?thread_ts=1635958686.164300&cid=C02116BBNTU)

**Comment by erichhhhho** [comment]
Not able to access the outerbounds thread. May I know if there is any on this issue?

**Comment by savingoyal** [comment]
https://docs.metaflow.org/scaling/secrets
