### ISSUE TITLE
Downloading code package on AWS Batch fails with ImportError: cannot import name 'OP_NO_TICKET' from 'urllib3.util.ssl_'

### ISSUE THREAD

**Issue by davified** [Netflix/metaflow#818]
Hi there, thanks for the great work on Metaflow :-) 

We're encountering an error when Metaflow attempts to download a code package to a batch instance, and we were wondering if others are encountering the same error as well.

### Issue

When any step is executed as a batch job, it fails when attempting to download the code package. Error logs:

```
Setting up task environment.
Downloading code package...

Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
... (truncated logs)
File "/usr/local/lib/python3.7/dist-packages/botocore/httpsession.py", line 10, in <module>
    from urllib3.util.ssl_ import (
    ImportError: cannot import name 'OP_NO_TICKET' from 'urllib3.util.ssl_' (/usr/lib/python3/dist-packages/urllib3/util/ssl_.py)
Failed to download code package from s3://metaflow-metaflows3bucket-19faa8kq3vn7c/metaflow/SplineInferenceFlow/data/78/78dcf3ba7c0b4ae533ecce7fde578828e7f4ccf7 after 6 tries. Exiting...
```

### Observations:
- We have multiple Flows, and they were all executing fine yesterday.
    - last successful run: Nov 07 2021 09:32:40 (UTC time)
-  But just starting from today, all steps executing as a batch job started failing consistently with the error above
    - first (of multiple) failed runs: Nov 08 2021 22:34:39 (UTC time)

Thanks for your time!

**Comment by davified** [comment]
Hi there, just to update on this - the issue resolved itself (jobs started running without this error at around 
 Nov 09 2021 00:40:00) without any code/infra changes on our side.

We were running Flows (and batch jobs) with a static base image (e.g. my-image:v70). Both successful and failed batch jobs were using the same image, so the installed version of `urllib3` must have been the same. So it puzzles me why this issue happened and how it got resolved 🤷‍♂️

**Comment by ahmadhori** [comment]
We had the same exact issue, also everything started to work again without us changing anything.

**Comment by katidieter** [comment]
Probably the issue happen because of [this dependency issue](https://github.com/boto/botocore/issues/2562) and it is fixed already.
