### ISSUE TITLE
Problem with @conda

### ISSUE THREAD

**Issue by eemlnv** [Netflix/metaflow#839]
Hi All,

I have some problems when I use code from [tutorial](https://docs.metaflow.org/metaflow/dependencies#local-execution).
After command _**python main.py --environment=conda run**_ this problem happened.
The screen with problem is attached.
![IMAGE 2021-11-25 02:42:16](https://user-images.githubusercontent.com/64747198/143326046-f9a20648-ee79-4ede-87af-56dbc6fe6b78.jpg)

Thanks,
Egor

**Comment by savingoyal** [comment]
@eemlnv Any updates?
