### ISSUE TITLE
Task doesn't execute if non-exist S3 bucket used

### ISSUE THREAD

**Issue by Jeffwan** [Netflix/metaflow#84]
Seems we can only use existing bucket for data storage and access. I tried to use a non-exist bucket name `hhehehedadsa`, the task is blocked and never move forward. 

```
with S3(run=self, bucket='hhehehedadsa', prefix='/my/prefix') as s3:
```

```
python3 s3demo.py run
Metaflow 2.0.1 executing S3DemoFlow for user:shjiaxin
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint not found, so extra checks are disabled.
2019-12-27 12:49:33.261 Workflow starting (run-id 44):
2019-12-27 12:49:33.559 [44/start/186 (pid 1292)] Task is starting.
##########################
Task is blocked here and no more progress. 
##########################
```

**Comment by savingoyal** [comment]
We will take a look. Looks our our exponential backoffs are too conservative in this case.

**Comment by matt-land** [comment]
+1 if I forget to set my metaflow envirnment variables, the step halts forever with no output.

**Comment by romain-intel** [comment]
Looked at the PR. It looks good. We should get it merged soon. Thanks for the fix!
