### ISSUE TITLE
Run a flow from another python file

### ISSUE THREAD

**Issue by rvorias** [Netflix/metaflow#842]
Hi,

I was wondering if it's possible to run a flow from anything other than a script:
e.g.
```python
from flow import ParameterFlow
ParameterFlow()
```

I'm currently getting the following error `TypeError: object of type 'NoneType' has no len()`

update:
ok so the first stage is solved:
```python
from flow import ParameterFlow
ParameterFlow(use_cli=False)
```

However, I normally give 2 parameters. Anyone know how to set them?

update 2:
ok ok I can just set the attributes

But how do I actually RUN the flow? thx

**Comment by savingoyal** [comment]
@rvorias We have plans to support [programmatic execution of flows](https://docs.google.com/document/d/1HJW9TH6lHEUojqDTzfgJZJXgjg3xZr43-p8_vjYJM1c/edit#heading=h.thnxk5pwrpsa). Meanwhile, you can use the Python subprocess module to invoke the flow.

**Comment by kathy-lee** [comment]
@savingoyal May I ask is there another update on this topic please, it seems the doc link above long time not updated. Thank you!!

**Comment by savingoyal** [comment]
this is now supported - https://outerbounds.com/blog/metaflow-in-notebooks-and-scripts
