### ISSUE TITLE
Setting parameters on resume

### ISSUE THREAD

**Issue by lambdaofgod** [Netflix/metaflow#88]
Being able to set parameters of downstream steps seems like a good idea.

An example:
Someone might run a costly feature extraction step, and then want to use a lot of different fast models. For now, one would have to explicitly define cross-validation before the whole pipeline is set in motion.

> If your flow has Parameters, you can't change their values when resuming. **Changing parameter values could change the results of any steps, including those that resume skips over,** which could result to unexpected behavior in subsequent steps.
> The resume command reuses the parameter values that you set with run originally.

I understand that fragment. But I do on the other hand think it seems pretty intuitive that there since the computations form a DAG, there is a first step where parameter is used, so changing its value before that step won't change any previous results.

If this seems so intuitive (at least doable) is there some other way that I can or should get similar functionality? I remember asking about composing flows, but it seems like there is no such feature. Am I missing something?

**Comment by romain-intel** [comment]
Currently, metaflow doesn't actually track which artifacts are used where (they are lazily loaded). In other words, there is currently no easy way for us to know whether or not a step used a parameter.

To do what I think you are asking though, you can actually compose flows using the client API. You can define your expensive feature extraction step in a flow and then everything that uses that in other flows (or a flow with a parameter if you want to continue using parameters). In that flow, you can then refer to your feature extraction flow (using, for example `Flow("FeatureExtraction").latest_successful_run.data` to get access to the artifacts at the end of the flow). Does that make sense? Happy to give more details if this is unclear.
