### ISSUE TITLE
Naked exception catching

### ISSUE THREAD

**Issue by mpkocher** [Netflix/metaflow#9]
As I've been looking to the code a bit, I'm running into a lot of "naked" except catching. 

E.g., 

```python
try:
     return json.loads(value)
except:
     self.fail("%s is not a valid JSON object" % value, param, ctx)
```

There's a difference between `except:` and `except Exception:`. 

https://docs.python.org/3/library/exceptions.html#exception-hierarchy

The list of potential issues can be obtained by `pylint metaflow | grep W0702`. 

In general, I would humbly suggest addressing some of the low hanging fruit from pylint as well as using a formatting tool such as black or autopep8.

**Comment by seeravikiran** [comment]
Yes indeed. We plan to follow up after the first release.
Thanks for reporting though.
