### ISSUE TITLE
Launching FlowSpec from within the interpreter

### ISSUE THREAD

**Issue by eliorc** [Netflix/metaflow#91]
A common use-case in our organization (even when not implemented through Metaflow) is being able to chain / mix and match workflows, and the most obvious implementation for this requires the ability to launch a workflow run from within the code.

#### Example:

Lets say we have two workflows `TrainAwesomeModelFlow` and `TrainSuperModelFlow`, which both train models
Assume that our evaluation is complicated and involves multiple steps, and is implemented in `EvaluationFlow`. We would like that for any workflow that trains a model (the two mentioned above, and potentially more in the future) to allow evaluation after it using the `EvaluationFlow`.

In practice, we'd expect to be able to call the `EvaluationFlow` from the code and pass parameters to it.
For example if the `EvaluationFlow` expects a model and we would like to chain the training and evaluation we would want it to looks something like:

```python3
if __name__ == '__main__':
    flow = TrainAwesomeModelFlow()
    EvaluationFlow(model=flow.model)

# In a different script
if __name__ == '__main__':
    flow = TrainSuperModelFlow()
    EvaluationFlow(model=flow.model)
```

Or alternatively we could add an evaluation step to the `TrainAwesomeModelFlow` and `TrainSuperModelFlow` which would look like something like this

```python3
class TrainAwesomeModelFlow(FlowSpec):

    ...

    @step
    def evaluate(self):

        EvaluationFlow(model=self.model)
```

Obviously we would like to preserve the separation of the flows when expecting results through the client

In both cases, executing flows and passing parameters to them directly from the code is necessary and will allow much more flexibility in the orchestration of connecting flows together, mixing and matching.

**Comment by jaychia** [comment]
I posted something similar in the community chatroom as well, something like this might be really nice to have:

```
class SuperFlow(FlowSpec)
    ...
    @subflow_step(SubFlow)
    def run_subflow(self, subflow_run):
        # do something with the successful subflow_run object
        self.subflow_result = subflow_run['end'].task.data.subflow_result
        self.next(self.continue_superflow)
```

And when accessing data through the client,
```
run = Flow('SuperFlow').latest_run
run['run_subflow'].task.subflow_run['subflow_run_step'].task.data
```

**Comment by eliorc** [comment]
Actually that is a consequence of that, but not exactly what I mean.

The general idea is to be able to execute tasks from within the code, regardless of where they are at. Maybe its a part of another script I am using or whatever - and also a very good use case will be calling one metaflow workflow from another metaflow workflow as you said.

So yeah, what you mentioned is a very important feature to have but this issue is about the broader ability to execute tasks through code

**Comment by romain-intel** [comment]
Merging with #117
