### ISSUE TITLE
Indentations being ignored on `show`

### ISSUE THREAD

**Issue by eliorc** [Netflix/metaflow#92]
When documenting classes or methods there are some common formats, like [NumPy](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html), [Google](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) and the standard reStructuredText format - all which involve indentations.

When using the `show` command line argument, these indentations are being ignored

#### Example:

train_benchmark.py

```python3

from metaflow import FlowSpec, step


class TrainBenchmarkModelFlow(FlowSpec):
    """
    Train a benchmark model

    Example
    -------

    Train a benchmark model

    .. code-block:: bash

        python train_benchmark.py run
    """
    ...

if __name__ == '__main__':
    TrainBenchmarkModelFlow()
```

Running `python train_benchmark.py show` results in 

```bash
Metaflow 2.0.1 executing TrainBenchmarkModelFlow ...

Train a benchmark model

Example
-------

Train a benchmark model

.. code-block:: bash

python train_benchmark.py run

```

Notice in the output the indentation is ignored. It will be helpful to have the correct indentation for better readability

**Comment by romain-intel** [comment]
Thanks for the suggestion, we will look into it.
