### ISSUE TITLE
Code and environnment versioning

### ISSUE THREAD

**Issue by jeanmidevacc** [Netflix/metaflow#93]
Hello @metaflow,

I am opening this issue because i have a question for you about versioning.

I am currently running multiple run with metaflow for a test project. When I am accessing the information about my runs I can access to the the flow,run and step informations but on a specific step I am trying to see the content of the environment info and the code but nothing is stored inside (screenshot attached).

![image](https://user-images.githubusercontent.com/23313992/72101002-b990c080-32f1-11ea-848a-5ac3db148d93.png)

So I  was wondering if the logging of the code and the environment info need a specific setup on the script to be done ?

Thanks in advance.

Setup:
* local test
* metaflow 2.0.1

**Comment by romain-intel** [comment]
Currently, the code is only stored if you run with Batch. We may change this behavior to store it for local runs as well.

**Comment by jeanmidevacc** [comment]
Thanks Romain for the update !!

**Comment by romain-intel** [comment]
Merging with #124
