### ISSUE TITLE
Artifact writes to S3 silently fail between Metaflow stages (Metaflow 2.3.3)

### ISSUE THREAD

**Issue by tmwong2003** [Netflix/metaflow#942]
I suspect that Metaflow 2.3.3 is either not receiving or silently ignoring sporadic S3 failures when writing task data artifacts at the end of a step. TL;DR: I wonder if one needs to consider a `HEAD` lookup right after calls to `boto3.S3.Client.upload_fileobj()` to ensure that S3 actually wrote the object.

In our case, the (simplified) flow looks like this:
```
    compute
     ↙ ↓ ↘
fork0 ... fork5
     ↘ ↓ ↙
     join
```
In `join`, Metaflow tries to retrieve an input artifact `my_artifact` from `fork4` seven times before failing, each time failing on `botocore.exceptions.ClientError`:
```
S3 datastore operation _get_s3_object failed (An error occurred (404) when calling the HeadObject operation: Not Found). Retrying 7 more times..
...
2022-02-04 14:02:45,952 ERROR [flow_run_id:sfn-b05d2d9b-cec4-4fce-96c0-a2a0f9a14e43 flow_name:MyFlow flow_step:join flow_task_id:4ee9c423-38bc-4a9d-8b26-ae8fcb3b0164 mlflow_run_id:-] [pid:59 metaflow_custom.plugins.decorators.step.runtime_metrics.task_finished:181] User step function raised an unhandled exception: botocore.exceptions.ClientError
```
Looking in the `fork4` task data attribute `[task].data._artifacts` shows that Metaflow cataloged the artifact:
```
'my_artifact': DataArtifact('MyFlow/sfn-b05d2d9b-cec4-4fce-96c0-a2a0f9a14e43/promoted_model_evaluation_fork/f65866d7-c9bf-4ec9-91e0-436358abf534/my_artifact')
```
and recorded a data key in `0.data.json` file for the task at `s3://my-metaflow-bucket/MyFlow/sfn-b05d2d9b-cec4-4fce-96c0-a2a0f9a14e43/promoted_model_evaluation_fork/f65866d7-c9bf-4ec9-91e0-436358abf534/0.data.json`, with hashed data key `d1f84ff71a71797b7c073c0bd339136a49b9f3f5`. Unfortunately, attempting to retrieve attribute `[task].data.my_artifact` results in the 404 retry loop, while attempting to retrieve the raw S3 object at `.../MyFlow/data/d1/d1f84ff71a71797b7c073c0bd339136a49b9f3f5` fails because the object is not there. The other task artifacts exist, as verified by printing out the other `[task].data` attributes; the only artifact I could not verify was an extremely large artifact that I could not load into my AWS management instance.

I suspect that a large upload (handled under the covers in `upload_fileobj()` by multipart uploads) is failing in a way that does not raise a `ClientException` that is visible to Metaflow, or alternatively that Metaflow is silently ignoring `ClientException` when saving objects. If the former is the culprit, a call to `boto3.S3.Client.head_object()` would relatively check that an `upload_fileobj()` succeeded.

**Comment by romain-intel** [comment]
There are two paths to upload files; could you let me know how many total artifacts are saved for that task (basically the number of entries in this 0.data.json).

**Comment by tmwong2003** [comment]
For each of the `forkN` tasks we write 72 objects.

```
for i, t in enumerate(tasks):
    data = fs.json.read(
        f"s3://our-metaflow-bucket/{t.pathspec}/0.data.json"
    )
    print(f"Task {i} wrote {len(data['objects'])} objects")
``` 
yields
```
Task 0 wrote 72 objects
Task 1 wrote 72 objects
Task 2 wrote 72 objects
Task 3 wrote 72 objects
Task 4 wrote 72 objects
Task 5 wrote 72 objects
```

**Comment by romain-intel** [comment]
Thanks. This helps. So you are getting this error sporadically? For the six tasks that wrote these 72 objects, how many objects failed?

**Comment by tmwong2003** [comment]
Yes. It's not consistent across Metaflow runs; the run from several weeks ago failed on a different artifact. In this case, all six tasks appear to have failed writing that same string list artifact, and it appears to be the only affected artifact.

**Comment by tmwong2003** [comment]
... we had a possible epiphany over here. We are required to expire certain Metaflow artifacts stored in AWS S3 automatically after 30 days for various compliance reasons. Metaflow uses a hash on the contents to derive a name for an artifact and simultaneously discover whether an artifact is automatically mergeable, yes? One wonders if once in a while we get caught out by S3 expiring an artifact. For common, simple artifacts like recurring string labels (`self.population_name`), we might get caught out by this race condition.

**Comment by tmwong2003** [comment]
In this situation, we'd want a way to reset the expiry timer with the equivalent of the *nix `touch` command.

**Comment by romain-intel** [comment]
Ah. That may indeed be the case. It is quite possible that the following happens:
  - MF wants to upload an artifact and therefore hashes it
  - If MF finds the hash exists in S3, it will not re-upload it but simply note "this is where my artifact is)
  - your artifact is expired and goes away
  - bug

We have internally been discussing how to deal with this as last I checked (but admittedly it has been a little while), AWS S3 does not support a "touch" functionality (although there may be ways around it). It's a bit of a thorny issue because we would also maybe want to update the metadata.

At any rate, I think this probably explains it. We have *never* seen this type of issue internally and have been running MF for quite a while but yes, we do not have expiring buckets (at least for MF artifacts).

**Comment by romain-intel** [comment]
I am going to close this for now. I believe the explanation is the issue you point out. If something else comes up, please reopen.

**Comment by tmwong2003** [comment]
> I am going to close this for now. I believe the explanation is the issue you point out. If something else comes up, please reopen.

Yes, thank you. We have no observed a mid-execution deletion recently, and have a few potential workarounds available.
