### ISSUE TITLE
Present Metaflow at the Argo Workflows community meeting

### ISSUE THREAD

**Issue by alexec** [Netflix/metaflow#951]
I know that the Argo support has not been implemented yet, but I think it would be great to see meta-flow presented at our community meeting.

**Comment by savingoyal** [comment]
@alexec For sure! How/where can I sign up?

**Comment by alexec** [comment]
We do a meeting every 3rd Wednesday at 10am PT. People tend to present on topics (often ML) for about 20m. 

Let me know when is good for you and I'll pencil you in!

http://bit.ly/argo-wf-cmty-mtng

**Comment by alexec** [comment]
Can I push you to come talk in March? We've got Katib talking this week and I think it is too much.

**Comment by savingoyal** [comment]
For sure! Let's do March!

**Comment by alexec** [comment]
@savingoyal would you be able to do a demo of the workflow integration? That would go down really well.

**Comment by savingoyal** [comment]
Yes indeed! That's the plan.
