### ISSUE TITLE
Allow passing custom resource tags to AWS batch job

### ISSUE THREAD

**Issue by stevenhoelscher** [Netflix/metaflow#963]
Metaflow [supports adding resource tags to AWS Batch jobs](https://docs.metaflow.org/introduction/release-notes#support-resource-tags-for-metaflows-integration-with-aws-batch), but as far as I can tell, [does not allow passing custom resource tags](https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/aws/batch/batch.py#L250-L263).

Zooming out, my desire is to [restrict the `batch:TerminateJob` permission](https://github.com/outerbounds/terraform-aws-metaflow/blob/3fd23c1f68cae5137e268394e85b8532dded873f/modules/step-functions/iam-step-functions.tf#L21-L29), narrowing it from the currently scoped `*` in the AWS Terraform template.

From [the AWS docs](https://docs.aws.amazon.com/batch/latest/userguide/batch-supported-iam-actions-resources.html#batch-supported-actions-terminatejob), there's two ways to narrow the resource scope:

1. Use prefixes, suffixes, etc. to subset jobs: `arn:aws:batch:region:account:job/jobId`
2. Use a `aws:ResourceTag/${TagKey}` conditional block

I haven't thoroughly investigated [whether it's possible to customize the jobId](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch.html#Batch.Client.submit_job) when submitting AWS Batch jobs with approach (1).

For approach (2), I can't seem to find an immutable tag to rely on (the logic being `aws:ResourceTag/${TagKey} = ${TagValue}`). Here's an example using my local scheduler:

| key | value |
| --- | --- |
| metaflow.step_name | start |
| metaflow.flow_name | MyFlow |
| metaflow.version | 2.5.0 |
| metaflow.run_id | 1645143018690796 |
| metaflow.user | developer |

Some useful tag key-values might be `Service:Metaflow` (for limiting users to only terminating Batch jobs spawned by Metaflow) or `Team:Foo` (for limiting users to only terminating Batch jobs spawned with their team/organization).

**Comment by savingoyal** [comment]
@stevenhoelscher We can add the tag - `app:Metaflow`. Would that work?

**Comment by stevenhoelscher** [comment]
> @stevenhoelscher We can add the tag - `app:Metaflow`. Would that work?

Works for me!

**Comment by stevenhoelscher** [comment]
Closing this issue.

With the [latest change](https://github.com/Netflix/metaflow/pull/970), a condition can now be applied when granting `TerminateJob` permissions.

Here's a Terraform example:
```
condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/app"
      values = [
        "metaflow"
      ]
    }
```
