### ISSUE TITLE
`Table.from_dataframe` only get first 5 rows

### ISSUE THREAD

**Issue by JulesBelveze** [Netflix/metaflow#968]
Hey all,

I am using `Metaflow (2.5.2)` and I am playing around with the `Card` component and I'm trying to create a `Table` from a `pandas.DataFrame` but I'm seeing a weird behaviour.
It seems like creating a `Table` from a dataframe only allows the first five rows, whereas directly instantiating the object doesn't  have this limitation.

Code to reproduce:
```python3
>>> df = pd.DataFrame.from_records([("TEST", 1)] * 10, columns=["a, "b"])
>>> Table.from_dataframe(df)._data
[[0, 'TEST', 1],
 [1, 'TEST', 1],
 [2, 'TEST', 1],
 [3, 'TEST', 1],
 [4, 'TEST', 1]]
>>> Table([["TEST", 1]] * 10)._data
[['TEST', 1],
 ['TEST', 1],
 ['TEST', 1],
 ['TEST', 1],
 ['TEST', 1],
 ['TEST', 1],
 ['TEST', 1],
 ['TEST', 1],
 ['TEST', 1],
 ['TEST', 1]]
```

Am I doing something wrong ??

Thanks for the cool stuff you guys are building! 😃

**Comment by valayDave** [comment]
` Table.from_dataframe(df,truncate=False)` should work

**Comment by JulesBelveze** [comment]
Indeed, sorry wasn't looking at the right object in the source code 😅 
Thanks @valayDave !
