### ISSUE TITLE
Step functions task definition ContainerOverrides length over 8192

### ISSUE THREAD

**Issue by redabuspatrol** [Netflix/metaflow#977]
Hi,

I am having the following error when launching a flow on AWS step functions.

```
 "Status": "FAILED",
  "StatusReason": "Container Overrides length must be at most 8192"
```

It seems my flow generates a task definition where the `ContainerOverrides` property is longer than 8192 chars.
My flow runs fine on AWS Batch, though it seems SFN doesn't like it very much.
Is there something I could try and do to get around this, or is this an issue with Metaflow itself?

Thanks a lot.

**Comment by savingoyal** [comment]
Would it be possible for you to share the output of `python flow.py step-functions create --only-json`? If you want to share it privately, you can DM me at chat.metaflow.org. We have some checks in place to catch this edge case but it could very well be the case that we are violating some condition unintentionally.

**Comment by redabuspatrol** [comment]
I just shared it with you over the outerbounds slack, please let me know if anything

**Comment by savingoyal** [comment]
@redabuspatrol [This](https://github.com/Netflix/metaflow/pull/979) PR will ensure that your workflow can execute again. We should be able to ship it out soon!

**Comment by savingoyal** [comment]
I will spend some time in a bit further compressing the `ContainerOverrides` field.
