### ISSUE TITLE
Storage space for containers when using @batch

### ISSUE THREAD

**Issue by mathdone** [Netflix/metaflow#99]
I'm trying to read a fasttext bin file that is stored in S3. I need to download it to allow the library to read the file from disk (it won't allow me to load from memory + that would require me to double the memory requirements). The default container space is about 10GB which is not nearly enough.
I can create and attach an EFS or EBS via launch templates, but mounting them inside the containers has been a challenge. I can also increase the container size using the "user data" portion of the launch template, but that is a huge workaround because it increases the space of every container that is spawned in the same machine. 
Right now I'm trying to implement a "mount" parameter via the batch decorator and I'm trying to figure out how to modify the job definition, but I'm not sure if that is going to work well.

pls hlp xD

**Comment by savingoyal** [comment]
The recommended approach is to have a custom AMI with the needed storage within an unmanaged AWS Batch compute environment. You can follow the steps listed here for example - https://stackoverflow.com/questions/52768937/how-to-define-root-volume-size-in-aws-batch
